### ISSUE TITLE
Server for production

### ISSUE THREAD

**Issue by cyberwombat** [wellyshen/react-cool-starter#10]
Thank you for your work. Do you have plans to get the server code transpiled for production? Right now it uses babel register instead of being run through Webpack or Babel

**Comment by wellyshen** [comment]
@cyberwombat I have ever considered about it. But not quit sure, what's the benefit if I do this?

**Comment by cyberwombat** [comment]
According to Babel docs you should not run any production code with [babel-register](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/user-handbook.md#toc-babel-register). Instead transpile it with [babel cli](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/user-handbook.md#babel-cli) first. You have your server entry file in a different place than the rest of the server code so that makes it a little awkward to do the entire server directory so perhaps move it to the "server" dir then you can easily babelify the entire directory in your `build` phase.

**Comment by wellyshen** [comment]
@cyberwombat Thank for your suggestion, I will enhance for it ;)

**Comment by cyberwombat** [comment]
Great thank you. btw.. I've been looking for an HMR/Webpack2/Redux starter for days (as well as trying to modify my own) and I have downloaded maybe 10+ kits and yours is the only one that does hot reloading without errors. Good job!
