### ISSUE TITLE
Is it possible to have cache for some request from node side?

### ISSUE THREAD

**Issue by amerllica** [wellyshen/react-cool-starter#1028]
I'm using `react-cool-starter` for a project and it seems I will need cache from server, for example some pages doesn't need to call BE APIs for several times and when user call it several times the node server should just answer by using its cache.

Is it possible for to have cache in this awesome configuration?

**Comment by wellyshen** [comment]
@amerllica Take a look at [React-Query](https://react-query.tanstack.com) or [SWR](https://swr.vercel.app). They can help us cache data without hitting the node server.
