### ISSUE TITLE
JPG files do not work

### ISSUE THREAD

**Issue by iamacup** [wellyshen/react-cool-starter#103]
Hi

I can't get JPG files to work and don't understand webpack / the underlying loaders enough to fix it - can you take a look @wellyshen when you have time please?

I have a broken commit here that you can use to replicate it: https://github.com/iamacup/sliips-ui/commit/aae472941ff378526d6ccdf3a156a4ee73247bc6

Note that PNG does seem to work :)

When including a JPG with require into an src value on an img tag, you get the following:

```
webpack building...
./src/containers/App/assets/dog.jpg
Module build failed: Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/tpickard/Desktop/sliips-ui/node_modules/mozjpeg/vendor/cjpeg
  Reason: Incompatible library version: cjpeg requires version 36.0.0 or later, but libpng16.16.dylib provides version 35.0.0

    at Promise.all.then.arr (/Users/tpickard/Desktop/sliips-ui/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
 @ ./src/containers/App/index.js 39:40-67
 @ ./src/client.js
 @ multi babel-polyfill react-hot-loader/patch webpack-hot-middleware/client?reload=true ./src/client.js

**Comment by wellyshen** [comment]
@iamacup I tried and I found only the `.jpg` file broke. And I try this [way](https://github.com/tcoopman/image-webpack-loader/issues/51#issuecomment-258194751). It's works for me.

**Comment by iamacup** [comment]
ahh its an environment issue not an issue with the project - my apologies and thanks :)
