### ISSUE TITLE
Trying to strip Redux from the Project

### ISSUE THREAD

**Issue by aagentah** [wellyshen/react-cool-starter#104]
Hi there, My apologies as this isn't an error as such, but I am seeking some assistance with this boilerplate - So I'm currently trying to strip Redux from this boilerplate to help me learn react without a global state manager.

Other than the obvious action, reducer and store pages, what else in the project uses Redux to help configure the boilerplate? For example, the server.js seems to use Redux in a number on places though I'm not sure how to configure it to work without redux, how difficult would this be to do?

Thank you in advance
Dan

**Comment by wellyshen** [comment]
@danjonesdev, 
If you want to get rid of redux from the `server.js`, you need to remove:
- Remove the `Provider` of react-redux.
- Remove the `configureStore` and the related store, history configurations etc.
- Adjust the action of the loadData method from `routes.js`.
- Adjust the html rendering template.
- And more...

This project is mainly designed for redux, react and react-router. If you want to get rid of redux from server-side. I suggest to do some study from google to realize the theory of server-side rendering. I spend half year to understand how it works ;)

**Comment by aagentah** [comment]
Thank you for your input!
