### ISSUE TITLE
Error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

### ISSUE THREAD

**Issue by smartcris** [wellyshen/react-cool-starter#105]
I'm currently using windows, to fix this issue I tried adding an .eslintrc with `/*eslint linebreak-style: ["error", "windows"]*/`, but then I got this error :

> D:\apps\react-cool-starter>yarn build:client
> yarn build:client v1.0.2
> $ yarn clean:client && better-npm-run build:client
> running better-npm-run in D:\apps\react-cool-starter
> Executing script: clean:client
> 
> to be executed: "rimraf ./build/public/assets"
> running better-npm-run in D:\apps\react-cool-starter
> Executing script: build:client
> 
> to be executed: "webpack --progress --hide-modules --config ./tools/webpack/webpack.client.babel.js"
> Hash: 6385ef822779212c8ca4
> Version: webpack 3.6.0
> Time: 23660ms
>  4 assets
> 
> ERROR in ./src/client.js
> Module build failed: Module failed because of a eslint error.
> 
> D:\apps\react-cool-starter\src\client.js
>   3:1  error  Parsing error: The keyword 'import' is reserved
> 
> ? 1 problem (1 error, 0 warnings)
> 
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by martin2786** [comment]
You need to add on package.json, under rules this line:

    "linebreak-style": 0,

So it will look like:

"rules": {
      "linebreak-style": 0,
      "global-require": 0,
      ....

And remove the other stuff you've added.

**Comment by smartcris** [comment]
thx that fixed my issue

**Comment by shahidkarimi** [comment]
@martin2786 there is nothing like "rules" in package.json

**Comment by martin2786** [comment]
@Shahidkarimi it is on eslintconfig section in package.json

**Comment by joseph-teb** [comment]
------------------for windows globe in package.son will read all import files---add--

"rules": {
"linebreak-style": 0,
"global-require": 0,
"eslint linebreak-style": [0, "error", "windows"],

**Comment by crescent-igor** [comment]
If you are using vscode i would recommend you to click the option at the bottom-right of the window and set it to LF from CRLF..this fixed my errors

**Comment by jocarsoft** [comment]
> If you are using vscode i would recommend you to click the option at the bottom-right of the window and set it to LF from CRLF..this fixed my errors

example please!

**Comment by crescent-igor** [comment]
> > If you are using vscode i would recommend you to click the option at the bottom-right of the window and set it to LF from CRLF..this fixed my errors
> 
> example please!

![screenshot from 2019-02-05 11-35-26](https://user-images.githubusercontent.com/31757907/52255837-3543f980-293a-11e9-9cfa-c7df5d4fb1f5.png)
Go to the LF /CRLF to toggle it

**Comment by JaveedIshaq** [comment]
> If you are using vscode i would recommend you to click the option at the bottom-right of the window and set it to LF from CRLF..this fixed my errors

Thanks

**Comment by gigamesh** [comment]
> If you are using vscode i would recommend you to click the option at the bottom-right of the window and set it to LF from CRLF..this fixed my errors

This only works for the currently selected file, correct? I'm trying to get eslint to run properly in windows on a repo that is all LF. Not having any luck with these suggestions.

**Comment by MichalKoder** [comment]
> > If you are using vscode i would recommend you to click the option at the bottom-right of the window and set it to LF from CRLF..this fixed my errors
> 
> This only works for the currently selected file, correct? I'm trying to get eslint to run properly in windows on a repo that is all LF. Not having any luck with these suggestions.

I had similar problem with whole project and not just single files and fixed it with the following command: 
npx eslint . --fix
