### ISSUE TITLE
index.js - unexpected token

### ISSUE THREAD

**Issue by aagentah** [wellyshen/react-cool-starter#108]
Hi, So after downloading the project > installing with `yarn install` > then running `start` I get the following error:

```
C:\Users\Dan (Mosquito)\Desktop\react-cool-starter-master\index.js:20
).server(dirRoot, () => {
^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
[nodemon] app crashed - waiting for file changes before starting...
```

I also tried  `start: production` first but it breaks on the same part.
Any help or suggestions?
Thanks

**Comment by iamacup** [comment]
What happens when you run `yarn build` followed by `yarn start`?

**Comment by aagentah** [comment]
build runs fine, but then running start returns the same error man @iamacup

**Comment by iamacup** [comment]
This is a wierd Windows specific issue that i was able to recreate.

If you __remove the comma at the end of the require line for WIT.config__ to make the code look like this:

```
// Settings of webpack-isomorphic-tools
global.webpackIsomorphicTools = new WebpackIsomorphicTools(
  require('./tools/webpack/WIT.config')
).server(dirRoot, () => {
  require('./src/server');
});
```

It should work

It is questionable syntax anyway, but it does work fine on nix

@danjonesdev can you check that it works and i will pop a PR in.

**Comment by martin2786** [comment]
@iamacup good catch! just tried and removing the comma works, even formatting with prettier or similar removes the comma automatically, that's why I never got the error.

**Comment by aagentah** [comment]
@iamacup I can confirm that did the trick, thank you kindly!
