### ISSUE TITLE
fsevents

### ISSUE THREAD

**Issue by ghost** [wellyshen/react-cool-starter#11]
I work for a large factory where I develop and maintain software that does measurements, analysis and produces reports about the process. Because it is used at different places I once decided to make a web application and use php/js/jquery as tools. It is running good but because of the size hard to maintain so I have started to look for a better solution. 
I investigated Agular but didn't like it because of Google (the factory is in China and a lot of Google services are blocked), so I looked for another solution and thought Meteor with React might be a good start until I read about the deployment issues - it seems Meteor only wants to have it installed on their own servers..
React/Nodejs is in the end the way I want to give a try and hot loading would be nice to improve the development speed. So I stumbled upon react-cool-starter because I don't want to reinvent the wheel.

I started to install it but received the following message:

aevl@aevl-Lenovo:~/react/react-cool-starter$ npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN eslint-config-airbnb@12.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
npm WARN eslint-config-airbnb-base@8.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
aevl@aevl-Lenovo:~/react/react-cool-starter$ 

I could start the server without problems but I am not sure what to think about the warning, can you explain?

The os I run it on is Lubuntu 16.04.1 (Xenial)

**Comment by wellyshen** [comment]
Hi @vanarieleyen 

The warnings come from the dependencies side not the project. So, you don't need to worry about it. You can run the project without any problem, which means you are get already to start off your project base on the starter kit ;)
