### ISSUE TITLE
Warning: Prop `className` did not match. Server: "jr9PI" Client: "styles__header-jr9PI"

### ISSUE THREAD

**Issue by aagentah** [wellyshen/react-cool-starter#111]
Hi... again (I'm an error magnet I know)

So here is my process:
clone project > `yarn install` > `yarn build` > `yarn start`

On initial page load, everything works fine.
After a refresh, the page's styling messes up + my browser (chrome) logs:

> Warning: Prop `className` did not match. Server: "jr9PI" Client: "styles__header-jr9PI"

NOTE: this does not happen whilst running `yarn start:production`, only in development mode.

Any help / advice is appreciated
Thank you in advance.

**Comment by iamacup** [comment]
I get the same thing on the master branch.

It looks like its something to do with what the webpack loaders do with the class names that are included through the import statement. Not sure how to fix and i think @wellyshen is on holiday at the moment.

It might be (you will have to test) possible to work around this by replacing the calls to hydrate from react-dom with render from react-dom - this should force the client to just render out what it has? - note if this works it will give you a notice about deprication in v17 or something so if it works its a short term fix ;-)

**Comment by wellyshen** [comment]
@danjonesdev It's a known issue about this project, I listed it as one of my [troubleshooting](https://github.com/wellyshen/react-cool-starter#troubleshooting). It only occur in dev environment sometimes when you use css modules. Actually I have no idea why it happens, I guess it maybe a bug of react or webpack loader. If you guys have great solution for it, please share to me lol.

BTW, I'm busying for my own react-native project at this moment lol.

**Comment by jeghers** [comment]
It is happening to me a LOT.  I want to migrate TWO projects into this Starter Kit, but this is a showstopper for me, and I'll have to find another kit soon.

**Comment by jeghers** [comment]
It is happening to me a LOT. I want to migrate TWO projects into this Starter Kit, but this is a showstopper for me, and I'll have to find another kit soon. I suggest this issue be re-opened

**Comment by wellyshen** [comment]
@jeghers It only happens on development environment sometimes. Currently I don't have great solution for it. I guess it's an issue of react server-side rendering. Maybe server-side hot reloading can solve this issue. If you found a kit which without this issue, please let me know ;)

**Comment by jeghers** [comment]
I have seen it when I run production also. The symptoms vary, in some cases
all of the CSS styling is present and everything looks correct but then
some JavaScript logic is missing and none of the UI behavior is there at
all. Other times that you I behave properly and at least part of the
styling is missing. Almost like not enough items from the webpack bundling
Got Loaded into the browser...?

**Comment by wellyshen** [comment]
Hi Guys, this issue has been fixed by this [commit](https://github.com/wellyshen/react-cool-starter/commit/d43e73cd68d7aa38346d2641bdc8277b5f15efd4).

BTW, the warning won't occurs while you start the development environment. But it will occurs when you change code on client side and **refresh browser page** by F5. Because the hot-reloading isn't implemented on server-side.

**Comment by jeghers** [comment]
Ok so far so good.  I will test further later tonight.  Thanks again.
