### ISSUE TITLE
Server and Client classNames do not match

### ISSUE THREAD

**Issue by malixsys** [wellyshen/react-cool-starter#113]
```
warning.js?6327:33 Warning: Prop `className` did not match. Server: "_2bi0E" Client: "styles__header-2bi0E"
```
Element has html:
`<div class="_2bi0E">`
React extension shows:
`<div className="styles__header-2bi0E">`

**Comment by malixsys** [comment]
Can be fixed by moving `.header` from under `.App` in _**src/containers/App/styles.scss**_

**Comment by wellyshen** [comment]
@malixsys Thanks for give me this instruction, I have removed it ;)
