### ISSUE TITLE
Unable to start the package

### ISSUE THREAD

**Issue by AbhayShiro** [wellyshen/react-cool-starter#114]
After installing packages I ran yarn start to run this project, I got the following error:
`).server(dirRoot, () => {
^
SyntaxError: Unexpected token )`

Please help

**Comment by iamacup** [comment]
see https://github.com/wellyshen/react-cool-starter/issues/108 for fix :)

will make it into master branch soonsies :)

**Comment by wellyshen** [comment]
@AbhayShiro Fixed this issue by the latest master branch, please try it.
