### ISSUE TITLE
Help wanted for prop-types Type check

### ISSUE THREAD

**Issue by ghost** [wellyshen/react-cool-starter#115]
If I don't wanna use the type and import it from above, would this be a good way to do it in the classic ES6 style? 
But I keep getting the error `Unexpected Token for the part where the prop-types object ends`

```
Home.propTypes = {
  fetchData: () => void
};

const connector = connect(
  ({ home }) => ({ home }),
  dispatch => ({
    fetchData: () => dispatch(action.fetchData()),
    actionVar: () => dispatch(action.actionVar()),
  }),
);
```

Just trying to work my way through the old and the new versions of this starter

Also why even change from `prop-types` to `flow`?

Thanks!

**Comment by ghost** [comment]
Well I figured it out with prop-types

**Comment by wellyshen** [comment]
Flow is a powerful type checking utility, it help me prevent from many troubles. It's easy to learn and understand. Take your time to check it.
