### ISSUE TITLE
[webpack-isomorphic-tools] [error]

### ISSUE THREAD

**Issue by sivaraj-v** [wellyshen/react-cool-starter#116]
`sivaraj.v@INB-W0452 MINGW64 /c/wamp64/www/react-cool-starter (master)
$ npm run start

> react-cool-starter@2.5.0 start C:\wamp64\www\react-cool-starter
> better-npm-run start

running better-npm-run in C:\wamp64\www\react-cool-starter
Executing script: start

to be executed: "nodemon ./index.js"
[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: index.js C:\wamp64\www\react-cool-starter\tools\webpack/**/* src/server.js src/utils/Html.js
[nodemon] starting `node ./index.js`
[webpack-isomorphic-tools] [error] asset not found: ./src/components/UserList/styles.scss
[webpack-isomorphic-tools] [error] asset not found: ./src/containers/Home/styles.scss
[webpack-isomorphic-tools] [error] asset not found: ./src/components/UserCard/styles.scss
[webpack-isomorphic-tools] [error] asset not found: ./src/containers/UserInfo/styles.scss
[webpack-isomorphic-tools] [error] asset not found: ./src/containers/NotFound/styles.scss
[webpack-isomorphic-tools] [error] asset not found: ./src/theme/normalize.css
[webpack-isomorphic-tools] [error] asset not found: ./src/containers/App/styles.scss
==> 🌎  Listening at http://localhost:3000
webpack building...
==> 😭  Rendering routes error: TypeError: Cannot read property 'App' of undefined
GET / 404 799.804 ms - 12
./src/client.js
Module build failed: Module failed because of a eslint error.

C:\wamp64\www\react-cool-starter\src\client.js
   3:1   error  Unexpected space or tab after '/*' in comment  spaced-comment
   4:19  error  Strings must use singlequote                   quotes
   5:1   error  Unexpected space or tab after '//' in comment  spaced-comment
   6:49  error  Strings must use singlequote                   quotes
   7:30  error  Strings must use singlequote                   quotes
   8:26  error  Strings must use singlequote                   quotes
   9:27  error  Strings must use singlequote                   quotes
  10:33  error  Strings must use singlequote                   quotes
  11:28  error  Strings must use singlequote                   quotes
  12:1   error  Unexpected space or tab after '//' in comment  spaced-comment
  16:43  error  Strings must use singlequote                   quotes
  19:23  error  Strings must use singlequote                   quotes
  29:14  error  Missing trailing comma                         comma-dangle
  33:1   error  Unexpected space or tab after '//' in comment  spaced-comment
  39:30  error  Strings must use singlequote                   quotes
  45:21  error  Strings must use singlequote                   quotes
  47:7   error  Unexpected space or tab after '//' in comment  spaced-comment

✖ 17 problems (17 errors, 0 warnings)
  17 errors, 0 warnings potentially fixable with the `--fix` option.

 @ multi babel-polyfill react-hot-loader/patch webpack-hot-middleware/client?reload=true ./src/client.js
webpack built 6d05ae8bb9e351c86079 in 3164ms

ERROR in ./src/client.js
Module build failed: Module failed because of a eslint error.

C:\wamp64\www\react-cool-starter\src\client.js
   3:1   error  Unexpected space or tab after '/*' in comment  spaced-comment
   4:19  error  Strings must use singlequote                   quotes
   5:1   error  Unexpected space or tab after '//' in comment  spaced-comment
   6:49  error  Strings must use singlequote                   quotes
   7:30  error  Strings must use singlequote                   quotes
   8:26  error  Strings must use singlequote                   quotes
   9:27  error  Strings must use singlequote                   quotes
  10:33  error  Strings must use singlequote                   quotes
  11:28  error  Strings must use singlequote                   quotes
  12:1   error  Unexpected space or tab after '//' in comment  spaced-comment
  16:43  error  Strings must use singlequote                   quotes
  19:23  error  Strings must use singlequote                   quotes
  29:14  error  Missing trailing comma                         comma-dangle
  33:1   error  Unexpected space or tab after '//' in comment  spaced-comment
  39:30  error  Strings must use singlequote                   quotes
  45:21  error  Strings must use singlequote                   quotes
  47:7   error  Unexpected space or tab after '//' in comment  spaced-comment

✖ 17 problems (17 errors, 0 warnings)
  17 errors, 0 warnings potentially fixable with the `--fix` option.

 @ multi babel-polyfill react-hot-loader/patch webpack-hot-middleware/client?reload=true ./src/client.js

  16:26  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style`

![issue](https://user-images.githubusercontent.com/6199252/31492552-26cb72a8-af69-11e7-8f2c-f8ec2e682ca2.PNG)

Can you please tell me how to run starter kit without this error..
now localhost showing `Not Found :(` 

I hope you understand the issue.
-Thanks in advance

**Comment by wellyshen** [comment]
@zural Please run `yarn build` before start when first running this starter.

**Comment by wellyshen** [comment]
@zural,

Please run `yarn build` when you use this starter at first time. Then turn the `const eslint = false;` from `./tools/webpack/config.babel.js`.

**Comment by sivaraj-v** [comment]
Okay thanks man
