### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by alex-brain** [wellyshen/react-cool-starter#117]
When I try to run 'yarn start:prod', I get this error:
Cannot assign to read only property 'exports' of object '#<Object>'

**Comment by wellyshen** [comment]
@alex-brain 
Did you run this starter directly without any customizing? Can you give me more detail?

**Comment by alex-brain** [comment]
Now all is OK. I resolved this problem. I used "module.exports" with import. But now I rewritten "export default" instead "module.exports"
