### ISSUE TITLE
Global Variables for Api/Image Server hits

### ISSUE THREAD

**Issue by deepank411** [wellyshen/react-cool-starter#119]
Hi,

Can you please tell me how can I create/use variables across the app to manage hits to our Api and Image server based on current environment. I need to hit separate image and api servers during dev and on prod.

I can see some variables declared in webpack.client.js and package.json but am unable to use them in the components and containers.

**Comment by wellyshen** [comment]
@deepank411 

Just use `process.env.NODE_ENV` for checking the env. Addition, you can define your own env variable by `./package.json` and `./tools/webpack/config.babel.js`.

**Comment by deepank411** [comment]
@wellyshen 

Yes I've already seen that, but I was looking for a mechanism to integrate a .env file where I could keep those constants that shouldn't pushed to the remote github repo.
