### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ghost** [wellyshen/react-cool-starter#12]
I am trying to get a better grip on the package and tried to build it to see how the resulting code was.
The docs told me that after a 'npm build' the result should be in the public/dist folder. This folder contains several files but what I am missing is for instance a simple index.html (or htm/php) file. So how to I put it on the server?

Next I cleaned the dist folder and tried to build it again with npm install.
Now I ran into more serious problems, below is the content of npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start:production' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 verbose run-script [ 'prestart:production',
4 verbose run-script   'start:production',
4 verbose run-script   'poststart:production' ]
5 info lifecycle react-cool-starter@1.3.6~prestart:production: react-cool-starter@1.3.6
6 silly lifecycle react-cool-starter@1.3.6~prestart:production: no script for prestart:production, continuing
7 info lifecycle react-cool-starter@1.3.6~start:production: react-cool-starter@1.3.6
8 verbose lifecycle react-cool-starter@1.3.6~start:production: unsafe-perm in lifecycle true
9 verbose lifecycle react-cool-starter@1.3.6~start:production: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/aevl/react/react-cool-starter/node_modules/.bin:/usr/local/bin:/home/aevl/bin:/home/aevl/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle react-cool-starter@1.3.6~start:production: CWD: /home/aevl/react/react-cool-starter
11 silly lifecycle react-cool-starter@1.3.6~start:production: Args: [ '-c', 'npm run build && npm run start:prod' ]
12 silly lifecycle react-cool-starter@1.3.6~start:production: Returned: code: 1  signal: null
13 info lifecycle react-cool-starter@1.3.6~start:production: Failed to exec start:production script
14 verbose stack Error: react-cool-starter@1.3.6 start:production: `npm run build && npm run start:prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid react-cool-starter@1.3.6
16 verbose cwd /home/aevl/react/react-cool-starter
17 error Linux 4.4.0-43-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start:production"
19 error node v6.2.1
20 error npm  v3.9.3
21 error code ELIFECYCLE
22 error react-cool-starter@1.3.6 start:production: `npm run build && npm run start:prod`
22 error Exit status 1
23 error Failed at the react-cool-starter@1.3.6 start:production script 'npm run build && npm run start:prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-cool-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build && npm run start:prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-cool-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-cool-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by kleinspire** [comment]
**npm install** you only do once to install the dependencies of the project. You can see the dependencies in package.json. This file also contains all the info you need about the various commands.

**npm run build** command cleans and builds a new development version of the project into your public/dist folder. 

**npm run start** command starts the development server with the development version you just built.

**npm run:production** command cleans and builds a new production version of the project into your public/dist folder and starts the production server with the production version you just built.

If you want to deploy your project to a production server you need to copy the whole built project to your production node server, not just the dist folder.

**Comment by wellyshen** [comment]
Hi @vanarieleyen 

As @jazblueful mentioned, `npm install` is for installing the dependencies which the project needed, so you just need to do it once. This is an universal rendering starter, so you need to put the project on your host which supports node.js. 

By the way, the `index.html` is generated through the run time of express server. You can configure it through the `./src/helper/renderHTMLPage.js` file.

Moreover, you don't have to clean the dist file by yourself, whenever you run the `npm run build` or `npm run start:production` the npm scripts will clean the dist folder for you :)
