### ISSUE TITLE
How can I disable SSR?

### ISSUE THREAD

**Issue by empz** [wellyshen/react-cool-starter#120]
Could you point me to the steps required to remove SSR?

Also, would it be too hard to switch from Redux to MobX?

Thanks!

**Comment by iamacup** [comment]
Hi - there is a variable in the index.js file in the root directory (not in src) called `__DISABLE_SSR__`, if you set this to true it will stop the SSR.

Not sure about MobX but i am wondering if a different boilerplate would be a better place to start instead of unpicking Redux.

**Comment by wellyshen** [comment]
@emzero Just do as @iamacup mentioned. I'm not familiar with MobX. So I don't have any idea for it. BTW, if you need client-side rendering only. You can give [create-react-app](https://github.com/facebookincubator/create-react-app) a try.

**Comment by ghost** [comment]
Hi! Very good job with this boilerplate. I've learned a lot from checking the code.

Just need to remove SSR, and I can't find  __DISABLE_SSR__ in source code.
Currently, is there any way we can easily disable SSR?

Cheers

**Comment by wellyshen** [comment]
@dr-webninja, This starter is designed for SSR. In other words, there's no easy way to disable SSR. If you want to disable SSR. I think you need to remove all the **code split components** and disable all the `get('*' (req, res) => { ...  })` from `.src/server.js` maybe more I am not test it yet.
