### ISSUE TITLE
Not working for me when you change css

### ISSUE THREAD

**Issue by gkarwchan** [wellyshen/react-cool-starter#121]
Hi
I love what you have and most probably I am going to help with it, when I understand it more.

But first, it is not working for me. 
Whenever I change any css coloring, it is not showing even I do F5 refresh.
And it is blinking twice, which make me wonder if both server side rendering and client rendering are running both.

**Comment by wellyshen** [comment]
@gkarwchan 

For the color issue. Can you provide me more information?
For the **blinking twice**, you have to register your new styles [here](https://github.com/wellyshen/react-cool-starter/blob/master/src/utils/Html.js#L44) for solving this issue.

**Comment by gkarwchan** [comment]
Thanks @wellyshen 
I understand what is going on now. So we register our style to be rendered.
It took me a while to understand what is going on.

You can close this issue if you want.
I really like the simplicity of what you have. And I really like to participate, specially for HMR and server side, but as I am reading and understanding, seems the universal webpack is the way to go rather than webpack-isomorphic-tools

Anyway, I am new to these problems (styles, and assets on isomorphic application), so it would take a while before I change your stuff to use universal-webpack

**Comment by wellyshen** [comment]
@gkarwchan Sure, I'm willing to reply your questions :)
