### ISSUE TITLE
Enable global classNames

### ISSUE THREAD

**Issue by aagentah** [wellyshen/react-cool-starter#122]
Is there a way I could use/enable global class names, like so:

normalize.css
```
...

.test {
  background: red;
  color: red;
}
```

userCard.js
```
...
<li className="test">Name: {info.name}</li>
...
```

Thank you in advance.

**Comment by wellyshen** [comment]
@danjonesdev Just turn off the `CSSModules` from [here](https://github.com/wellyshen/react-cool-starter/blob/master/tools/webpack/config.babel.js#L17) then you can use **className** as normal.
