### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by fadiquader** [wellyshen/react-cool-starter#123]
async doesn't work when [nodemon] restarting due to changes...
  var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(req, res) {}

**Comment by wellyshen** [comment]
@fadiquader Can you give me more reproduce steps?

**Comment by wongteam** [comment]
@fadiquader 
I had some problem when integrated redux-saga. The cause - no babel polyfill/runtime transformation for generators (yield/ function*). For solve this error you should perform follow steps;
`yarn add --dev babel-plugin-transform-runtime`
and then add babel plugin to your **.babelrc** OR **package.json** like follow line
`"plugins": ["transform-runtime"],`
This project uses babel rules and presets defined in package.json. If you use .babelrc - add into.
This fixed config for me (package.json)
```json
"babel": {
    "presets": [
      "env",
      "react",
      "stage-0"
    ],
    "plugins": ["transform-runtime"],
    "env": {
      "production": {
        "plugins": [
          "transform-remove-console"
        ]
      }
    }
  },
```
line `"plugins": ["transform-runtime"]` has added

**Comment by wellyshen** [comment]
Close due to inactive.
