### ISSUE TITLE
How hard to add support for Redux Sagas?

### ISSUE THREAD

**Issue by jeghers** [wellyshen/react-cool-starter#124]
I have learned Sagas recently and like them very much.  I really like removing the complexity from Actions, and want to use them going forward.  So here are two questions:

1. How hard do you think for someone to add Redux Saga support to this Starter Kit?

2. Could you kindly consider adding Saga support with an example code?  You could certainly keep the use of Redux-Thunk, and perhaps show a separate example for both.  Then developers could enjoy more options and flexibility from the one Starter Kit.

Thanks,
/Mark

**Comment by wellyshen** [comment]
@jeghers 

Answers:
For 1). I just quickly overview the document of **redux-sagas**. I think it's not so hard to use it instead of **redux-thunk**.
For 2). It's a good suggestion, but recently I'm quite busying for my working and my own RN app (side-project). And there's a [feature](https://github.com/wellyshen/react-cool-starter#todo) I want to do for the next step. My time is really limited now. Can you do it for me?

**Comment by jeghers** [comment]
I might be able to help at some point, however if the other recent styling
bug forces me to move to a different starter kit, then I would probably not
be able to work on it at that point.

**Comment by wongteam** [comment]
@jeghers  I've integrated redux-saga at my project based on this started kit. It was easy. But i changed project structure and don't know how to proposal PR correctly. @jeghers i can show a sample w/o any rep changes.

**Comment by jeghers** [comment]
Sounds good. If you are in a difficult position to make a PR, maybe I can
adapt your changes into a PR and submit that if you wish.

**Comment by wongteam** [comment]
@jeghers i can make PR here but i don't think what it's good idea. Not all developers use redux-saga stuff and currently _redux-thunk_ is the best solution  for beginners here. Therefore i think  redux saga implementation should be pushed to another branch (like docker branch here).  @wellyshen what do u think about it?

**Comment by jeghers** [comment]
Well in my humble opinion, I think the Redux Saga actually makes the
backend API call code simpler, the complication of the thunk logic in the
action Creator code is also pretty difficult for a beginner I think.
Perhaps there is some way that both options can be available, and maybe
have an example of both? Then a developer can decide which one they like
and use that one.

**Comment by wongteam** [comment]
Someone else may think what redux-observable more simple) redux-saga is not silver bullet.
Look for my example with redeux-observable [epics](https://github.com/wongteam/0001-TT-geekstaff/blob/dev/src/app/redux/modules/employees/epics.ts).

**Comment by wongteam** [comment]
Now i propose @wellyshen create new branch redux-saga and then push there PR/our code with rdx-saga implementation. Someone else may create redux-observable or same async action management and push theirs code to different branch . At same time **master** branch will have _redux-thunk_ implementation that simple for beginners and simple SPA projects

**Comment by wellyshen** [comment]
@jeghers Sure, I already fixed the warning of **className** mis-match while start the developing environment.

**Comment by wellyshen** [comment]
@wongteam You know me man.

**Comment by wellyshen** [comment]
And I need someone to maintain the redux-sagas branch guys. Or the best way is you guys keep the branch on your github then I add the link on my README file.

**Comment by wongteam** [comment]
@wellyshen sounds good
