### ISSUE TITLE
Getting errror when starting in development mode with yarn start

### ISSUE THREAD

**Issue by dinesh-matta-mpf** [wellyshen/react-cool-starter#128]
Gettng following erro on yarn start

yarn start
yarn run v1.3.2
$ better-npm-run start
running better-npm-run in /home/dinesh/projects/react-cool-starter
Executing script: start

to be executed: nodemon ./index.js 
[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: index.js /home/dinesh/projects/react-cool-starter/tools/webpack/**/* src/server.js src/utils/Html.js
[nodemon] starting `node ./index.js`
[nodemon] Internal watch failed: watch /home/dinesh/projects/react-cool-starter/index.js ENOSPC
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Anybody has any idea about this error?

**Comment by wellyshen** [comment]
@dinesh-matta-mpf Try [it](https://github.com/remy/nodemon/issues/214#issuecomment-184180248)

**Comment by dinesh-matta-mpf** [comment]
Thanks @wellyshen, this solution worked for me
