### ISSUE TITLE
How can I wrap certain containers in certain routes?

### ISSUE THREAD

**Issue by alex-brain** [wellyshen/react-cool-starter#130]
For example, i want to wrap all my containers in div with class 'my-class' if route not equal '/UserInfo/:id'. What is the best way to do it?

**Comment by wellyshen** [comment]
@alex-brain Sorry I don't quite understand what you meant. Did you mean you want redirect user to a certain route which includes a certain container component?

**Comment by alex-brain** [comment]
@wellyshen I resolved this issue.  This solution is:
```javascript
export default () => {
  const showMainContainer = (route, props) => {
    if (route.path !== '/SignIn' && route.path !== '/SignUp') {
      return (
        <div className={styles.Authorized}>
          <Header />
          <route.component {...props} routes={route.routes || null} />
        </div>
      );
    }
    return <route.component {...props} routes={route.routes || null} />;
  };


  // Use it when sub routes are added to any route it'll work
  const routeWithSubRoutes = route => (
    <Route
      key={_.uniqueId()}
      exact={route.exact || false}
      path={route.path}
      render={props => (
        // Pass the sub-routes down to keep nesting
        showMainContainer(route, props)
      )}
    />
  );

  return (
    <div className={styles.Ap}>
      <Helmet {...config.app} />
      <Switch>
        {routes.map(route => routeWithSubRoutes(route))}
      </Switch>
    </div>
  );
};
```
But there is only one problem: my component Header, which I use in showMainContainer function can't get access to Redux store. It has empty object instead of the data. What I do wrong?
<route.component {...props} routes={route.routes || null} /> - works fine. It is OK, but
component Header can't use Redux data

**Comment by wellyshen** [comment]
@alex-brain How did you connect redux store with the **Header** component?

**Comment by alex-brain** [comment]
@wellyshen  I connect to Redux store in Header component in the same way as other:
```javascript
/* @flow */

import React, { PureComponent } from 'react';
import { connect } from 'react-redux';
import type { Connector } from 'react-redux';
import type { SignIn as SignInType, Reducer } from '../../types/index';


import styles from './styles.scss';

type Props = {
  signIn: SignInType,
};

export class Header extends PureComponent {
  props: Props;

  render() {
    const { signIn } = this.props;
    console.log('signIn', signIn);
    return (
      <div className={styles.Header}>
        This is header
      </div>
    );
  }
}

Header.defaultProps = {
  signIn: {},
};

const connector: Connector<{}, Props> = connect(
  ({ signIn }: Reducer) => ({ signIn }),
);

export default connector(Header);
```

**Comment by alex-brain** [comment]
@wellyshen  The most interesting thing: I made Header component in the individual route and added this code for the route:
```javascript
          <Header {...props} routes={route.routes || null} />
          <route.component {...props} routes={route.routes || null} />
```
And first string - Header can't get access to Redux, and in the second string - Header got access without problems

**Comment by wellyshen** [comment]
@alex-brain, Your code seems correct. I not sure if this problem caused by this starter or your stuff. Can you try to reproduce this issue base on the latest commit of this starter kit (create a simple nest route and component then access with a simple redux store). If this issue is caused from this starter kit. I'll fix it soon.

**Comment by alex-brain** [comment]
@wellyshen, How can I commit my reproduced issue to your starter kit? I have error: enable to access

**Comment by wellyshen** [comment]
@alex-brain You fork my repo. I clone your reproduced repo to see what's going on.

**Comment by wellyshen** [comment]
Close due to inactive.
