### ISSUE TITLE
babili deprecated

### ISSUE THREAD

**Issue by Tuizi** [wellyshen/react-cool-starter#133]
When installing the starter this deprecation warning appears:

```shell
npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
```

**Comment by wellyshen** [comment]
@Tuizi Use the [new](https://github.com/webpack-contrib/babel-minify-webpack-plugin) library to replace the old one.

**Comment by Tuizi** [comment]
You don't want to fix that in this starter?

**Comment by wellyshen** [comment]
@Tuizi This warning is caused from **babili-webpack-plugin** and now it's updated (and renamed) to **babel-minify-webpack-plugin**. So I updated to the new one and the warning should be solved.
