### ISSUE TITLE
React cool with Material UI Next

### ISSUE THREAD

**Issue by gediminastub** [wellyshen/react-cool-starter#134]
Hello :)

I'm new to react, and looking forward to implement something with this very cool starter!
But reached to the problem, that I can't use Material UI next, due to it's usage of newer js syntax.
On `yarn start:production` I get:

/Users/university/Documents/react-cool-starter-master/node_modules/material-ui/es/Card/CardActions.js:5
import React from 'react';
^^^^^^

SyntaxError: Unexpected token import

How could I change build process that this node_module would be babel'ified to work?

Thanks!

**Comment by jmsherry** [comment]
That's objecting to es6 module import! Have you built?? (`yarn build`)

**Comment by wellyshen** [comment]
@gediminastub I can use Material UI without problem. Did you use the latest commit?

**Comment by gediminastub** [comment]
Sorry, the problem was that I installed `Next` version which wasn't es6. Thank You again for all! :)

**Comment by ghost** [comment]
I'm having same issue with Material UI next. When I try to run production build and start, I get same:
import React from 'react';
^^^^^^

Also tried bable preset: node 6 to compile it to right ES version (put .babelrc in project and allowed babel to use it). However, then I get that <Html is unexpected token.
Thank You for Your time in advance :)

**Comment by wellyshen** [comment]
@akimirka Try to set up the babel config [here](https://github.com/wellyshen/react-cool-starter/blob/master/package.json#L106) rather than `.babelrc`.

**Comment by wellyshen** [comment]
Close due to inactive.
