### ISSUE TITLE
IE11 errors

### ISSUE THREAD

**Issue by forwardomg** [wellyshen/react-cool-starter#135]
Hello guys. I noticed that something is wrong with ie10-11 support.

![ie](https://user-images.githubusercontent.com/5165362/34109836-e16d67c0-e415-11e7-99ab-43968066cdc3.png)

**Comment by wellyshen** [comment]
@forwardomg It seems **babel runtime transform** not works (or enough) on IE10-11. I will take time to survey it.

**Comment by wellyshen** [comment]
Hey @forwardomg Could you please help to verify this issue with [v2.8.1](https://github.com/wellyshen/react-cool-starter/releases/tag/v2.8.1)?

**Comment by forwardomg** [comment]
@wellyshen Yeap :) Awesome, but now we have another issue (syntax) in node_modules/ansi-styles/index.js package.

![image](https://user-images.githubusercontent.com/5165362/34159903-f5a80e2c-e4db-11e7-9590-638ab6152c69.png)

**Comment by wellyshen** [comment]
@forwardomg The error seems occurs from 3rd library. Can you translate it to English for me?

**Comment by forwardomg** [comment]
@wellyshen Syntax error

**Comment by wellyshen** [comment]
@forwardomg Which version of IE are you using?

**Comment by wellyshen** [comment]
@forwardomg Can you please help to verify this issue again with [v2.8.2](https://github.com/wellyshen/react-cool-starter/releases/tag/v2.8.2)?

**Comment by forwardomg** [comment]
@wellyshen I'm using IE11 now. Still same error. You can check out the gif bellow.

![123](https://user-images.githubusercontent.com/5165362/34162913-5f63781a-e4e6-11e7-88b8-7f6a9dcc680a.gif)

**Comment by wellyshen** [comment]
@forwardomg Even adding **Babel Runtime Transform** still not work on IE11 right?

**Comment by forwardomg** [comment]
@wellyshen yeap, strange behaviour

**Comment by wellyshen** [comment]
@forwardomg OK, it seems using `babel-polyfill` is fine for non IE browsers. But for IE I will spend time to find other solution. Now is 11pm in my country (TW). I need to take a shower. Thank you for your help man.

**Comment by forwardomg** [comment]
@wellyshen thank to you for trying solve this issue)

**Comment by forwardomg** [comment]
@wellyshen Alright, I solved this problem by removing the chalk from the store and set babel-polyfill instead of babel-runtime-transform. The problem occurs because the [ansi-styles](https://github.com/chalk/) package is used on the client.

**Comment by wellyshen** [comment]
@forwardomg Thank you for finding the root cause. **Chalk** is used for coloring terminal string, I didn't notice it :P

**Comment by forwardomg** [comment]
@wellyshen Just noticed that now in the production version does not work at all in all browsers :(
`Uncaught ReferenceError: regeneratorRuntime is not defined`

**Comment by wellyshen** [comment]
@forwardomg have you `require(babel-polyfill)` in your entry file as I [did](https://github.com/wellyshen/react-cool-starter/blob/master/index.js#L5)?

**Comment by forwardomg** [comment]
@wellyshen Sure :) I'm testing not on my project, just downloading this repository and trying to start it.
1. Clone the project
2. Yarn
3. Yarn build
4. Yarn start:prod
5. Click on any users after page open
6. Error occurs 
> Uncaught ReferenceError: regeneratorRuntime is not defined

**Comment by wellyshen** [comment]
@forwardomg Can you tell me what node version, browser, developing OS that you are using?

**Comment by forwardomg** [comment]
@wellyshen 
- Node 8.9.3
- Chrome ver. 63.0.3239.84
- Windows 10

**Comment by wellyshen** [comment]
@forwardomg OK I reproduce your step and I get the error too. I'm dealing with it. Thanks.

**Comment by wellyshen** [comment]
@forwardomg Try the last commit. See if I solve this issue man ;)

**Comment by forwardomg** [comment]
@wellyshen nice, it works now. One more thing, the vendor bundle has const and other es6 things.
Two more errors in IE11 like:

- Need to initialize const
- webpackJsonp is not defined

The same steps that I reproduced.
But it depends on what browsers you support)

**Comment by wellyshen** [comment]
@forwardomg If you clear the cache of your IE browser and press "Control + F5" will the error of  `webpackJsonp is not defined` gone? And do you think I need to abandon IE11?

**Comment by forwardomg** [comment]
@wellyshen I did it, but the same problem. In my opinion, IE support is very important, all commercial projects need to support it, but the maintainer decides here. :)

**Comment by wellyshen** [comment]
@forwardomg Do these two errors occurs on IE11 only? Can you describe the errors for me more detail?

**Comment by forwardomg** [comment]
@wellyshen 11 and lower. You can emulate windows with a browserstack, it will be so much easier for you.
So, the first error is "webpackJsonp is not defined", another one error is related to es6 not compiling into es5 syntax.

**Comment by wellyshen** [comment]
@forwardomg Yea, I know it. I will try to use it if the latest commit not works for IE11. Can you help me to verify it again?

**Comment by forwardomg** [comment]
![image](https://user-images.githubusercontent.com/5165362/34320379-2c5d8312-e80a-11e7-908f-762432f72bb8.png)

**Comment by wellyshen** [comment]
@forwardomg OK it doesn't work. Thank you I will find other solution for it 👍

**Comment by wellyshen** [comment]
@forwardomg Did you turn on the **Compatibility Mode** of your IE11?

**Comment by forwardomg** [comment]
@wellyshen Compatibility Mode IE11 by default :) I use an original IE11 browser.
I'll try to solve this problem when I have time.

**Comment by forwardomg** [comment]
#137 Solved.

**Comment by wellyshen** [comment]
@forwardomg Thanks man. It really help 👍
