### ISSUE TITLE
Support request - question about including static props via routes.js

### ISSUE THREAD

**Issue by openbook** [wellyshen/react-cool-starter#139]
Apologies if this has been answered before if it has I've been unable to find it.  I'm also fairly new to SSR react, so this may be a simple question.  I'm trying to pass a static prop into a controller from the routing config, previously I've done this using the render function in the route info but im unsure how to do this with this starter.  Ideally, I need to do something like this in routes.js .... i.e.

```
export default [
  {
    path: '/videos/*/:nid',
    component: NodePage,
    // static property here
    props: {
      customProp: 'propValue',
    },
    loadData: (dispatch: Dispatch, params) => Promise.all([
      dispatch(fetchNodeIfNeeded()),
    ]),
  },
];
```

so I could then access it using props.customProp in the NodePage controller.

Thanks in advance, and, great starter project, thanks for putting it together.

**Comment by wellyshen** [comment]
@openbook,

I guess you can pass the props through:
```javascript
export default [
  {
    path: '/videos/*/:nid',
    component: () => <NodePage customProp={propValue} />,
    loadData: (dispatch: Dispatch, params) => Promise.all([
      dispatch(fetchNodeIfNeeded()),
    ]),
  },
];
```

**Comment by openbook** [comment]
Great, thanks for that.  When using this, I then needed to also include the router location info as a prop, so the following is working, thanks for your help.

```
export default [
  {
    path: '/videos/*/:nid',
    component: params => <NodePage customProp={propValue} location={params.location} />,
    loadData: (dispatch: Dispatch, params) => Promise.all([
      dispatch(fetchNodeIfNeeded()),
    ]),
  },
];
```
