### ISSUE TITLE
Benefits of testing with Jest

### ISSUE THREAD

**Issue by jabacchetta** [wellyshen/react-cool-starter#14]
What are your thoughts on moving testing to Jest? Dan Abramov — the author of Redux — has been working on the framework recently and they've pushed [a number of big updates](https://facebook.github.io/jest/blog/2016/10/03/jest-16.html) over the past few months (snapshot testing, performance improvements, integrated coverage reporting, upgraded CLI, etc).

**Comment by wellyshen** [comment]
@jabacchetta Wow, sounds great. I will take time to study it, thanks a lot :)

**Comment by TitanKing** [comment]
Jest does seem to slowly become preferred over Mocha, though, nothing wrong with Mocha, just a larger dependable stack.

**Comment by wellyshen** [comment]
@TitanKing I will evaluate about it, thanks.

**Comment by jabacchetta** [comment]
I might have time to help with this feature in the next few weeks if nobody else takes it on by then. I've been using snapshot testing for about a month now and it's awesome. Stack includes Jest, Enzyme, Redux Mock Store, Moxios, and identity-obj-proxy (for CSS Modules).

**Comment by wellyshen** [comment]
Hi @jabacchetta It will be great, currently the project is maintained by myself. So feel free to do it ;)

**Comment by wellyshen** [comment]
Hi Guys, Transfer to Jest framework, enjoy it :)
