### ISSUE TITLE
Fat lodash

### ISSUE THREAD

**Issue by forwardomg** [wellyshen/react-cool-starter#141]
### Expected Behavior
1. One lodash for all bundles.
2. Don't load all monolithic lodash.

### Actual Behavior
1. We have a lodash for each bundle.
2. We load all monolithic lodash with fp module.

![image](https://user-images.githubusercontent.com/5165362/34871796-f28d0ee6-f79f-11e7-81b6-41014aa7cea5.png)

**Comment by forwardomg** [comment]
- [x] #140 - 1. PR for remove lodash from vendor bundle.
- [x] - 2. I fount old issue here https://github.com/lodash/lodash/issues/3079

**Comment by wellyshen** [comment]
Solved by #140

**Comment by forwardomg** [comment]
@wellyshen Awesome :) What about the second problem related to load monolithic lodash.min library with lodash/fp module into bundle? It seems babel-lodash doesn't do its job. ;(

**Comment by wellyshen** [comment]
@forwardomg babel-plugin-lodash seems support it already (see [here](https://github.com/lodash/babel-plugin-lodash/issues/21))

**Comment by forwardomg** [comment]
@wellyshen it seems so, but it doesn't work and as a result, we get a lot of unused code.

**Comment by wellyshen** [comment]
@forwardomg 

Maybe you can try:
```javascript
import { assign } from 'lodash/fp';
```

**Comment by forwardomg** [comment]
@wellyshen I found the problem and fixed it #142 , hope you'll be merged it.

**Comment by wellyshen** [comment]
@forwardomg Should I include the webpack analyze plugin as you show above into this starter?

**Comment by forwardomg** [comment]
@wellyshen, In my opinion, the simpler the better :) I don't think that it is necessary, but I implemented in my project based on this starket kit task named "build:stats" which shows much more information about bundles.

**Comment by wellyshen** [comment]
@forwardomg 

Good idea 👍 
I'm doing this.

**Comment by forwardomg** [comment]
@wellyshen Nice :) and more importantly what would be great to implement is code splitting and lazy loading based on specific page, it's a must-have feature for optimization. 👍

**Comment by wellyshen** [comment]
@forwardomg Yea. I will do it.

**Comment by forwardomg** [comment]
@wellyshen Awesome, you can check one of my favorite package for doing this https://github.com/thejameskyle/react-loadable. It is easy enough to integrate into this starket kit.

**Comment by wellyshen** [comment]
@forwardomg 
Great library. I have checked it, but I also want to redux reduces are dynamic loaded which follow their related route's component. The library seems no proper way to support it :(

**Comment by forwardomg** [comment]
@wellyshen This makes sense if the reducers would be very large, but this can only happen if we fetch and fill data for the entire state, but this won't happen, coz we fetch only specific data for each page. I don't think that this is a bad idea if we load the entire state of the app without data. And I'm sorry for the flood on this topic. :)

**Comment by wellyshen** [comment]
@forwardomg It's OK. I will study the **react-loadable** and think how to injectReducer dynamically with it ;)
