### ISSUE TITLE
react-loadable integration?

### ISSUE THREAD

**Issue by ItsMrAkhil** [wellyshen/react-cool-starter#144]
Why can't we integrate react-loadable here? 
It's a great package which offers **component-level code splitting** not route level code splitting.

You can show a nice **loading text or a loading image** while downloading the chunk file. Let's say the internet is slow you can even set a timeout to show some text like "Taking longer time than usual", etc.

Please check here for all the features.
https://github.com/thejameskyle/react-loadable

**Comment by wellyshen** [comment]
@ItsMrAkhil Yes, we can. I might use **react-loadable** for the feature of dynamic routing.

**Comment by wellyshen** [comment]
@ItsMrAkhil **react-loadable** on server-side render seems have some problems and the open issue function was disabled by the author. I'll give [loadable-component](https://github.com/thejameskyle/react-loadable) a try for code-splitting with this starter ;)

**Comment by wellyshen** [comment]
@ItsMrAkhil Great news! [loadable-component](https://github.com/thejameskyle/react-loadable) has been success integrated with this starter. Now code-splitting is easy to be used. I'll push it later ;)

**Comment by wellyshen** [comment]
Code-splitting now available on this starter on [v2.2.0](https://github.com/wellyshen/react-cool-starter/releases/tag/v2.2.0).

**Comment by ItsMrAkhil** [comment]
@wellyshen Awesome dude. Thank you.

**Comment by ItsMrAkhil** [comment]
I'm just curious what was the issue with the react-loadable.

But react-loadable is also working fine with me. You can check here.
https://github.com/ItsMrAkhil/starter

**Comment by wellyshen** [comment]
@ItsMrAkhil 

I list the problem than I encountered when integrating with **react-loadable**.
* react-loadable `stats.json` includes the `main.js` but it already handled by **webpack-isomorphic-tools**.
* When you press `f5` to refresh the **UserInfo** page you will find there're error warnings on your browser's developer console panel. (I think the problem occurs from react-loadable).
* Too many configuration to setup the SSR of **react-loadable** however the SSR setup of **loadable-components** is much easier and painless.
