### ISSUE TITLE
Resolving based on src/ directory

### ISSUE THREAD

**Issue by rbhalla** [wellyshen/react-cool-starter#146]
Would be great to be able to to do `import Modal from 'components/Modal'` instead of `import Modal from '../../components/Modal'`. It can drastically declutter imports.

In the past I've used resolve.modules to do this, but I can't seem to get it working again. It's possible you might know of a quick way to do this.

If you don't think it's helpful, feel free to close :)

**Comment by wellyshen** [comment]
@rbhalla I think you can use webpack [`resolve.alias`](https://webpack.js.org/configuration/resolve/#resolve-alias) for deal with it.
