### ISSUE TITLE
Hanging Webpack build

### ISSUE THREAD

**Issue by ThugDebugger** [wellyshen/react-cool-starter#147]
After cloning and an `npm install,` after trying to start the app with` npm run start`, the terminal repeats and hangs on the output: ` [webpack-isomorphic-tools] (waiting for the first Webpack build to finish)`. Trying to navigate to the localhost does not deter this either. This has been hanging for around 20 mins.

**Comment by wellyshen** [comment]
@js1599 I have listed some common issues on the [troubleshoots](https://github.com/wellyshen/react-cool-starter#troubleshooting) section. It can help you solve this issue :)

**Comment by ThugDebugger** [comment]
92% chunk asset optimizationC:\Users\jsamuels\Desktop\JestDemo\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:276
        throw new Error(
        ^

Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.

**Comment by ThugDebugger** [comment]
I would recommend building your scripts over again so they can run and install via npm in their entireity, rather than having to rely on both npm and yarn.

**Comment by wellyshen** [comment]
@js1599 Can you run the starter successful based on the latest commit?

**Comment by ThugDebugger** [comment]
The issue comes from WebPack: https://github.com/webpack/webpack/issues/5931

Swapping line # 138 in config.babel.js from `  devtool: isDev ? 'cheap-module-source-map' : 'hidden-source-map',` to `devtool: 'none'` got me past this error. I can submit a PR to your doc to explain this error and the resolve, would you like that?

**Comment by wellyshen** [comment]
@js1599 I can't reproduce this issue. What other packages did you used?
