### ISSUE TITLE
Aborting CSS HMR due to new CSS selector

### ISSUE THREAD

**Issue by jsauca** [wellyshen/react-cool-starter#151]
###Bug Report
CSS HMR is aborted when css selectors are added or removed. Full-page reload required.
![screen shot 2018-02-14 at 11 18 19 am](https://user-images.githubusercontent.com/29192645/36189301-bb6c686a-11a5-11e8-9e6d-cd6cad817ec1.png)

### Expected Behavior
Expect page to take CSS changes in account, when adding or removing selectors.

### Actual Behavior
**The CSS HMR only works when editing css selectors.**
'Aborting CSS HMR due to changed css-modules locals'.
-> Full page reload required to see changes.

### Your Environment
- Developement

**Comment by wellyshen** [comment]
@jsauca Thank you for report this issue. This issue probably will be fixed in [webpack-contrib/style-loader#298](https://github.com/webpack-contrib/style-loader/pull/298). Please wait for the new release of style-loader.

**Comment by jsauca** [comment]
No probs. Thanks @wellyshen

**Comment by AleksandrZhukov** [comment]
Still get this error, but this comment helped me
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/384#issuecomment-277375004

**Comment by lydell** [comment]
webpack-contrib/style-loader#298 _introduced_ the `Aborting CSS HMR due to changed css-modules locals` "error" and it has already been released months ago. I know, because I wrote that patch :) Feel free to ask me if you have further questions (though I know nothing about this repo)

**Comment by AleksandrZhukov** [comment]
@lydell yeah, I saw your PR, but I still got that problem, and css-hot-loader helped)
