### ISSUE TITLE
Data is not rendered on server (dev mode)

### ISSUE THREAD

**Issue by AleksandrZhukov** [wellyshen/react-cool-starter#153]
### Expected Behavior
Data should be rendered 

### Actual Behavior
Only `Loading...` is rendered

![image](https://user-images.githubusercontent.com/8876116/36309360-f442f3ec-132c-11e8-8958-1b3629206659.png)

### Your Environment
* Clint OS: mac
* Browser and its version: Chrome 64
* Version of node: v9.5.0

**Comment by wellyshen** [comment]
@AleksandrZhukov, I have tested the latest [commit](https://github.com/wellyshen/react-cool-starter.git) on dev, it works as expect. Any error message on your client or server console? Or how about your network connection status?

**Comment by AleksandrZhukov** [comment]
@wellyshen Try to disable browser js or check html that you get from server

**Comment by wellyshen** [comment]
@AleksandrZhukov Thank you for extending the information. It's because of the [getloadablestate](https://github.com/smooth-code/loadable-components#getloadablestate) of  [loadable-components](https://github.com/smooth-code/loadable-components) doesn't get the state on development. I'll investigate it.

**Comment by wellyshen** [comment]
Related to https://github.com/smooth-code/loadable-components/issues/48

**Comment by aslapkov** [comment]
I have noticed, if you go back to the version **react-hot-loader@4.0.0-beta.21** this will work.

**Comment by wellyshen** [comment]
@aslapkov Seems the problem caused by the integrating between **react-hot-loader** and **loadable-components**. Thank you for this helpful information 👍

**Comment by aslapkov** [comment]
@wellyshen In the updated version **react-hot-loader@4.0.0-beta.23** the problem is solved.

**Comment by wellyshen** [comment]
Hi Guys **react-hot-loader@4.0.0-rc.0** solved this issue. Please refer to my last commit.
