### ISSUE TITLE
Deprecated  webpack-isomorphic-tools

### ISSUE THREAD

**Issue by AleksandrZhukov** [wellyshen/react-cool-starter#154]
I've checked webpack-isomorphic-tools repo and found this

> is now considered deprecated and new projects shouldn't use it.

And they suggest to use https://github.com/catamphetamine/universal-webpack

> For new projects use either universal-webpack

@wellyshen What are you thinking about migration, any known problems?

**Comment by wellyshen** [comment]
@AleksandrZhukov Yes, I know about it. But seems the author still maintaining the repo. I also consider to use other library to handle the universal webpack bundling. Is there a good library for it?

**Comment by AleksandrZhukov** [comment]
I think we can try to use universal-webpack and check how it works 
https://github.com/catamphetamine/universal-webpack#universal-webpack-vs-webpack-isomorphic-tools

**Comment by wellyshen** [comment]
Any great library for handling assets on SSR? Please recommend.

**Comment by AleksandrZhukov** [comment]
Sorry, I'm not so familiar with this, need to investigate

**Comment by wellyshen** [comment]
@AleksandrZhukov The latest commit has removed the **webpack-isomorphic-tools**.
