### ISSUE TITLE
[Discussion] Feature branch: simple-action

### ISSUE THREAD

**Issue by wellyshen** [wellyshen/react-cool-starter#160]
Here's the discussion place for the `simple-action` feature branch.

**Comment by wellyshen** [comment]
@alirezavalizade Please note, `componentWillMount` is going to be deprecated in react@16.3.0. See this [post](https://medium.com/@baphemot/whats-new-in-react-16-3-d2c9b7b6193b) for more detail.

**Comment by alirezavalizade** [comment]
@wellyshen Thank you, I'll check it.
