### ISSUE TITLE
Bug on windows 10 in development

### ISSUE THREAD

**Issue by Kimel1** [wellyshen/react-cool-starter#164]
I have installed latest react-cool-starter pure and 
```
C:\react-app>node -v
v8.9.4
C:\react-app>yarn -v
yarn install v0.24.6
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.75s.
C:\react-app>npm -v
5.7.1
```
w/o any errors.
But when I start dev server and try to change \src\components\UserCard.js:13 
`<li>Name: {info.name}</li>`
to 
`<li>Name1: {info.name}</li>
`

In browser console 
https://imgur.com/a/1xnIC
In cmd 
https://imgur.com/a/pSDLm

Nodemon cause recompile . But if I modify package.json to 
```
  "betterScripts": {
    "start": {
      "command": "node ./index.js",
      "env": {
        "NODE_PATH": "./src",
        "NODE_ENV": "development",
        "PORT": 3000
      }
    },
```

things  goes in more ridiculous way 
https://imgur.com/a/hc8Se
that message appears in browser console for 50ms and then page refreshes.

**Comment by wellyshen** [comment]
Duplicated issue #165
