### ISSUE TITLE
Hot Module Reloading not working on components

### ISSUE THREAD

**Issue by elledienne** [wellyshen/react-cool-starter#165]
I've been playing around with this repo and I noticed that hot module reloading is working only for containers but it doesn't work for components mounted within them.

The workaround/solution I found is wrapping also every component inside the `hot(module)` function exported by `react-hot-loader`, like this:

``` js
// src/components/index.js
import { hot } from 'react-hot-loader';

import _UserList from './UserList';
import _UserCard from './UserCard';
import _Error from './Error';
import _Loading from './Loading';

const UserList = hot(module)(_UserList);
const UserCard = hot(module)(_UserCard);
const Error = hot(module)(_Error);
const Loading = hot(module)(_Loading);

export {
  UserList,
  UserCard,
  Error,
  Loading
};
```
Also it was necessary to use run the code with `node` instead of `nodemon` because `nodemon` was reloading the server instead of hot reloading the components (even though I guess could be enough to exclude the file from the watched files).

### Expected Behavior
- When components are updated, they should be hot reloaded
- Page should not hard reloaded
- Server should not restart

### Actual Behavior
- Nodemon restarts the server
- Client reloads

### Your Environment
* macOS 10.12.6
* Chrome 64
* node 8.8.1 (tried also with 8.7.0)

**Comment by Kimel1** [comment]
same problem on win10 https://github.com/wellyshen/react-cool-starter/issues/164

**Comment by wellyshen** [comment]
It seems a bug of react-hot-loader. I have open an issue for it. Please note on https://github.com/gaearon/react-hot-loader/issues/887

**Comment by BJvdA** [comment]
It seems that the nodemonConfig is wrong, the watch rule `"index.js"` should be `"./index.js"` to make sure that the server is only reloaded on changes to the index.js in the root folder. Now it reloads when changing any file named index.js, also in container folder.

**Comment by Kimel1** [comment]
@BJvdA 
 But if I modify package.json to

``` javascript
  "betterScripts": {
    "start": {
      "command": "node ./index.js",
      "env": {
        "NODE_PATH": "./src",
        "NODE_ENV": "development",
        "PORT": 3000
      }
    },
```
we get https://imgur.com/a/hc8Se
this message appears in browser console for 50ms and then page refreshes.

**Comment by wellyshen** [comment]
@BJvdA The problem isn't the `nodemonConfig`. I think it might be a bug of **react-hot-loader**. There's a related bug before already => https://github.com/gaearon/react-hot-loader/issues/600

**Comment by theKashey** [comment]
React-hot-loader shall be more clear on this, but 
__only one "hot"__ is permitted per module, and that "hot" shall be a default export, and it should be wrapped around a Component.
The second point - it is better to have a single `hot` around top-most Comments(application), __and__(!) that component should be used to `react-dom/render` in __another__ file.

PS: In case of any problems please follow the "v3" way – just handle webpack HMR by yourself.

**Comment by wellyshen** [comment]
Fixing by the latest commit.

**Comment by Kimel1** [comment]
@wellyshen not completely fixed.
After updating to newly version get this when editing component.
https://imgur.com/a/MqDhL

To reproduce go to UserList an edit it, then in browser refresh page.

**Comment by wellyshen** [comment]
@Kimel1 Sorry my bad. Please try the latest commit again.
