### ISSUE TITLE
prettier error

### ISSUE THREAD

**Issue by zolcman** [wellyshen/react-cool-starter#166]
I have error when try run yarn build && yarn start

![errror](https://user-images.githubusercontent.com/22850643/37150859-0fd92a5e-22dc-11e8-914a-fb28c79c31ec.png)
I updated my store like I need, but it gives me error
how to disable this errors? 
in config not helps

```
const eslint = false;

const stylelint = false;
```

**Comment by wellyshen** [comment]
@zolcman This starter integrated with [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) for javascript code guide. You can quickly fix the format errors by `yarn lint:js`. Or define your preferable rules [here](https://github.com/wellyshen/react-cool-starter/blob/master/package.json#L154)

**Comment by zolcman** [comment]
@wellyshen thank you!
