### ISSUE TITLE
Script load failure in development (chrome)

### ISSUE THREAD

**Issue by aagentah** [wellyshen/react-cool-starter#174]
Cloned the repo, ran yarn.
Build + production (yarn start:production) works fine, but in dev (yarn start) returns this in browser console:

`Refused to apply style from 'http://localhost:3000/assets/main.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

`Refused to execute script from 'http://localhost:3000/assets/main.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

`Refused to apply style from 'http://localhost:3000/assets/main.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

Any idea what this could be? Thank you in advance.

**Comment by wellyshen** [comment]
@danjonesdev I can't reproduce it. Did you try the latest commit?

Here's my result :
<img width="1280" alt="2018-04-12 11 35 12" src="https://user-images.githubusercontent.com/21308003/38687847-356aaace-3eaa-11e8-8c0a-ec14348460fb.png">

**Comment by aagentah** [comment]
Hmm that's strange, yes it was the latest version of repo, here are my settings:

```
Chrome 65.0
Node v8.11.1
Windows 10
```

I will try different browser - thanks!

**Comment by wellyshen** [comment]
@danjonesdev OK let me know about that 👍

**Comment by aagentah** [comment]
Chrome re-install fixed issue - Thanks.
