### ISSUE TITLE
Cannot load images with more than 10Kb

### ISSUE THREAD

**Issue by ghost** [wellyshen/react-cool-starter#175]
Hi! 
I'm investigating an issue related to image loading. I got an error related to client and server not rendering exactly the same src property for images greater than 10kb.

**Steps to reproduce:**
-  change file:/src/app/index.js to load a new image (> 10kb)
` <img src={require('./assets/new-image.png')} alt="image" role="presentation" /> `
- Run: `yarn run start:production`

**Result:** Image is not loaded.

I was trying to fix this, and had to remove the image-webpack-loader (in config.babel.js)
` { loader: 'image-webpack', options: { bypassOnDebug: true } }`

and changed images asset-require-hook (in hooks.js) to

`   require('asset-require-hook') ( {
        extensions: ['gif', 'jpg', 'jpeg', 'png', 'webp'],
        publicPath: '/assets/',
        limit: 10240
  }); 
`

so it will convert to inline base64 any image below or equal to 10k (**as in config.babel.js**).

Now everything seems to work properly. The problem is that I've lost image optimisation stuff.
Do you know if there is any server hook that can output the same as image-webpack-loader?
Thanks.

**Comment by wellyshen** [comment]
@dr-webninja Thank you for reporting this issue. It has been fixed by [v2.4.2](https://github.com/wellyshen/react-cool-starter/releases/tag/v2.4.2).
