### ISSUE TITLE
app is crashing on91% additional asset processing

### ISSUE THREAD

**Issue by alirezavalizade** [wellyshen/react-cool-starter#176]
<img width="1440" alt="screen shot 2018-04-24 at 11 31 47 am" src="https://user-images.githubusercontent.com/14992757/39171141-25ca09c2-47b3-11e8-8481-eb1a8088ccd9.png">
@wellyshen Do you have any idea about this?

**Comment by alirezavalizade** [comment]
the problem is `new MinifyPlugin({}, { test: /\.jsx?$/, comments: false })`, But i don't know how to fix it @wellyshen

**Comment by wellyshen** [comment]
@alirezavalizade I already upgraded to webpack v4 and **MinifyPlugin** has been removed from this starter. I recommend you upgrade it.
