### ISSUE TITLE
Error: Cannot find module '../public/webpack-assets.json'

### ISSUE THREAD

**Issue by sebringj** [wellyshen/react-cool-starter#177]
Upon building a fresh clone `yarn && yarn start` you'll run into this issue.

Server.js line 25 is expecting this file to be defined in the public folder. I'm on Node LTS 8 on a mac with Mac high sierra v 10.13

Placing "public/webpack-assets.json" with
```{}```
works.

**Comment by wellyshen** [comment]
@sebringj  Please run `yarn build` to generate the **public/webpack-assets.json** file at first time. For more information you can see the [troubleshooting](https://github.com/wellyshen/react-cool-starter#troubleshooting) section.

**Comment by denny64** [comment]
@wellyshen I've tried running `heroku run yarn build` but it still doesn't work. Any ideas?

**Comment by denny64** [comment]
Nvm, worked it out. Just needed to remove public/webpack-assets.json in gitignore in first build
