### ISSUE TITLE
Redux Form Like Method

### ISSUE THREAD

**Issue by dayrlism10** [wellyshen/react-cool-starter#180]
Hi Welly,
Just seeking for advice.

i just started redux not long, fetching data from API in redux i could still manage to understand,

however, i was wondering if posting up a form to an API, 
should i use something like a redux-form since it already have redux fetching data with it, 
or i should just create a normal api library to post up with axious without redux or there is a way that you could suggest perhaps? or could you write a sample post form if this wont take long. 👯‍♂️

**Comment by wellyshen** [comment]
@dayrl94 For posting a form's data. If the data won't influences other components, I'll use **axios** to handle it directly from the component of the form.

**Comment by dayrl10** [comment]
thanks for the advice. ;)
