### ISSUE TITLE
Uncaught ReferenceError: babelHelpers is not defined

### ISSUE THREAD

**Issue by ilkertuna** [wellyshen/react-cool-starter#184]
When I added 
"'@babel/plugin-external-helpers',"
into config.babel.js (your commit 'Remove .nvmrc & Use babel external helper plugin & Upgrade dependencies' commit 94d08569fe285c3316bd755d082be238883bd0a7 )
I mean : 
![screenshot from 2018-07-16 12-24-51](https://user-images.githubusercontent.com/7367514/42751404-5563031a-88f3-11e8-8d19-294c4165b35e.png)
I also added "@babel/plugin-external-helpers": "^7.0.0-beta.53",
it's give me this error.

![screenshot from 2018-07-16 12-13-49](https://user-images.githubusercontent.com/7367514/42751024-0985cdd4-88f2-11e8-95df-8c440f36da9d.png)

However, I delete "'@babel/plugin-external-helpers'," in config.babel.js there is no error.

### Environment
* Ubuntu 16.04.4 LTS
* Chrome 67 (67.0.3396.99-1) on Linux
* v8.11.3 node

**Comment by wellyshen** [comment]
@ilkertuna Thank your for bug report. It has been fixed in [v2.5.2](https://github.com/wellyshen/react-cool-starter/releases/tag/v2.5.2).
