### ISSUE TITLE
Imported css is working only in development mode, but not working in production mode

### ISSUE THREAD

**Issue by ilkertuna** [wellyshen/react-cool-starter#185]
### Expected Behavior
I included css in app.js. My related component which is affected by css is called under Home. I want my component to work the same in both production and development mode.

### Actual Behavior
However, it's working only in development mode. 
In development mode, css is applied and everything is looking normal. However, in production mode css is not loading. I do not know how to explain or show it to you but, it is not loading or it is not being applied in production mode.

### Another Question.
What is the best way to import Css? Can you guide me? Also, what is the difference between import in renderHtml.js file or in app.js file?

### Your Environment
* Ubuntu 16.04.4 LTS
* Chrome 67 (67.0.3396.99-1) on Linux
* v8.11.3 node

**Comment by wellyshen** [comment]
@ilkertuna Can you give me a simple reproduced branch based on the [latest version](https://github.com/wellyshen/react-cool-starter/releases/tag/v2.5.3).

**Comment by ilkertuna** [comment]
I can't provide you the code because of "ISSUE  #186 Can't start && ReferenceError: window is not defined". Your latest version doesn't run currently.

I think that I could not properly import css's.
In previous closed issues, you said that css's should be imported in app.js and there is no difference in between css being located in node_modules and src/themes. Am I correct?

Also,
1 - ) What is the difference between import in renderHtml.js file and in app.js file?
2 - ) Can imported css in app.js affect the all project?
3 - ) What is the best way to import Css? Can you guide me?

For third question, is the following way correct ?:
   Css is located in src/theme or in public.
   Also CSSModules must be false in config.babel.js.
   Then, css is imported in app.js.

**Comment by ilkertuna** [comment]
I am able to answer some of my questions after some trials of my own
1 - )  Css which is inluceded in renderHtml.js has no effect.
2 - ) Yes. Css which is inluceded in app.js affects the all project.

Still waiting for an answer to the third question.

**Comment by wellyshen** [comment]
@ilkertuna OK I will spend time to see ur questions.

**Comment by wellyshen** [comment]
@ilkertuna 
Yes, if you want to use css without css modules you need to [set it](https://github.com/wellyshen/react-cool-starter/blob/master/tools/webpack/config.babel.js#L17).

You can put global styles or common variable in the `theme` folder and import them in `app.js` so they will influence every component. 

For component style, you can import it to the component which it belongs as I did.

Do I answer your question?

**Comment by ilkertuna** [comment]
Yes, thank you for your interest.
