### ISSUE TITLE
Can't start && ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ilkertuna** [wellyshen/react-cool-starter#186]
### Expected Behavior
yarn build
yarn dev
then, the app should be running 

### Actual Behavior
yarn build
yarn dev
then, gives this error

![screenshot from 2018-07-16 19-59-22](https://user-images.githubusercontent.com/7367514/42772509-59dfa7d2-8933-11e8-825c-1aa5ec307ff5.png)

### Your Environment
* ubuntu 18.04
* Chrome 67 on Linux
* node v8.11.2

**Comment by wellyshen** [comment]
@ilkertuna I fixed this issue in the last commit.
