### ISSUE TITLE
Removing babels stage presets

### ISSUE THREAD

**Issue by denbezrukov** [wellyshen/react-cool-starter#187]
Hi,
I had a problem with babel migration.
What do you think about this? 
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets

**Comment by wellyshen** [comment]
@Dominionys Thank you for telling me this big news. You can check this [release](https://github.com/wellyshen/react-cool-starter/releases/tag/v2.5.4) to see what I have done for dealing with this issue. The start-kit only need `@babel/plugin-proposal-class-properties` plugin but you can add your own plugins as I did.
