### ISSUE TITLE
WildCard will not fire fetchUserIfNeeded again if it run the same route.

### ISSUE THREAD

**Issue by dayrlism10** [wellyshen/react-cool-starter#188]
for example if you re in
http://localhost:1123/tabs/management/info/4

and you go to this wilecard route via a react router link

http://localhost:1123/tabs/management/info/5
or
http://localhost:1123/tabs/management/info/6

it will render the parent and the child in the first time, but if you re going to another route it will not render the child until you refresh the page only then it will render content for both parent and child.

any idea how to solve this, i found that because when i click to the link it will not fire componentDidMount but refresh does, thats why it will fire the redux fetchUserIfNeeded if it refresh.

**Comment by dayrlism10** [comment]
i found a way to do it not sure if its right but at least it solve, i place

componentWillReceiveProps(props) {
    const { manageuser, match, fetchManageUserIfNeeded } = props;
    if (props.manageuser[match.params.id]===undefined){
      fetchManageUserIfNeeded(match.params.id);
    } 
  }

this code to let it re-render if found not matching from param. lol

**Comment by wellyshen** [comment]
You can use this [new API](https://hackernoon.com/replacing-componentwillreceiveprops-with-getderivedstatefromprops-c3956f7ce607) to achieve it.
