### ISSUE TITLE
React i18next for multi language support

### ISSUE THREAD

**Issue by maiconcarraro** [wellyshen/react-cool-starter#189]
I would like to suggest to add react i18next because it's really good for multi language products, for example: I'm from Brazil, so most of our projects we need to have portuguese and english languages.

**And why react i18next and not react-intl?**
I really enjoy react i18next syntax, for example `t function`, it looks more productive and their repository is frequently updated (more than react-intl)

Anyway, awesome boilerplate 👍

**Comment by wellyshen** [comment]
@maiconcarraro Thank you for give this starter a try. I think it's better to keep it more "starter". As you see many starter kits are just a simple and clear environment for developers. If you want to integrate this starter with a multi-lang library I can help you.

**Comment by maiconcarraro** [comment]
@wellyshen I would appreciate very much your help 👍 how can we do this?

**Comment by maiconcarraro** [comment]
I'll share how I'm doing...

- src/i18-client.js
```js
import i18next from 'i18next';

import en from './locales/en/translation.json';
import pt from './locales/pt-BR/translation.json';

i18next.init({
  fallbackLng: {
    'pt-BR': ['pt'],
    default: ['pt']
  },
  resources: {
    en: { translation: en },
    pt: { translation: pt }
  }
});

export default i18next;

```
 

- src/client.js
```js
+ import { I18nextProvider } from 'react-i18next';
+ import i18next from './i18n-client';

import configureStore from './utils/configureStore';

...

  hydrate(
    <AppContainer>
      <Provider store={store}>
+        <I18nextProvider i18n={i18next}>
          <ConnectedRouter history={history}>
            {renderRoutes(Routes)}
          </ConnectedRouter>
+        </I18nextProvider>
      </Provider>
    </AppContainer>,
    // $FlowFixMe: isn't an issue

```

 

- src/pages/Home/Home.js
```js
+ import { translate } from 'react-i18next';

import { usersAction } from '../../actions';

...

+ type Props = {
+   home: HomeType,
+   fetchUsersIfNeeded: () => void,
+   t: string => string
+ };

...

  render() {
+     const { t } = this.props;

    return (
      <div className={styles.Home}>
        <Helmet title="Home" />
+         <div>{t('content.text')}</div>
        {this.renderUserList()}
      </div>
    );

...

export default compose(
  withRouter,
  connector,
+  translate()
)(Home);


```

and I have a folder on src > locales > en/pt-BR > translation.js

**Comment by maiconcarraro** [comment]
It worked and not worked... if I have the original Home.js file, and I run **yarn dev** its show the home page, then I replace Home.js file with those modifications and it *worked*

But if I stop **yarn dev**, and try again to run **yarn dev** with the Home.js modified, it doens't load the home page, keeps loading forever... Am i missing something?

**Comment by wellyshen** [comment]
I will spend time to survey it.

**Comment by maiconcarraro** [comment]
If you need some more information, you can ask me

**Comment by wellyshen** [comment]
@maiconcarraro Seems you have to setup it for SSR, you can see my [branch](https://github.com/wellyshen/react-cool-starter/tree/react-i18next) to setup it.

**Comment by maiconcarraro** [comment]
@wellyshen did you push something? https://github.com/wellyshen/react-cool-starter/compare/react-i18next

**Comment by maiconcarraro** [comment]
Alright, now it's working

I just added this on **server.js**

```js
+        <I18nextProvider i18n={i18next}>
          <Provider store={store}>
            {/* Setup React-Router server-side rendering */}
            <StaticRouter location={req.path} context={staticContext}>
              {renderRoutes(routes)}
            </StaticRouter>
          </Provider>
+        </I18nextProvider>
```

Okay, I think I got it what happened, server was rendering a different Home because it didnt have i18n like the client, so they dont match... then server conflicted?

**Comment by wellyshen** [comment]
@maiconcarraro 

Sorry my fault I have pushed some new stuff to the branch plz check it.
Yea server and client must have the same rendering stuff.

BTW, you can check the [SSR doc](https://react.i18next.com/misc/serverside-rendering) of i18n for more info.

**Comment by maiconcarraro** [comment]
@wellyshen thank you very much 👍 I don't have much experience with SSR yet, but I'm trying hard...

btw is just me or that SSR is really a kludge? 

I was reading how[ Airbnb created hypernova](https://medium.com/airbnb-engineering/server-rendering-code-splitting-and-lazy-loading-with-react-router-v4-bfe596a6af70) to solve their problem, and there is a quote from Ryan Florence, Co-Creator of React Router: "Godspeed those who attempt the server-rendered, code-split apps."

Also [Facebook do not use SSR](https://twitter.com/dan_abramov/status/711708653871624192), but react's community looks encouraged to make it work, people like you that help others 👍 

My main stack is java, so those problem with SSR and code splitting I don't have, so there are new things to learn and improve, I want to have a solid full-stack stack :)

**Comment by wellyshen** [comment]
@maiconcarraro 

SSR is good for SEO, UX, performance. Facebook is not using SSR for react but Facebook is **Universal** which means Facebook is some kind of SSR lol.

You are welcome, enjoying your React life man ;)
