### ISSUE TITLE
Autobuilding in dev mode stops on stylelint error

### ISSUE THREAD

**Issue by bytesnz** [wellyshen/react-cool-starter#19]
If running in dev mode (`npm start`), and you save a `scss` file that doesn't meet the lint requirements, an unhandled promise stops to autobuilding and it can only be restarted again by restarting dev mode (CTRL+C and `npm start`).

Below is an example of the error:
```
webpack built 2c46991acd218b194d93 in 9297ms

src/components/UserList/styles.scss
 5:3  ✖  Unexpected empty line before nested rule   rule-nested-empty-line-before


(node:30980) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed because of a stylelint error.
```

**Comment by wellyshen** [comment]
Hi @bytesnz This is a known issue, I am still looking for the solution.

**Comment by bytesnz** [comment]
Hi @wellyshen. Yeah, I figured it might be - have come across issues like it before, just thought it would be worth adding to the issues. I will try and look at it if I get a chance. Cheers for react-cool-starter - is a great starter kit

**Comment by wellyshen** [comment]
Hi @bytesnz It's quit inconvenient in dev, I will try to find the solution and fix it. Before that, I would like to suggest you to try the inline style library such as [radium](https://formidable.com/open-source/radium/). I personal use this library in my project and Inline style is great for react hot reloading ;)

**Comment by wellyshen** [comment]
HI @bytesnz 

It is a bug of webpack-isomorphic-tools, now it has been fixed ([detail](https://github.com/halt-hammerzeit/webpack-isomorphic-tools/issues/116#event-843473342)). 

If you don't want to stop the hot reloading process of .scss error, please turn the stylelint `failOnError` off from webpack config file, like below :

```
 new StyleLintPlugin({
      syntax: 'scss',
      failOnError: false,      // Disable style lint error terminating here
    }),
```

**Comment by bytesnz** [comment]
@wellyshen ah mesa muppet. Thanks for looking into / pointing it out to me.
