### ISSUE TITLE
Async exception after adding TailwindCss

### ISSUE THREAD

**Issue by hasusuf** [wellyshen/react-cool-starter#191]
I’m trying to add [tailwindcss](https://tailwindcss.com/) after adding tailwind to the project I have gotten that exception `Use process(css).then(cb) to work with async plugins` after performing `npm run dev` the exception belongs to `css-modules-require-hook` and by googling that exception I found that `css-modules-require-hook` don’t support async functions. Unfortunately, am not a Webpack expert that's why am seeking for help and I hope I can find it here. 
Example of what I have done so far in that repo: https://github.com/hasusuf/react-cool-starter-tailwind

Error stack:
```
$ better-npm-run dev
running better-npm-run in ~/playground/js/react/react-cool-starter-tailwind
Executing script: dev

to be executed: nodemon ./index.js
[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: src/server.js src/utils/renderHtml.js
[nodemon] starting `node ./index.js`
~/playground/js/react/react-cool-starter-tailwind/node_modules/css-modules-require-hook/node_modules/postcss/lib/lazy-result.js:266
                throw new Error('Use process(css).then(cb) to work with async plugins');
                ^

Error: Use process(css).then(cb) to work with async plugins
    at LazyResult.sync (~/playground/js/react/react-cool-starter-tailwind/node_modules/css-modules-require-hook/node_modules/postcss/lib/lazy-result.es6:319:23)
    at LazyResult.warnings (~/playground/js/react/react-cool-starter-tailwind/node_modules/css-modules-require-hook/node_modules/postcss/lib/lazy-result.es6:157:21)
    at fetch (~/playground/js/react/react-cool-starter-tailwind/node_modules/css-modules-require-hook/lib/index.js:102:16)
    at hook (~/playground/js/react/react-cool-starter-tailwind/node_modules/css-modules-require-hook/lib/index.js:125:18)
    at Object.cssModulesHook [as .css] (~/playground/js/react/react-cool-starter-tailwind/node_modules/css-modules-require-hook/lib/attachHook.js:16:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by wellyshen** [comment]
@hasusuf If you don't use **css modules** you can turn it off from [here](https://github.com/wellyshen/react-cool-starter/blob/master/tools/webpack/config.babel.js#L16) and comment the **css modules hook part** out from [here](https://github.com/wellyshen/react-cool-starter/blob/master/tools/webpack/hooks.js#L11).

**Comment by hasusuf** [comment]
Thanks, @wellyshen for your reply! 
The problem is that if I commented out the `css-modules-require-hook` definition, I will lose all `postcss-config` and Tailwind implementation as well [here](https://github.com/hasusuf/react-cool-starter-tailwind/blob/master/postcss.config.js#L8)

My problem is related to this [issue](https://github.com/css-modules/css-modules-require-hook/issues/58) and am wondering if I can refactor the `css-modules-require-hook` part with an alternative hook/plugin that supports async functions.

**Comment by wellyshen** [comment]
@hasusuf I will spend time to check your repo. Give me a simple reproduced environment as possible as you can.

**Comment by wellyshen** [comment]
@hasusuf 

I create a [branch](https://github.com/wellyshen/react-cool-starter/tree/tailwind-css) based on yours. You can see how to **remove css modules hook** through it. The differences are:
- Remove all css modules from components.
- Import scss styles in client-side only (styles can't work in SSR).

**Comment by hasusuf** [comment]
That's why I like this project the most! @wellyshen you rock 👍  
Regarding the SSR, I will work on that and I will keep this issue updated.

**Comment by wellyshen** [comment]
@hasusuf Cool keep going.

**Comment by FarazPatankar** [comment]
Recently came across this starter and we're planning to use it for our application but I am running into the same issue trying to add Tailwind. I don't need css modules and tried turning them off but the import for tailwind styles fails. Any pointers/suggestions? @wellyshen @hasusuf

**Comment by wellyshen** [comment]
@hasusuf Can you help with it ☝️with your "TailwindCss" experience?

**Comment by FarazPatankar** [comment]
@wellyshen Do you have any pointers for this? I tried disabling CSS modules and even the hook in `hooks.js` and then loading tailwind styles only in `client.js` but then they don't apply at all.

Any ideas on how I can get a basic version up and running with Tailwind?

**Comment by wellyshen** [comment]
@FarazPatankar I will spend time to see how to integrate it with this starter-kit. But not today, I need to work tomorrow...

**Comment by wellyshen** [comment]
@hasusuf It's not hard to integrate Tailwind-Css with this starter, you can see this [example](https://github.com/wellyshen/react-cool-starter/tree/example/tailwind-css). I only did two things:
1. Follow the [doc](https://tailwindcss.com/docs/installation/#using-tailwind-cli) to compile it
2. Import it [here](https://github.com/wellyshen/react-cool-starter/blob/example/tailwind-css/src/app/index.js#L10)

**Comment by FarazPatankar** [comment]
With this approach, we'd manually have to build Tailwind every time we make a change to the config, right?

I followed an approach similar to yours but I tried adding it in the postcss config and that's when I kept getting the error that this issue is about.

**Comment by wellyshen** [comment]
@FarazPatankar It's the easiest way that I found to integrate with this starter. You don't need to build it manually. You can integrate it with commands where you need. e.g `"dev": yarn tailwind && better-npm-run dev`.
