### ISSUE TITLE
Private page and css body

### ISSUE THREAD

**Issue by itgelo** [wellyshen/react-cool-starter#193]
Lately I am very interested in this boilerplate,
and I am interested in learning it. but there are some things I like to know.

- How to make a good private page and public page in this boilerplate, which file do I need to edit.
- I have 2 pages, ie: `/logins` and `/dashboards` and each page has a different css body {}, can this boilerplate do it?

**Comment by wellyshen** [comment]
@itgelo I'll spend time to reply your question.

**Comment by wellyshen** [comment]
@itgelo 

- For protected route: this starter use **react-router** therefore you can handle your protected route like [this](https://tylermcginnis.com/react-router-protected-routes-authentication/) (there're many authentication with react-router tutorials you can find on Google).

- For page styles: each page has its own `styles.scss`. you can define the `body { ... }` styles in it.
