### ISSUE TITLE
Bug - Analyze reports development bundle rather than production bundle

### ISSUE THREAD

**Issue by jbidston** [wellyshen/react-cool-starter#194]
### Expected Behavior
When running `yarn analyze` I expect the report to include analysis of production bundles.

### Actual Behavior
Analysis appears to be of development bundles. For example, `react-dom.development.js` appears instead of `react.dom-production.min.js`.

May be caused by `NODE_ENV=analyze` and not `NODE_ENV=production`.

### Your Environment
* Clint OS
`Mac OS Sierra 10.12.6`
* Browser and its version
`Chrome 68.0.3440.106`
* Version of node
`8.11.1`

### Suggestion
Add `-p` option to `package.json > betterScripts.analyze.command`

```diff

- "command": "webpack --progress --hide-modules --config ./tools/webpack/config.babel.js",
+ "command": "webpack -p --progress --hide-modules --config ./tools/webpack/config.babel.js",

```

**Comment by wellyshen** [comment]
@jbidston Thank you man. It has been fixed on [v2.5.7](https://github.com/wellyshen/react-cool-starter/releases/tag/v2.5.7).
