### ISSUE TITLE
Not working HMR when edit scss file with css modules

### ISSUE THREAD

**Issue by TotallWAR** [wellyshen/react-cool-starter#196]
### Do you want to report a bug or request a feature?
* Bug

### Expected Behavior
I edit scss file, save it and styles in browser are changing.

### Actual Behavior
I edit scss file, save it and in browser it happens nothing. I should reload page in beowser and only after this styles are applied.

### Your Environment
* Mac OS Sierra.
* The latest Chrome.
* Version of node - 10.0.0

**Comment by wellyshen** [comment]
@TotallWAR css/sass hot reloading is support in [v2.6.0](https://github.com/wellyshen/react-cool-starter/releases/tag/v2.6.0)

**Comment by TotallWAR** [comment]
Great! It works. Thank you!
