### ISSUE TITLE
Hot module replacement on client doesnt seem to work

### ISSUE THREAD

**Issue by hitesh97** [wellyshen/react-cool-starter#200]
### Do you want to report a bug or request a feature?
Cloned this repository and performed initial steps of "Yarn install" and then "yarn dev" 
Project compile and opened url "http://localhost:3000" with landing page and user's list.

Changed simple text from '<h4>user list</h4>' on userList component to '<h4>User List Changed!!</h4>'

Saw on visual studio code, the compilation began and finished without any issues!

### Expected Behavior
web browser to hot reload the page and show updated Text.

### Actual Behavior
Page did not reload...and did not show updated text

"http://localhost:3000/__webpack_hmr" seems to not get any updates from server

### Your Environment
* Client OS :     windows
* Browser and its version  : Chrome Version 69.0.3497.100
* Version of node : 8.11.4

**Comment by wellyshen** [comment]
@hitesh97 Sorry for replay lately. I have tested it in the latest commit. The hot reloading works as expect. Can you plz try it?
