### ISSUE TITLE
Is it Possible to do redirects in routes.js

### ISSUE THREAD

**Issue by ghost** [wellyshen/react-cool-starter#201]
Just a quick question is it possible to do a redirect in routes.js?

**Comment by wellyshen** [comment]
@tom-seegreen Seems it's possible to use <Redirect /> component in routes config. You can refer [here](https://github.com/ReactTraining/react-router/issues/5138#issuecomment-311824053). Is that you want?

**Comment by TotallWAR** [comment]
You can use redirect from ```import { Redirect } from 'react-router';```.
I tried this method but more flexible one for me is redirecting in lifecycle methods.

**Comment by ghost** [comment]
@wellyshen Thanks for the link that's exactly it
