### ISSUE TITLE
RIght way to do login redirection

### ISSUE THREAD

**Issue by dayrlism10** [wellyshen/react-cool-starter#204]
Hi there,
can i know what is the right way to handle login authentication redirection?
just like how 404 work, if there is not login authenticate, redirect the user something like that,
i realise this is using react router config, have no clue how i can customise this, any suggestion please?

**Comment by wellyshen** [comment]
@dayrlism10,
There're many ways to do authentication redirection with `react-router-config`.
You can do redirect via `render` method as this [discussion](https://github.com/ReactTraining/react-router/issues/4962#issuecomment-376567551) or use HOC to do redirect as this [discussion](https://github.com/ReactTraining/react-router/issues/4962#issuecomment-387275863).

**Comment by dayrlism10** [comment]
@wellykkstream 
hi, i seems abit confuse with the solution, my route config kept giving error when i trying to place into this form, or attempt to modify the router config structure.

`
{
        path: "/restricted-area",
        render: (props) => isUserLoggedIn() ? <RestrictedArea/> : <Redirect to="/login"/>
},
`

**Comment by dayrlism10** [comment]
was wondering, if can you write a quick example with react cool starter, it will be great?

**Comment by wellyshen** [comment]
@dayrlism10 I'll show you how when I have free time. Please stay passionate for finding solution.

**Comment by dayrlism10** [comment]
@wellyshen haha sure i am, i actually doing it in this way at the moment, but seems like not a good practice and also it will have a quick blink when im accessing restricted page.

 ```
 async componentWillMount() {
    const flag = await fetchAuthState();
    if (!flag) { this.props.history.push('/login'); }
    if (this.props.location.pathname === '/login') {
      if (flag) {
        this.props.history.push('/');
      }
    }
  }
```

**Comment by wellyshen** [comment]
@dayrlism10 Seems `render` method works as expect. See this [example](https://github.com/wellyshen/react-cool-starter/blob/feature/auth-example/src/routes.js) for more detail.

**Comment by dayrlism10** [comment]
thanks so much! man, i think need to upgrade my dependencies, cause mine is all quite old, doest fit this feature. finally find out this is the matter lel

**Comment by dennymiloen** [comment]
hi @wellyshen can you show the example again?the link was not found :(

**Comment by wellyshen** [comment]
@dennymiloen Sorry I have deleted the branch. @dayrlism10 Would you love to show it to @dennymiloen ?

**Comment by dayrlism10** [comment]
@dennymiloen did not notice this thread somehow, sorry for the late
in your route config you could do it this way.


```
render: (props: any) => {
     return isLoggedIn() ? <AsyncLayouts {...props} /> : <AsyncLogin />;
},

```
