### ISSUE TITLE
If disable css modules - Imported css is working only in development mode, but not working in production mode

### ISSUE THREAD

**Issue by RomanBON** [wellyshen/react-cool-starter#206]
### Expected Behavior

I set css-modules to disable, change scss imports. I want my component to work the same in both production and development mode.

### Actual Behavior

it's working only in development mode.

### Your Environment

- Ubuntu 18.04.1 LTS
- Chrome Version 70.0.3538.77 (Official Build) (64-bit) on Linux
- v10.10.0 node

**Comment by ilkertuna** [comment]
I had the same problem.

In development mode, css modules are included in to bundles.
However, in production mode, css modules are not included in to bundles.

Dummy Solution: 
include each css file in renderHtml.js 
i.e.
<link href="/my-path/my-custom-css.css" media="screen, projection" rel="stylesheet" type="text/css">

Better Solution:
create the css folder in the public folder directory, then include all of them like @wellyshen did, (You can inspect server.js and renderHtml.js to get an idea).

**Comment by wellyshen** [comment]
@RomanBON Thank you, I will spend time to check it.

**Comment by wellyshen** [comment]
@RomanBON Fixed in [here](https://github.com/wellyshen/react-cool-starter/releases/tag/v2.8.1)

**Comment by wellyshen** [comment]
@RomanBON Sorry, it is fixed in [this version](https://github.com/wellyshen/react-cool-starter/releases/tag/v2.8.3)
