### ISSUE TITLE
Integrity check failed for "listr-update-renderer"

### ISSUE THREAD

**Issue by taime** [wellyshen/react-cool-starter#208]
### bug

error https://github.com/okonet/listr-update-renderer/tarball/upgrade-log-update: Integrity check failed for "listr-update-renderer" (computed integrity doesn't match our records, got "sha1-Bgc/qTFmJ3YHp4FPTh+DlgCBQUw=")
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

### How to repeat:
```
git clone https://github.com/wellyshen/react-cool-starter.git
cd react-cool-starter
yarn
```

### Your Environment
- Mac OS
- Node v11.7.0

**Comment by alirezavalizade** [comment]
It's a problem in yarn.lock, If you remove it and then run `yarn install` again you will not see that,
But! this is a temporary solution, We'll fix it soon!

**Comment by taime** [comment]
Thanks! May be we should remove it from repo then!

**Comment by alirezavalizade** [comment]
No, it's nice to have it because of the dependencies. specially when you have large scale apps.

**Comment by alirezavalizade** [comment]
@wellyshen

**Comment by wellyshen** [comment]
@alirezavalizade What?
