### ISSUE TITLE
Rendering Routes error

### ISSUE THREAD

**Issue by redlinecodes** [wellyshen/react-cool-starter#209]
Bug - cloned, installed and built per instructions. Then ran yarn dev and got this error message in my Terminal: `===> Rendering routes error: ReferenceError: assets is not defined`

I'm guessing that error is referring to the 'assets' from this line: `.send(renderHtml(head, assets, htmlContent, initialState));`

So I looked in my /public/assets and I don't see any css files. Is that why its failing? I removed your default theme directory with the variables.scss (wanted to begin to customize a bit). Thanks in advance.

BTW: Great starter kit for SSR!
Ubuntu 1.604
Chrome 72x
Node 10x

**Comment by wellyshen** [comment]
@redlinecodes Are there `loadable-assets.json` and `webpack-assets.json` in the public folder?

**Comment by redlinecodes** [comment]
@wellyshen Yes there are.  Any other ideas?

**Comment by wellyshen** [comment]
@redlinecodes Did you remove all the related reference  of `variables.scss` (e.g. https://github.com/wellyshen/react-cool-starter/blob/master/src/app/styles.scss#L1)

**Comment by redlinecodes** [comment]
@wellyshen - Yes - is that causing this?

**Comment by TotallWAR** [comment]
How can we get more info about error in react component on server side rendering?
I have an error in catch block in server.js with sending 404 status, but i can't detect where this error appeared?

**Comment by wellyshen** [comment]
@TotallWAR You can use `Error Boundaries` API for catching the error of react component, plz refer to the doc => https://reactjs.org/docs/error-boundaries.html

**Comment by wellyshen** [comment]
@redlinecodes May I see your repo?

**Comment by wellyshen** [comment]
Close due to inactive

**Comment by redlinecodes** [comment]
@wellyshen - sorry about that - got diverted away from this for awhile. I did get it working and it was scss scenario. Thanks for your great support!
