### ISSUE TITLE
ERROR in Entry module not found: Error: Can't resolve 'babel'

### ISSUE THREAD

**Issue by kiki-le-singe** [wellyshen/react-cool-starter#21]
Hi!

I just tried to start the react-cool-starter project, but I have some troubles.

I get the following message: `webpack-isomorphic-tools (waiting for the first webpack build to finish)` when I'm running `npm start`. So I runned `npm run build` to fix it. Then I've got this error: `ERROR in Entry module not found: Error: Can't resolve 'babel' in '/PATH/react-cool-starter'`.

Do you have any ideas?

Thanks for your time.

**Comment by wellyshen** [comment]
Hi @kiki-le-singe Thank you for your report the error has been fixed, please clone the latest commit repo :)

**Comment by kiki-le-singe** [comment]
Hi @wellyshen Thank you, it works. I'll try it later :)
