### ISSUE TITLE
Disconnect between client-side and server-side rendering

### ISSUE THREAD

**Issue by mattcarlotta** [wellyshen/react-cool-starter#210]
### Expected Behavior

Client-side and server-side should contain matching HTML.

### Actual Behavior

Saving a file updates the client-side, but it doesn't reflect on the server-side until the node process has been stopped and restarted. 

### Reproduction

- Add any JSX element to a file (for example, add `<h1>Hello</h1>` to `components/UserList/index.js`)
- Refresh the page

Client updates on save:
![clientupdate](https://user-images.githubusercontent.com/22607722/53515165-37533100-3a7e-11e9-856c-8273cd1aa591.png)

Refreshing page:
![refresh](https://user-images.githubusercontent.com/22607722/53515076-01ae4800-3a7e-11e9-90b9-11971168f9a9.png)

This may also be the reason why the client-side resolves instantaneously regardless of a `delay` setting in a `Loadable` import. As such, the `Loading` component is never triggered. 

For example, in `pages/Home/index.js`, I created a new promise to delay the import. This should, in theory, show a `console.log("Loading...);` and show the `Loading` component. But as you can [see in the video](https://youtu.be/iWQI04BBN5c), the `Loading` component was never called  (I had to change the file, save and reload for this to delay, otherwise, it loads instantly and then logs a `imported asset` a few seconds later). I'm assuming this isn't an issue with `react-loadable` but how the webpack config is set up. Unfortunately, I haven't been able to narrow it down.

```
import Loadable from "react-loadable";

import { Loading } from "../../components";

export default Loadable({
  loader: async () =>
    await new Promise(resolve => {
      setTimeout(() => {
        console.log("Imported asset");
        resolve(import("./Home"));
      }, 3000);
    }),
  loading: () => {
    console.log("Loading...");
    return Loading;
  },
  delay: 3000
});
```

Also, it appears importing or changing `.scss` styles doesn't apply changes on the client. Requires a process restart.

### Your Environment

- Linux Mint 19.1 (Kernel 4.15.0-45)
- Version 72.0.3626.119 (Official Build) (64-bit)
- Node v11.10.0

**Comment by mattcarlotta** [comment]
Figured out the problem. See fix here: https://github.com/nozzle/react-static/issues/144#issuecomment-348270365

**Comment by wellyshen** [comment]
@mattcarlotta Thank you, learnt from you.
