### ISSUE TITLE
Upgrade lint-staged to 8.1.5

### ISSUE THREAD

**Issue by geekuality** [wellyshen/react-cool-starter#212]
### Expected Behavior

When initially running `yarn`, packages should install without errors.

### Actual Behavior

```
$ yarn
yarn install v1.13.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error https://github.com/okonet/listr-update-renderer/tarball/upgrade-log-update: Integrity check failed for "listr-update-renderer" (computed integrity doesn't match our records, got "sha1-Bgc/qTFmJ3YHp4FPTh+DlgCBQUw=")
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Suggested fix

Upgrade `lint-staged` to [v8.1.5](https://github.com/okonet/lint-staged/releases/tag/v8.1.5) that fixes the problem by using original author's latest release (v0.5.0) of `listr-update-renderer` instead of an outdated fork used previously.

### Your Environment

- Yarn v1.13.0

**Comment by wellyshen** [comment]
@geekuality Could you mind to send me a PR for fixing this issue?
