### ISSUE TITLE
Lint errors: Typescript used in .js files

### ISSUE THREAD

**Issue by ginna-baker** [wellyshen/react-cool-starter#215]
IDE linter complains because there is no .ts extension.  

Also, there is no tslint config.  I'm new to react.  Am I missing something here?
<img width="688" alt="Screen Shot 2019-03-14 at 2 03 18 PM" src="https://user-images.githubusercontent.com/6732956/54387875-14ba3e00-4662-11e9-8ebc-c5bb8fe07d89.png">

**Comment by wellyshen** [comment]
@ginna-baker I think you need [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) to let eslint works with typescript.
