### ISSUE TITLE
prevent refreshing then it return to root page

### ISSUE THREAD

**Issue by geng890518** [wellyshen/react-cool-starter#216]
Hi, I need to prevent refreshing the page , then it jump to the root page . How can I do it??

**Comment by wellyshen** [comment]
@geng890518 Can you give me more detail about your case?

**Comment by geng890518** [comment]
@wellyshen My url is "/userInfo/1",  I press command + R, then the url become "/". Is there any way to let it stay the current page?

**Comment by wellyshen** [comment]
@geng890518 Oh, this's a bug. It has been fixed in [v2.8.6](https://github.com/wellyshen/react-cool-starter/releases/tag/v2.8.6)
