### ISSUE TITLE
npm run start:production failed

### ISSUE THREAD

**Issue by perevezencev** [wellyshen/react-cool-starter#22]
I run **npm install** and **npm run start:production**
http://pastebin.com/LjzRFhuK
what am I doing wrong?

**Comment by wellyshen** [comment]
@perevezencev 

I recommend you use the latest commit version.
Or you can remove the "DedupePlugin" plugin and disable the eslint terminal from the webpack config as below :

``` javascript
        eslint: {
          failOnError: false,  // Disable js lint error terminating here
        },
```

**Comment by perevezencev** [comment]
I use latest version. Your method does not work for me

**Comment by wellyshen** [comment]
Can you share your repo to me?

**Comment by perevezencev** [comment]
I executed only 4 instructions
```
git clone https://github.com/wellyshen/react-cool-starter.git
cd react-cool-starter
npm install
npm run start:production 
```

my repository is no different from your

**Comment by wellyshen** [comment]
@perevezencev what's your IDE?

**Comment by perevezencev** [comment]
@wellyshen WebStorm (win 10)

**Comment by wellyshen** [comment]
@perevezencev 

1. I guess here's a solution for the error on Win : http://stackoverflow.com/questions/33189722/linebreak-style-expected-linebreaks-to-be-lf-but-found-crlf-eslint

2. Or you can config the line-break rule through .eslintrc as below : 

```
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "plugins": ["react"],
  "env": {
    "es6": true,
    "browser": true,
    "node": true,
    "mocha": true
  },
  "rules": {
    "global-require": 0,
    "no-underscore-dangle": 0,
    "no-console": 0,
    "linebreak-style": 0,   // Add a new rule here
    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
  },
  "globals": {
    "__CLIENT__": true,
    "__SERVER__": true,
    "__DISABLE_SSR__": true,
    "__DEV__": true,
    "webpackIsomorphicTools": true,
    "should": true,
    "expect": true,
    "assert": true
  }
}
```

**Comment by perevezencev** [comment]
Cool!! This solved my problem, thank you very much

**Comment by wellyshen** [comment]
Cheers ;)
