### ISSUE TITLE
JS being run twice in production

### ISSUE THREAD

**Issue by mikejdegroot** [wellyshen/react-cool-starter#220]
Hi,
Thanks for the great boilerplate! We just have a strange issue when the project is run in production. 

On the dev server, network requests display as normal in devtools and the site works as expected. However, in production the requests are doubled up and the page even appears to render twice. 

Whilst checking around the code I noticed that (in production) the main.***.js and main***.css file is put in twice at the end of the file, whereas in dev it is only placed in once. I downloaded a fresh boilerplate to see if it was something I had done, and the script tag is doubled up in there as well. Is this expected behaviour?

Below is a screenshot of the script tags in my production env -

![Screen Shot 2019-04-08 at 18 16 43](https://user-images.githubusercontent.com/27430574/55743567-8a7bb480-5a2a-11e9-92d2-39133f676676.png)

As you can see the css and js files are doubled, and the "svg-icons" div, which is injected by my react app is also injected twice. Same shot in development below-

![Screen Shot 2019-04-08 at 18 23 52](https://user-images.githubusercontent.com/27430574/55743950-8d2ad980-5a2b-11e9-891f-8a00bb86f8ca.png)

Below is a shot from devtools network tab in production, showing the doubled up requests - 

![Screen Shot 2019-04-08 at 18 19 54](https://user-images.githubusercontent.com/27430574/55743834-40470300-5a2b-11e9-83c8-e33ffc445b4d.png)

And the same in development - 

![Screen Shot 2019-04-08 at 18 22 43](https://user-images.githubusercontent.com/27430574/55743894-640a4900-5a2b-11e9-9b8c-1527fc905d69.png)

If you could provide any help, advice or point me in the right direction it would be much apprecated. Thanks in advance

### Your Environment

- Client OS
Mac 10.13.4
- Browser and its version
Chrome 73 and tested on Safari 11.1
- Version of node
10.13.0

**Comment by wellyshen** [comment]
@mikejdegroot Fixed by [v2.8.8](https://github.com/wellyshen/react-cool-starter/releases/tag/v2.8.8). Thanks for @aslapkov 's help 👍

**Comment by mikejdegroot** [comment]
Thank you guys!
