### ISSUE TITLE
Push method from connected-react-router not working

### ISSUE THREAD

**Issue by francistm** [wellyshen/react-cool-starter#222]
### Expected Behavior

``` js
import React from 'react'
import { push } from 'connected-react-router'

class Comp extends React.Component {
  componentDidMount () {
    setTimeout(() => {
      this.props.dispatch(push('/'))
    }, 5e3)
  }

  render () {
    return <div>Will redirect to root after 5 seconds</div>
  }
}
```

Using `push` method which import from `connected-react-router` or dispatch it in connected action, will change the location to selected route.

Tell me what should happen.

### Actual Behavior

The url in browser changed, but previous component didn't unload, and next component did not load.

### Your Environment

- Client OS `OSX 10.14`
- Browser and its version `Firefox 66 or Chrome 73`
- Version of node: `10.15.3`

## Something else but not SPAM
According [package.json in V2.8.8](https://github.com/wellyshen/react-cool-starter/blob/v2.8.8/package.json)

 - `connected-react-router` version is `^6.3.2`
 - `react-router` is `^5.0.0`
 - [client.js](https://github.com/wellyshen/react-cool-starter/blob/v2.8.8/src/client.js#L22) is like 
```js
<AppContainer>
	<Provider store={store}>
		<ConnectedRouter history={history}>
			<BrowserRouter>{renderRoutes(Routes)}</BrowserRouter>
		</ConnectedRouter>
	</Provider>
</AppContainer>
```

But in [connected-react-router document](https://github.com/supasate/connected-react-router#step-3) said should remove `BrowserRouter` as our condition.

After remove <BrowserRouter />, looks `push` method which import from connected-react-router works fine.

**Comment by wellyshen** [comment]
@francistm Thank you for this bug reporting. It really helpful. I have released [v2.8.9](https://github.com/wellyshen/react-cool-starter/releases/tag/v2.8.9) for this bug fixing.
