### ISSUE TITLE
Chunks are not splitted

### ISSUE THREAD

**Issue by xD3CODER** [wellyshen/react-cool-starter#225]
Hi,

I just noticed that code splitting though React-Loadable seems to not work anymore.

### Expected Behavior

Pages required with react-loadable should be split in different bundles

### Actual Behavior

All code is bundled inside a single chunk file

### Your Environment

- Node 10.8

**Comment by Rid** [comment]
I've also noticed this issue, I've already fixed it in my project and I'll make a PR tomorrow for it here.

**Comment by Rid** [comment]
This is now fixed in https://github.com/wellyshen/react-cool-starter/pull/226, @wellyshen ptal.

**Comment by xD3CODER** [comment]
> This is now fixed in #226, @wellyshen ptal.

Mmh, I tried your solution, but it doesn't seem to work any better.
I think it's time to move on [https://github.com/smooth-code/loadable-components](url) because react-loadable is not maintained and has not been updated since a long time

**Comment by Rid** [comment]
@xD3CODER what is yarn analyze outputting? I've tested #226 and code splitting is definitely working. Are you using dynamic imports on the code which you want splitted?

We were previously using loadable-components, but you can see why we switched here: #197

**Comment by xD3CODER** [comment]
That's weird, i'll retry this afternoon.

Now loadable-components support prefetch, and the library is recommanded by react team as alternative of lazy

**Comment by Rid** [comment]
This was the main issue I had when trying to implement it here last time:
https://github.com/smooth-code/loadable-components/issues/135

It seems there are still some outstanding issues related to SSR:
https://github.com/smooth-code/loadable-components/issues/345
https://github.com/smooth-code/loadable-components/issues/343
https://github.com/smooth-code/loadable-components/issues/230

We would probably need those fixed/resolved before we can think about trying again.

**Comment by Rid** [comment]
I will try loadable-components again today as I think most of those issues wouldn't apply here.

**Comment by xD3CODER** [comment]
I just tried loadable-components I have the same issue:
[https://github.com/smooth-code/loadable-components/issues/135](url)

**Comment by xD3CODER** [comment]
> @xD3CODER what is yarn analyze outputting? I've tested #226 and code splitting is definitely working. Are you using dynamic imports on the code which you want splitted?
> 
> We were previously using loadable-components, but you can see why we switched here: #197

My fault, your fix works well

**Comment by xD3CODER** [comment]
I made the same mistake with loadable-component, it's work well, i'll make a PR soon
