### ISSUE TITLE
[Discussion] eval-source-map over eval

### ISSUE THREAD

**Issue by Rid** [wellyshen/react-cool-starter#227]
Thanks again for maintaining this awesome project @wellyshen.

I'd like to know your opinion on changing the `eval` source mapping to `eval-source-map`. Just to refresh you this is from the webpack docs:

`eval` - Each module is executed with `eval()` and `//@ sourceURL`. This is pretty fast. The main disadvantage is that it doesn't display line numbers correctly since it gets mapped to transpiled code instead of the original code (No Source Maps from Loaders).

`eval-source-map` - Each module is executed with `eval()` and a SourceMap is added as a DataUrl to the `eval()`. Initially it is slow, but it provides fast rebuild speed and yields real files. Line numbers are correctly mapped since it gets mapped to the original code. It yields the best quality SourceMaps for development.

It seems like eval can be slightly confusing as the line numbers are not displayed correctly. I've been using `eval-source-map` on a big project and it seems fast and more suited to easier development.

**Comment by wellyshen** [comment]
@Rid Sure, can you do it with PR #226 ?

**Comment by Rid** [comment]
@wellyshen no problem, I've put it in #228
