### ISSUE TITLE
Dictation mistakes

### ISSUE THREAD

**Issue by amerllica** [wellyshen/react-cool-starter#229]
### Expected Behavior

In some configs files, there are many wrong dictation mistakes.

### Actual Behavior

Tell me what happens instead.

### Your Environment

- Client OS: Mac OSX
- Browser and its version: Google Chrome -latest
- The version of node: 10

**Comment by wellyshen** [comment]
@amerllica I leave a comment, plz take time to see it :)

**Comment by amerllica** [comment]
@wellyshen, Where do you leave a comment? I see my PR now but I don't see your comment anywhere.

**Comment by wellyshen** [comment]
@amerllica [Here](https://github.com/wellyshen/react-cool-starter/pull/230/files#diff-808ea934e145b719cd0a30abda96c283R8)

**Comment by amerllica** [comment]
Dear @wellyshen, your Starter is awesome, it's a true fact, but the comment has typo mistake. I make a PR to fix it. I cannot understand:

> I leave a comment, plz take time to see it :)

Do I make a mistake? Do I do something wrong?

![Screen Shot 2019-07-21 at 10 44 32](https://user-images.githubusercontent.com/10472437/61587730-9720b480-aba4-11e9-96ff-9df909292463.png)

I see it, there is no review comment.

**Comment by wellyshen** [comment]
@amerllica It's fine just a little thing I will handle it, I am going to merge your PR, 3Q
