### ISSUE TITLE
Implementing absolute path

### ISSUE THREAD

**Issue by amerllica** [wellyshen/react-cool-starter#231]
### It is a feature

- Importing component by using relative path causes to see the hell-dots issue. it is hard to read and make the project dirty.

### Expected Behavior
In these settings when projects going on development, we will see the line of imports like below:

    import SomeComponent from '../../../../../../components';
    import fooHandler from '../../../../utils/helpers';
    ...

### Actual Behavior
It should be like below:

    import SomeComponent from '@components';
    import fooHandler from '@utils/helpers';

That has two important benefits. _one:_ it's very readable _two:_ because of absolute paths the line of code could be migrated as easy as can.

### Your Environment

- Client OS: Mac OSX
- The browser and its version: Google Chrome - latest version
- The version of node: 10

**Comment by wellyshen** [comment]
@amerllica Some think absolute path isn't a good practice and some like it. As a starter-kit. I prefer let developer to setup it by themself.

**Comment by dayrlism10** [comment]
can i know how to configure that absolute paths, in webpack?

**Comment by wellyshen** [comment]
@dayrlism10 [Here](https://webpack.js.org/configuration/resolve/) you are

**Comment by amerllica** [comment]
Dear @dayrlism10, by using `resolve` and `alias` you can set _absolute path_. And if you use JetBrains IDEs to develop you should set your webpack configuration file inside **Settings > Language and Frameworks > JavaScript > Webpack**.

But for Cool Starter in the earlier version, I set the absolute path and it doesn't work properly. maybe in the latest version, it works.
