### ISSUE TITLE
Using Redux-Saga instead of Redux-Thunk

### ISSUE THREAD

**Issue by amerllica** [wellyshen/react-cool-starter#232]
### I wanna ask a feature

- Based on [this article](https://is.gd/fkvY3x) Using Redux-Saga has some benefits to Redux-Thunk

### Expected Behavior

Handling asynchronous actions buy using Redux-Saga

### Actual Behavior

But now all of the asynchronous actions are handled by using Redux-Thunk

### Your Environment

- Client OS: Mac OSX
- Browser and its version: Google Chrome -latest version
- The version of node: 10

**Comment by dayrlism10** [comment]
i think redux-saga is a nice too.

**Comment by amerllica** [comment]
Dear @dayrlism10, yes the `Redux-Saga` is nice but actually, it has many benefits to `redux-thunk`

**Comment by dayrlism10** [comment]
you mean redux sage and redux thunk can work together?

**Comment by amerllica** [comment]
@dayrlism10 , Absolutely, Both can work together but I don't mean that you said. I mean we could implement `Redux-Saga` and completely remove `redux-thunk`.

**Comment by wellyshen** [comment]
@amerllica Redux-Saga is great but more learning curve. Some ppl don't need it that's why I choice Redux bcz it's basic and common.
