### ISSUE TITLE
How hard to add a proxy?

### ISSUE THREAD

**Issue by redlinecodes** [wellyshen/react-cool-starter#235]
I'd like to add a proxy to this so that I can add my Nodejs backend (login etc), any thoughts/suggestions or simple example?

**Comment by hienhuynhtm** [comment]
it quite easy, just do 2 following steps:

- in **server.js**: add this line
`require('./routes.js')(app);`
- add new file called **routes.js**:
```
module.exports = function (app) {
	app.get('/login', function (req, res, next) {
		res.render('login', { flash: req.flash() } );
	});

	app.post('/login', function (req, res, next) {

		// you might like to do a database look-up or something more scalable here
		if (req.body.username && req.body.username === 'user' && req.body.password && req.body.password === 'pass') {
			req.session.authenticated = true;
			res.redirect('/secure');
		} else {
			req.flash('error', 'Username and password are incorrect');
			res.redirect('/login');
		}

	});

	app.get('/logout', function (req, res, next) {
		delete req.session.authenticated;
		res.redirect('/');
	});
};
```

**Comment by wellyshen** [comment]
@redlinecodes What kind of proxy do you want? Can you give me more detail.

**Comment by redlinecodes** [comment]
@wellyshen - just something simple so that instead of using jsonplaceholder and `headers: { 'Allow-Control-Allow-Origin': '*' },`

I can use my own auth backend

**Comment by redlinecodes** [comment]
Clicked the wrong button - DIDN'T mean to close it....

**Comment by redlinecodes** [comment]
@wellyshen Maybe something with express-http-proxy?

**Comment by wellyshen** [comment]
@redlinecodes I think you can do it by follow their [example](https://github.com/villadora/express-http-proxy#example). It's easy.

**Comment by redlinecodes** [comment]
@wellyshen thanks for the link. Sometimes I google/search too much and forget about the docs.
