### ISSUE TITLE
importing scss from node_modules causes build to fail

### ISSUE THREAD

**Issue by amitava82** [wellyshen/react-cool-starter#236]
### Bug
Importing a scss (eg, bootstrap) fails with error 
```
 Rendering routes error: Error: File to import not found or unreadable: ~bootstrap/scss/bootstrap.
```
This happens when import is done in lazy loaded component. How to reproduce:
1. add `@import "~bootstrap/scss/bootstrap";` at the top of `pages/UserInfo/styles.scss`
2. directly navigate to `http://localhost:3000/UserInfo/1` or refresh page. It'll show "Not Found :(" and above error in console.

Seems to work if imported to top level component or index route component.

**Comment by wellyshen** [comment]
@amitava82 Yup, it's better to import global style in top level. Anything I can help you?

**Comment by amitava82** [comment]
Should be able to import scss from node_nodules relavant for each chunk.
This seems to be a bug that importing from node modules fails but not for
Local scss files. Importing everything in single file isn't optimal for a
large app.

**Comment by wellyshen** [comment]
@amitava82 I will check it.

**Comment by wellyshen** [comment]
@amitava82 I can import bootstrap.scss from UserInfo.scss without building error, plz [see here](https://github.com/wellyshen/react-cool-starter/tree/example/bootstrap)

**Comment by amitava82** [comment]
@wellyshen Nope, I tried your branch, it does not work. navigate to `http://localhost:3000/UserInfo/1` and then hit refresh browser.

![Screenshot 2019-08-23 at 3 33 51 PM](https://user-images.githubusercontent.com/1279530/63584853-7096d480-c5bb-11e9-9417-c6d6548672ba.png)

**Comment by wellyshen** [comment]
@amitava82 How did you try my branch? I didn't see error on `http://localhost:3000/UserInfo/1`

**Comment by amitava82** [comment]
Usual git clone and check out your bootstrap branch

**Comment by wellyshen** [comment]
@amitava82 So wired... May I know your environment? e.g. node version, OS etc.

**Comment by amitava82** [comment]
node v8.15.1, OSX latest.

>

**Comment by wellyshen** [comment]
@amitava82 Can you try it with higher node.js version (see [doc](https://github.com/wellyshen/react-cool-starter#requirements))

**Comment by amitava82** [comment]
Used `v12.1.0`, but no luck.

>

**Comment by hienhuynhtm** [comment]
@amitava82 how about removing `~` character.
In my project, I just use like below and it works
`import '@package/folder_name/dist/ace.css';`

**Comment by amitava82** [comment]
Yeah importing like so `@import 'node_modules/bootstrap/scss/bootstrap';`
works.

>
