### ISSUE TITLE
Why is connected-react-router used?

### ISSUE THREAD

**Issue by redlinecodes** [wellyshen/react-cool-starter#237]
@wellyshen  I'm not questioning WHY its used - just exactly what it is. I've been doing some searching and reading but there's no real clear explanation on what it is - except that its a redux binding for React Router 4/5.

What would be a use case for why you would want navigation done by redux? What exactly is the benefit?

**Comment by wellyshen** [comment]
@redlinecodes With this library you can access react-router's `history` within redux's data flow. e.g. action creator.

**Comment by redlinecodes** [comment]
@wellyshen So then you could possibly look at the user's history of navigation on the site?

**Comment by wellyshen** [comment]
@redlinecodes You can see these data in redux store:
<img width="794" alt="螢幕快照 2019-08-25 下午2 53 56" src="https://user-images.githubusercontent.com/21308003/63646626-46bee880-c748-11e9-9512-d83c89d873df.png">

**Comment by wellyshen** [comment]
This's not an issue, so I close it.
