### ISSUE TITLE
"SyntaxError: Unexpected token *" issue

### ISSUE THREAD

**Issue by hienhuynhtm** [wellyshen/react-cool-starter#238]
hi @wellyshen @Rid,
Do you guys have experience with below issue, I got stuck with it for a day, and still don't know how to fix. Please help me :). 
>>> _**I think it does not understand `ES6 syntax` on `server side`**_

**Before add `babel-loader` config to `config.babel.js`, I got below error**
![image](https://user-images.githubusercontent.com/23022945/63858164-39675f80-c9cf-11e9-8c1a-c5b51fed2106.png)

**After add this configuration to `config.babel.js`, I solved this error**
![image](https://user-images.githubusercontent.com/23022945/63858225-56039780-c9cf-11e9-82a1-2c632440dab6.png)

**but still remain below error:**
![image](https://user-images.githubusercontent.com/23022945/63858012-f1e0d380-c9ce-11e9-8471-e373b459a9da.png)

**Error details:**
> /working/source/examples/react-cool-starter/node_modules/@ansarada/ace-react/dist/ace/components/index.js:4
> import * as editor from './Editor';
>        ^
> 
> SyntaxError: Unexpected token *
>     at Module._compile (internal/modules/cjs/loader.js:723:23)
>     at Module._compile (/working/source/examples/react-cool-starter/node_modules/pirates/lib/index.js:99:24)
>     at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Object.newLoader [as .js] (/working/source/examples/react-cool-starter/node_modules/pirates/lib/index.js:104:7)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (/working/source/examples/react-cool-starter/src/pages/Home/Home.js:6:1)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Module._compile (/working/source/examples/react-cool-starter/node_modules/pirates/lib/index.js:99:24)
>     at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Object.newLoader [as .js] (/working/source/examples/react-cool-starter/node_modules/pirates/lib/index.js:104:7)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at Object.requireSync (/working/source/examples/react-cool-starter/src/pages/Home/index.js:6:14)
>     at InnerLoadable.loadSync (/working/source/examples/react-cool-starter/node_modules/@loadable/component/dist/loadable.cjs.js:188:35)
>     at new InnerLoadable (/working/source/examples/react-cool-starter/node_modules/@loadable/component/dist/loadable.cjs.js:128:17)
>     at processChild (/working/source/examples/react-cool-starter/node_modules/react-dom/cjs/react-dom-server.node.development.js:2846:14)
> ==> 😭  Rendering routes error: SyntaxError: Unexpected token *
> GET / 404 14429.555 ms - 12

**Content of the `component which cause issue`**
![image](https://user-images.githubusercontent.com/23022945/63851011-8e9b7500-c9bf-11e9-8f63-d900cbee143f.png)

**The line which cause issue**
![image](https://user-images.githubusercontent.com/23022945/63851160-e043ff80-c9bf-11e9-9a80-f40ef21fd2ad.png)

Thank you so much.

**Comment by Rid** [comment]
@hienhuynhtm can you let us know the command you're running when you get this error?

i.e. yarn dev or yarn build && yarn start

**Comment by hienhuynhtm** [comment]
@Rid I got error when run `yarn dev`

**Comment by hienhuynhtm** [comment]
@Rid I updated the `error details` for more clearer

**Comment by Rid** [comment]
Please confirm that your package.json contains:

```
"babel": {
    "presets": [
      [
        "@babel/preset-env",
        {
          "useBuiltIns": "usage",
          "corejs": "3.0.0"
        }
      ],
      "@babel/preset-react",
      "@babel/preset-flow"
    ],
    "plugins": [
      "react-hot-loader/babel",
      "@loadable/babel-plugin",
      "@babel/plugin-proposal-class-properties",
      "@babel/plugin-syntax-dynamic-import"
    ],
    "env": {
      "production": {
        "plugins": [
          "transform-remove-console",
          "transform-react-remove-prop-types"
        ]
      }
    }
  },
```

Do you have a link to the repository you're working from?

**Comment by hienhuynhtm** [comment]
@Rid yes, my `babel` config on package.json, I don't change it:

![image](https://user-images.githubusercontent.com/23022945/63904989-f93ec600-ca3c-11e9-83c4-05ee7e9bf33f.png)


I'll upload my repo to github, but the problem: the `package cause ES6 problem is private`.
This one: "@ansarada/ace-react": "^13.6.0",

**Comment by hienhuynhtm** [comment]
@Rid here my repository: https://github.com/hienhuynhtm/react-cool-starter
note: I included node_modules too, then you can run easily.

1. I add babel.config.js to solve some problems
![image](https://user-images.githubusercontent.com/23022945/63905647-15436700-ca3f-11e9-9698-5c66e77672d7.png)
2. I add this `babel-loader` to config.babel.js too
![image](https://user-images.githubusercontent.com/23022945/63905695-33a96280-ca3f-11e9-952b-d5a5ecc2b582.png)

**Comment by hienhuynhtm** [comment]
@Rid how about `pirates` for `hooks`: https://github.com/nesterow/pirates-examle ?

**Comment by hienhuynhtm** [comment]
I solved it, with `pirates hook`.
Details:

```
const { addHook } = require('pirates');
const { transform } = require('@babel/core');

function matcher(filename) {
  if (
// condition here
  ) {
    return false;
  }
  return true;
}

module.exports = options =>
  addHook(
    function(source) {
      return transform(source, {
        presets: [
          [
            '@babel/preset-env',
            {
              modules: 'cjs',
              targets: {
                node: process.versions.node
              }
            }
          ]
        ]
      }).code;
    },
    {
      exts: ['.js'],
      ignoreNodeModules: false,
      matcher,
      ...options
    }
  );
```

**Comment by hienhuynhtm** [comment]
@Rid thank you so much for your kind support <3
