### ISSUE TITLE
Server for production

### ISSUE THREAD

**Issue by jabacchetta** [wellyshen/react-cool-starter#24]
In reference to #10 , there's a basic [solution offered here](https://github.com/babel/example-node-server) (towards the bottom) that might help.

**Comment by wellyshen** [comment]
Hi @jabacchetta I have created a repo for server side bundle of this starter kit, feel free to [check it](https://github.com/wellyshen/react-cool-starter/tree/server_bundle)

**Comment by jabacchetta** [comment]
Perfect, thanks!

**Comment by TotallWAR** [comment]
Probably this issue is not the best place where i can ask you but why do i need all of the components and helpers in production version? I thought that i need only assets and server because everything is bundled, didn't i?

**Comment by wellyshen** [comment]
@TotallWAR Server-side runtime need those files.
