### ISSUE TITLE
How can create a separate server bundle?

### ISSUE THREAD

**Issue by redlinecodes** [wellyshen/react-cool-starter#240]
This starter is Awesome, really nice work!

My only wish is that the server was packaged in a separate bundle so that I can put some api keys in there. So basically I would have all the separate chunks for client side code and then one bundle for the server - so that I can put sensitive info in there (api keys).

I see that basically the server runs with require('server') in the src/index file and that nodemon is watching it.

I'm trying to wrap my head around how I can use Webpack to do this - 
Would I need to start a second instance of webpack for the server  - any ideas or suggestions?

**Comment by wellyshen** [comment]
@redlinecodes If you want to optimize the boosting of your web app by server-side bundle, you need to do:
- Create server-side webpack config
- Adjust script command to access the bundled server-side file in production

There're many resources of SSR bundled that you can find on internet such as this [one](https://medium.com/@christossotiriou/speed-up-nodejs-server-side-development-with-webpack-4-hmr-8b99a932bdda)

This is not an issue, so I close it but feel free to discuss with me if you have question.

**Comment by redlinecodes** [comment]
@wellyshen - thanks! Again, really nice work - its clean and simple :)

**Comment by redlinecodes** [comment]
@wellyshen - 1 more quick question. Is the /src/tools/webpack/hooks.js file - is that all the css processing for the server side? All that would need to be included in a webpack config for a server-side bundle?

**Comment by wellyshen** [comment]
@redlinecodes It's assets runtime bundler for SSR. I think them already in the webpack config. If you bundle SSR for production. You can skip the `hook.js` by env.
