### ISSUE TITLE
How to add static files to public folder?

### ISSUE THREAD

**Issue by hienhuynhtm** [wellyshen/react-cool-starter#242]
Hi guys,
I'm trying to add `manifest.json` & `service-worker.js` to allow `PWA` feature. Below are my steps:

1. in `renderHtml.js`, I'm trying to add those lines
`<link rel="manifest" href="/manifest.json">`

2. I added 2 files to public folder:
![image](https://user-images.githubusercontent.com/23022945/66265171-e8ebe900-e83b-11e9-9af6-799f0a66ce75.png)

>>> But it always got `404` for those files:
![image](https://user-images.githubusercontent.com/23022945/66265208-ab3b9000-e83c-11e9-87f0-05d997a52cc6.png)
![Uploading image.png…]()

Which steps I missed to achieve it?

**Comment by wellyshen** [comment]
@hienhuynhtm Interesting issue. I will find time to configure out how to achieve it 👍

**Comment by denny64** [comment]
@hienhuynhtm paths for files in the public folder aren't resolved in DEV mode. See this -> https://github.com/wellyshen/react-cool-starter/blob/master/src/server.tsx#L37

You can change that logic so it works locally as well.

**Comment by denny64** [comment]
@wellyshen - We should probably expose the paths for all files in the public folder in dev. Should I do a PR?

**Comment by wellyshen** [comment]
@hienhuynhtm Sorry, I forget this issue. How's going on with this issue? BTW, many developers use [workbox](https://github.com/GoogleChrome/workbox) for PWA + SSR.

@denny64 Sure man, plz show it by a PR 👍

**Comment by wellyshen** [comment]
Close due to https://github.com/wellyshen/react-cool-starter/pull/309
