### ISSUE TITLE
How to deploy to AWS Beanstalk

### ISSUE THREAD

**Issue by redlinecodes** [wellyshen/react-cool-starter#243]
I'm used to putting my build files from create-react-app on S3 and connecting that to Cloudfront to deploy my SPAs. This is my first time with an SSR app...

I know I need to deploy on Beanstalk because I need the express server... other than that I'm not sure what to do after I run yarn build and where to put those files? Any help would be great!!

**Comment by wellyshen** [comment]
@redlinecodes I'll write a document on README tomorrow.

**Comment by wellyshen** [comment]
@redlinecodes You can refer [here](https://github.com/wellyshen/react-cool-starter#how-to-deploy)

**Comment by redlinecodes** [comment]
@wellyshen Awesome! Thanks :)
