### ISSUE TITLE
No map file for production level

### ISSUE THREAD

**Issue by amerllica** [wellyshen/react-cool-starter#247]
### No map file needed for production level (feature)

- For the production level, there is no need to have `map` files because downloading and parsing and mapping them have a large cost for clients browsers, especially for mobile devices.

### Expected Behavior

For production, the project shouldn't generate `map` files for JavaScript and CSS bundles. this awesome starter should be very light in production running.

### Actual Behavior

All map files are generated for the `yarn build` command.

### Your Environment

- Client OS: all
- Browser and its version: all
- Version of node: all

**Comment by wellyshen** [comment]
@amerllica I agree.

**Comment by amerllica** [comment]
Thanks, dear @wellyshen, I leave a separate PR for each issue. after your code review and accepting we have them on our lovely starter.

**Comment by wellyshen** [comment]
Close due to https://github.com/wellyshen/react-cool-starter/pull/248#issuecomment-547467987
