### ISSUE TITLE
Omit comments from CSS bundle file

### ISSUE THREAD

**Issue by amerllica** [wellyshen/react-cool-starter#249]
### The bundled CSS files shouldn't include comments (feature)

- In the production version, there is no need to see comments on the CSS bundled files.

### Expected Behavior

No existing comments on CSS bundled files.

### Actual Behavior

After the production build, there are many comments on the CSS bundled file.

### Your Environment

- Client OS: all
- Browser and its version: all
- Version of node: all

**Comment by amerllica** [comment]
Dear @wellyshen, It's very weird to me. the `normalize.css` have comments on its CSS but why? even I don't know where the `normalize.css` file come from?

**Comment by wellyshen** [comment]
@amerllica Is [that] (https://github.com/wellyshen/react-cool-starter/blob/master/src/app/index.tsx#L9) you are looking for?

**Comment by amerllica** [comment]
Thanks for your guide. Dear @wellyshen, If you're agreed, I wanna omit `normalize.css` from its place and complete the theme folder, then I will place the `normalize.css` in the theme folder. maybe a developer wanna use `reset.css`.

**Comment by wellyshen** [comment]
@amerllica Sure go ahead.
