### ISSUE TITLE
Uglify JavaScript bundled file

### ISSUE THREAD

**Issue by amerllica** [wellyshen/react-cool-starter#251]
### Uglify JavaScript bundled file to have more compressed bundles.

- For the production build, we should have the most compressed JavaScript bundled files. with uglifying, we could build it better.

### Expected Behavior

More ugly bundles to have more compressed bundles.

### Actual Behavior

The bundles' compression does not satisfy me.

### Your Environment

- Client OS: all
- Browser and its version: all
- Version of node: all

**Comment by wellyshen** [comment]
@amerllica Can you help with this issue?

**Comment by amerllica** [comment]
Dear @wellyshen, I sent `PR`s for all of my issues. Please check the PR tab.

**Comment by wellyshen** [comment]
@amerllica Nice job bro! I'll review the PR ASAP (I am going to gym now), thanks!

**Comment by wellyshen** [comment]
@amerllica Close due to https://github.com/wellyshen/react-cool-starter/pull/252#issuecomment-547465741
