### ISSUE TITLE
Involving .env and environment variables

### ISSUE THREAD

**Issue by amerllica** [wellyshen/react-cool-starter#253]
### Involving .env and environment variables (feature)

- Actually, all of us know, some config variables are a detached concept from our projects. like the main API URL of endpoints. or like the main PORT of production running or etc. it means after a build when we deliver the product to the DevOps team, they should just run it, with their desired API URLs or their own PORTs. these config variables are not part of our production build. these are part of our project running. so we should separate them. I proffer to use `.env` file in our _development_ area and for production, we will tell DevOps team to set config variables in their environment. because without an environment our build doesn't run. Also, we don't push `.env` file. we just leave and `.env.example` file about config variables and it is DevOps duty to set them in their environment.

### Expected Behavior

When we use `process.env.API_URL` in our project, it passed the `API_URL` variable of `.env` or environment variable. 

### Actual Behavior

But it passed `undefined`.

### Your Environment

- Client OS: all
- Browser and its version: all
- Version of node: all

**Comment by amerllica** [comment]
![image](https://user-images.githubusercontent.com/10472437/67633686-20dcce00-f8c8-11e9-8f41-d1e1d19e382c.png)

Due to the above picture, we see the `API_URL` is declared in the project file, it should declared in a way that the DevOps engineers will change it after developers build. it should come from the environment. something like below:

    // separated urls.ts file
    export const Urls = {
      users: '/users',
    };

    // separated fetches.ts file
    import Urls from '~/urls';

    const baseUrl = process.env.API_URL;

    export const Users = {
      get: axios.get(`${baseUrl}/${Urls.users}`),
    };

Or something like below:

    // separated urls.ts file
    const baseUrl = process.env.API_URL;

    export const Urls = {
      users: `${baseUrl}/users`,
    };

    // separated fetches.ts file
    import Urls from '~/urls';

    export const Users = {
      get: axios.get(Urls.users),
    };

Or even make an instance from `axios` and then set it up with `baseUrl` and use the export of the instance for calling APIs.

**Comment by amerllica** [comment]
Dear @wellyshen, why the Travis build fall into an error, it happens because of the env variable. I set a new Travis variable inside `.travis.yml` file, and push it again, but it doesn't fix.

**Comment by wellyshen** [comment]
Close due to https://github.com/wellyshen/react-cool-starter/pull/255#issuecomment-546859195
