### ISSUE TITLE
Why we don't put some build files inside git ignore?

### ISSUE THREAD

**Issue by amerllica** [wellyshen/react-cool-starter#254]
### Why we don't put some build files inside git ignore? (question)

- Why after each build, we have `loadable-stats.json` and `webpack-stats.json` file in the git tracker? Isn't better put them in the `.gitignore` file?

### Expected Behavior

Each build file should get ignore from the git tracker.

### Actual Behavior

But, for each builds the git tracker shows the `loadable-stats.json` and `webpack-stats.json` are changed.

#HINT: @wellyshen, If you are agreed, I will make a PR, this issue is just a question.

- Client OS: all
- Browser and its version: all
- Version of node: all

**Comment by wellyshen** [comment]
Fixed via [v3.2.2](https://github.com/wellyshen/react-cool-starter/releases/tag/v3.2.2)
