### ISSUE TITLE
Having trailing comma

### ISSUE THREAD

**Issue by amerllica** [wellyshen/react-cool-starter#256]
### Having trailing comma (feature)

- For code movement and replacement, the `trailing-comma` is a lovely feature.

### Expected Behavior

At the end of **multi-line** _Objects or Array_  we should have a trailing comma.

### Actual Behavior

We don't have it.

### Your Environment

- Client OS: all
- Browser and its version: all
- Version of node: all

**Comment by wellyshen** [comment]
Close due to https://github.com/wellyshen/react-cool-starter/pull/257#issuecomment-546778642
