### ISSUE TITLE
Do all containers have to have a fetchData method?

### ISSUE THREAD

**Issue by dianafaye17** [wellyshen/react-cool-starter#26]
Do all containers have to have a fetchData method?  In server.js, it looks like you are expecting every container to have a fetchData method if it wants access to "dispatch". What do I do for containers that don't need to fetch data but still need access to store.dispatch?

**Comment by dianafaye17** [comment]
My action.js code:

```
export const TOGGLING_DIV = 'TOGGLING_DIV';

const toggleMyDiv = () => {
  const { dispatch } = this.props;
  dispatch({ type: TOGGLING_DIV });
};

```
Errors:

```
  1:1  error  Prefer default export                             import/prefer-default-export
  3:7  error  'toggleMyDiv' is assigned a value but never used  no-unused-vars
```

**Comment by wellyshen** [comment]
@dianafaye17 

The `server.js` will find the static fetchData method from each container and do fetch data before rendering on client side. It means you don't need to have the fetchData method on every container, just use it when you need it.

If your container is wrapped by the connect of Redux, e.g. `export default connect(mapStateToProps)(Home);` then the dispatch will be a prop of the container, therefore you can use it like this: 

```javascript
  componentDidMount() {
    const { dispatch } = this.props;

    // Fetching data for client side rendering
    Home.fetchData(dispatch);
  }
```

**Comment by dianafaye17** [comment]
Thank you very much.
