### ISSUE TITLE
React router v4

### ISSUE THREAD

**Issue by maximusnikulin** [wellyshen/react-cool-starter#27]
Hi @wellyshen:) 
Do you have a plan to add react router v4 to your boilerplate?
It's really great solution for routing, but it has some disadvantages like unclear way for server side routing and async routes and reducers as well.
Thanks

**Comment by wellyshen** [comment]
Hey @maximusnikulin 
Yes, I will support React Router v4 in the future, I am waiting for the official document of the universal rendering :)

**Comment by wellyshen** [comment]
@maximusnikulin Hi, upgraded to React-Router v4 without missing any feature :)
