### ISSUE TITLE
Adding Material UI

### ISSUE THREAD

**Issue by redlinecodes** [wellyshen/react-cool-starter#273]
First I know this is NOT an issue with this great repo, I just need a little help integrating it. I can get the button to render as shown [here](https://material-ui.com/getting-started/usage/), however, it displays without any styles.

I believe I followed their integration guide and adjusted where necessary for react cool starter:
In client.js
`// added for Material UI
import CssBaseline from '@material-ui/core/CssBaseline';
import { ThemeProvider } from '@material-ui/core/styles';
import theme from './theme/sitetheme';
...
const render = (Routes: Array<Object>) => {
  const renderMethod = module.hot ? ReactDOM.render : ReactDOM.hydrate;

  React.useEffect(() => {
      const jssStyles = document.getElementById('#jss-server-side');
      if (jssStyles) {
        jssStyles.parentElement.removeChild(jssStyles);
      }
  }, []),

  renderMethod(

    <ThemeProvider theme={theme}>
      <CssBaseline />
    <AppContainer>
      <Provider store={store}>
        <ConnectedRouter history={history}>
          {renderRoutes(Routes)}
        </ConnectedRouter>
      </Provider>
    </AppContainer>
    </ThemeProvider>,
    // $FlowFixMe: isn't an issue
    document.getElementById('react-view')
  );
};
`

And then in server.js
`// added for Material UI
import CssBaseline from '@material-ui/core/CssBaseline';
import { ServerStyleSheets, ThemeProvider } from '@material-ui/core/styles';
import theme from './theme/sitetheme';
...
const extractor = new ChunkExtractor({ statsFile });
      const sheets = new ServerStyleSheets(); // added for material-ui
      const staticContext = {};
      const AppComponent = (
        sheets.collect(
        <ThemeProvider theme={theme}>
          <CssBaseline />
        <ChunkExtractorManager extractor={extractor}>
          <Provider store={store}>
            {/* Setup React-Router server-side rendering */}
            <StaticRouter location={req.path} context={staticContext}>
              {renderRoutes(routes)}
            </StaticRouter>
          </Provider>
        </ChunkExtractorManager>
        </ThemeProvider>
      ));

      const css = sheets.toString(); // for material ui
      const initialState = store.getState();
      const htmlContent = renderToString(AppComponent);

      // head must be placed after "renderToString"
      // see: https://github.com/nfl/react-helmet#server-usage
      const head = Helmet.renderStatic();

      // Check if the render result contains a redirect, if so we need to set
      // the specific status and redirect header and end the response
      if (staticContext.url) {
        res.status(301).setHeader('Location', staticContext.url);
        res.end();

        return;
      }

      // Check page status
      const status = staticContext.status === '404' ? 404 : 200;

      // Pass the route and initial state into html template
      res
        .status(status)
        .send(renderHtml(head, extractor, htmlContent, initialState, css));
`

and finally in renderHtml.js
`export default (
  head: Object,
  extractor: Function,
  htmlContent: string,
  initialState: Object,
  css: string // added for Material UI
...

        ${extractor.getLinkTags()}
        ${extractor.getStyleTags()}
        <style id="jss-server-side">${css}</style>
`
I'm not exactly sure what I'm doing wrong? I also posted this on [SO](https://stackoverflow.com/questions/59217293/adding-material-ui-to-react-ssr)

**Comment by wellyshen** [comment]
@redlinecodes I'll spend time to see it.

**Comment by wellyshen** [comment]
@redlinecodes I just follow the [doc](https://material-ui.com/guides/server-rendering/#server-rendering) then BOOM! You can follow this [branch](https://github.com/wellyshen/react-cool-starter/tree/example/material-ui) to integrate it.
 
<img width="857" alt="螢幕快照 2019-12-09 下午7 00 17" src="https://user-images.githubusercontent.com/21308003/70430809-8f5f9f00-1ab6-11ea-86ee-f0003a9f71db.png">

**Comment by redlinecodes** [comment]
@wellyshen Thanks, will do!
Update - your right, very easy - I was trying to do it real quick when I should have gone to bed and left it for the next day. Thanks for the help and keep up the great work with this bp!
