### ISSUE TITLE
Isomorphic Webpack

### ISSUE THREAD

**Issue by jabacchetta** [wellyshen/react-cool-starter#28]
Interesting [new isomorphic-webpack package here](https://github.com/gajus/isomorphic-webpack). Haven't had a chance to look at it yet — and not sure if it would be of any help with this boilerplate — but it claims to solve some of the pain points with webpack-isomorphic-tools.

**Comment by wellyshen** [comment]
Hey @jabacchetta It seems awesome, I will spend time to do some study about it, current I'm busying in study react-native for building an app lol, thanks dudde ;)

**Comment by wellyshen** [comment]
Keep use wepback-isomorphic-tools for now, because it's resource rich and the author fix bug very fast
