### ISSUE TITLE
Problem dispatching actions from different components

### ISSUE THREAD

**Issue by nicolabortignon** [wellyshen/react-cool-starter#29]
First of all,
thankyou @wellyshen  for the great boilerplate.

I have the following structure from a checkout of the boilerplate 5 days ago.

```
        /Tags/
             /index.js //component
             /reducer.js // the reducer for that component
             /actions.js // all the actions that can be performed by that component
       /Products/
             /index.js
             /reducer.js 
             /actions.js 
```

I'm trying to have a component connect to two reducers.

I use redux's connect and mapStateToProps in this way: 

 

  ```
  const mapStateToProps = state => (
      { products: state.get('products').products, tags: state.get('tags').tags }
    );
    
    export default connect(mapStateToProps)(Products);
```

Now, I'd like to dispatch from the very same component two actions.
One action is from the actions in the same component folder, and the other is from the folder in tags.
The name of the actions are unique. 
The actions are executed correctly and both try to update their own reducers with dispatch().
 The reducer of tags doesn't receive his own dispatch (it doesn't see it), while the reducer of Products, receives both.

I believe i'm doing a bit (lot) of confusion with the function dispatch that seams to be the same and coming from the component itself.
Actions that are dispatched from the Tags component are processed correctly by its reducer.

Any suggestion?

**Comment by wellyshen** [comment]
Hi @nicolabortignon

Actual the action can be use by any “container” component, you can see how I setup it through the `./src/containers/Home` and `./src/containers/UserInfo`. By the way, make sure you also setup the reducer properly through the async routes, you can refer the `./src/routes.js`.

**Comment by nicolabortignon** [comment]
Hi @wellyshen thank you for the answer,

what i'm trying to do is having two part of the store (state.tags, and state.product) available in the same component.


what I'm doing is:

1- in the component mapStateToProp for both:
`{ products: state.get('products').products, tags: state.get('tags').tags }` 

2- call both fetchData from the respective actions:

`
import * as action from './action';
import * as actionTags from './../Tags/action';

...

dispatch(action.fetchDataIfNeeded()),
dispatch(actionTags.fetchDataIfNeeded()),

  `

and in the routes.js I have the following declaration:

`{
        path: '/products',
        getComponent(nextState, cb) {
          const importModules = Promise.all([
            System.import('./containers/Products'),
            System.import('./containers/Products/reducer'),
            System.import('./containers/Tags/reducer'),
          ]);

          const renderRoute = loadModule(cb);

          importModules
            .then(([Component, reducer]) => {
              injectReducer(store, 'products', reducer.default);
              injectReducer(store, 'tags', reducer.default);
              renderRoute(Component);
            })
            .catch(errorLoading);
        },
      },
`

Am I doing something wrong?

the action called on the product action is captured correctly by its reducer, while the tag action is captured by the product reducer and not by the tag reducer.

**Comment by nicolabortignon** [comment]
Ok, so I had to rewrite the injection of the reducer in the router.js.

Not the most elegant but here it is: 

`{
        path: '/products',
        getComponent(nextState, cb) {
          const importModules = Promise.all([
            System.import('./containers/Products'),
            System.import('./containers/Products/reducer'),
            System.import('./containers/Tags/reducer'),
          ]);

          const renderRoute = loadModule(cb);

          importModules
            .then(([Component, ...reducers]) => {
              console.log('reducer');
              console.log(reducers);
              injectReducer(store, 'products', reducers[0].default);
              injectReducer(store, 'tags', reducers[1].default);
              renderRoute(Component);
            })
            .catch(errorLoading);
        },
      },
`

Ideally would be nice if the system.import can detect the name of the reducer, and the injectReducer calls is called on every element of the array reducers.. but oh well. for now at least it works :)

**Comment by wellyshen** [comment]
Hi @nicolabortignon I not quite sure what's the structure of your website, but I recommend you to combine these two reducers into one for the route of product, the code will be more elegant :)

**Comment by nicolabortignon** [comment]
I have been thinking about this a bit, 
I'm not 100% sure that having micro components with their own reducer is necessarily the most practical idea. 

I like the idea of encapsulating everything in one folder that represent component's view + model + controller in the react flavor of view + redux + action, but on the other hand is quite a unrealistic scenario.

I used couple of different boilerplates before, and they approach was to have 1 reducer shared by all the components, each component may add its own part to the main reducer as a concatenation.  As long as all the actions have different naming convention, that works.

**Comment by wellyshen** [comment]
@nicolabortignon Yea, everyone has their own preference for the project structure. I prefer to collect all the reducers into one for each route ;)

**Comment by nicolabortignon** [comment]
How would you implement a component that needs to access a reducer but don't have a route ?

**Comment by wellyshen** [comment]
@nicolabortignon 

Just pass the reducer as the prop from the top level container.

By the way if you have a container inside a container, then you also can access the reducer through the redux `connect` from the children container directly, because the reducer of the container already be injected while the route be injected :)
