### ISSUE TITLE
ReferenceError: initialState is not defined

### ISSUE THREAD

**Issue by devellopah** [wellyshen/react-cool-starter#3]
I am sorry for this, actually there is no error with your boilerplate. Let me explain.
I have cloned your boilerplate to use for my Recipebook(the app i am building in educational purposes in order to get solid understanding of redux ecosystem).
So i have changed boilerplate to fit my needs.
After that i run `npm run build` successfully.
And then i get error(screenshot below) on 'npm start'. 
I have created [Recipebook](https://github.com/dagman/Recipebook) repo where i have uploaded my code.
I know i asking for too much but i am eated my braines trying to figure this out.
Can you please check my repo and help me figure out how to fix this error.
Thanks in advance!
![recipebook error](https://cloud.githubusercontent.com/assets/13398931/18616992/43c34402-7dcf-11e6-9ab0-af6cd52ea7c6.png)

**Comment by wellyshen** [comment]
@dagman Let me check it first.

**Comment by wellyshen** [comment]
Yo @dagman,

It's because of your `configureStore.js` is requiring the initialState parameter but it can't be accessed. I have modified your code and sent a PR to you, please check it ;)

**Comment by isaadabbasi** [comment]
Quick Solution: 
This may not be the perfect solution but what i found it to be is way the node/test envs are reading the modules. 
replace const/let with var and replicate the object in param assignment.
![solution1](https://user-images.githubusercontent.com/15571610/50571421-8e64be80-0dcb-11e9-9264-b29d73f340c9.PNG)

**Comment by FablihaNahid** [comment]
![1](https://user-images.githubusercontent.com/49697751/167346679-2b114d4a-ee9d-41d8-92d5-c6f646c750ae.PNG)
![2](https://user-images.githubusercontent.com/49697751/167346686-66bdaa81-0529-483b-933e-994989ffa849.PNG)
 
I'm facing this error and unable to solve it. can you help me how can I resolve it?

**Comment by zack-ari** [comment]
> ![1](https://user-images.githubusercontent.com/49697751/167346679-2b114d4a-ee9d-41d8-92d5-c6f646c750ae.PNG) ![2](https://user-images.githubusercontent.com/49697751/167346686-66bdaa81-0529-483b-933e-994989ffa849.PNG)
> 
> I'm facing this error and unable to solve it. can you help me how can I resolve it?

Hi there, did you find a solution for this facing same error here

**Comment by nghianm93** [comment]
<img width="507" alt="image" src="https://user-images.githubusercontent.com/106898353/175871444-a452a65a-f958-464e-9a06-549ab4cda99f.png">
Try this.

**Comment by asif-code** [comment]
> 

It Works

**Comment by vectordotsats** [comment]
Thanks
