### ISSUE TITLE
Trying to deploy to AWS Elasticbeanstalk

### ISSUE THREAD

**Issue by redlinecodes** [wellyshen/react-cool-starter#310]
I'm following the instructions provided [here](https://github.com/wellyshen/react-cool-starter#how-to-deploy) and I keep getting this error in aws console:

Failed to find package.json. Node.js may have issues starting. Verify package.json is valid or place code in a file named server.js or app.js.

Do I need to rename the root index file to app.js or something else? Everything has worked fine up until this point.

**Comment by wellyshen** [comment]
@redlinecodes Did you pack the `package.json` file to the cloud?

**Comment by wellyshen** [comment]
Close due to inactive.
