### ISSUE TITLE
using css with this starter

### ISSUE THREAD

**Issue by beckmeindia** [wellyshen/react-cool-starter#32]
Hey,
  I saw the part in readme where it explains how to use css with the boilerplate.

Somehow in my case it is not importing the css modules.

What I am doing is, let's say we have a div which needs to be given some styling
In App,js
`<div className="left-half">
      <h1 className="o-header__title titledesk">Something</h1>
    </div>`

and in normalize.css

> .left-half{ color: red; width: 100%; height: 800px; background-color: #2bb1de; }

Should it be written in some other way?

**Comment by beckmeindia** [comment]
This seems to work, inside config.babel.js    module.exports / modules / rules

>       {        test: /\.css$/,
        loader: isDev ?
          'style-loader!css-loader'
          : ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: 'css-loader' }),
      },

I guess the problem was the test for .scss and .css were same

This should fix it. Any downsides @wellyshen

**Comment by wellyshen** [comment]
Hi @beckmeindia 

If you don't need to use CSS module just change the `CSSModules` variable to 'false' from the `./src/tools/webpack/config.babel.js` as below :
<img width="989" alt="2017-02-04 3 18 09" src="https://cloud.githubusercontent.com/assets/21308003/22616709/6a5225da-eaed-11e6-9fa5-27d29b076600.png">

Then import your css stylesheet into the `App.js`, then point your className to the css class which you have declared (here I declared the `App` and `header` class in my `.scss` file), here I use the scss as the example :
<img width="981" alt="2017-02-04 3 23 41" src="https://cloud.githubusercontent.com/assets/21308003/22616735/126a4f5e-eaee-11e6-879d-fd68026ba626.png">

**Comment by beckmeindia** [comment]
Oh great! Thanks a lot
