### ISSUE TITLE
Redirecting path: '*' to path: '/'

### ISSUE THREAD

**Issue by beckmeindia** [wellyshen/react-cool-starter#33]
I want to redirect all not found routes to the home link './'

What changes do I make in the routes.js file?

**Comment by wellyshen** [comment]
@beckmeindia You can adjust the `./src/routes.js` as below :
<img width="973" alt="2017-02-05 9 45 21" src="https://cloud.githubusercontent.com/assets/21308003/22626607/81190e5a-ebec-11e6-8aa6-e616e38f4780.png">

**Comment by beckmeindia** [comment]
Oh okay, yeah I tried that but had a confusion if have to inject reducer and etc. again or it will work because it is already injected earlier

**Comment by wellyshen** [comment]
@beckmeindia I think the reducer should be injected for the path "*" because someone may typing the unexpected URL, in that situation the home may not be launch at the first time.

**Comment by beckmeindia** [comment]
@wellyshen Thanks man, ryt.

Also wanted to ask you if you are available on gitter or something where we could communicate without creating a new issue every time :D

Thanks

**Comment by wellyshen** [comment]
@beckmeindia You can find me on my FB : Wei-Yu Shen

**Comment by beckmeindia** [comment]
Great, sent a request from Rahul Basu. 
Thanks

**Comment by wellyshen** [comment]
@beckmeindia Cool I found you there
