### ISSUE TITLE
Implementing dispatch(push('/locn')) with router

### ISSUE THREAD

**Issue by beckmeindia** [wellyshen/react-cool-starter#36]
How do I dispatch push on click or other actions through the router?

**Comment by samparmenter** [comment]
In redux/store.js add the following two lines to the imports at the top.

```Javascript
import { browserHistory } from 'react-router';
import { routerMiddleware } from 'react-router-redux';
```

Then in the middlewares array add:

```Javascript
routerMiddleware(browserHistory)
```

That should allow you to do the following via dispatch():

```Javascript
import { push } from 'react-router-redux';

this.props.dispatch(push('/mylocation'));
```

**Comment by beckmeindia** [comment]
Hey @samparmenter

Thanks for replying. I have tried that already and it keeps saying: cannot find push of undefined.

Let me know if you get the same problem and/or a workaround

Thanks

**Comment by samparmenter** [comment]
Have you imported it via 

```Javascript
import { push } from 'react-router-redux'
```

I was looking at implementing this recently and your post encouraged me to have a play. I have this working on my app currently by doing the steps above.

**Comment by beckmeindia** [comment]
@samparmenter 
Thanks man, it works now. I guess there was a problem with the function I was calling it from.

Thanks a lot!

**Comment by samparmenter** [comment]
No worries, glad to help!
