### ISSUE TITLE
Multiple Entries with Different Styles

### ISSUE THREAD

**Issue by yussinsharp** [wellyshen/react-cool-starter#38]
I am wanting to integrate some of the code that you have created here into my own stack to achieve a better development experience but I am running into a snag.

Your application assumes one entry, while mine has several. The reason for this is that we have different applications for different types of users (admin vs. customer etc.).

I know how to set up multiple entries with Javascript and that has gone well, but I can't figure out how to handle the SCSS files? In renderHtmlPage, it seems you loop over all compiled style assets and inject them in. In my use case, we wouldn't want the styles of other apps bleeding into eachother.

My webpack setup before was able to determine what CSS we brought in based on the entry but it seems that is not the case anymore. WIT is compiling all of them. So if I could get some advice or help on how to set up multiple 'views' or entries and have the style assets be dynamic based on the entry, that would be greatly appreciated!

P.S. I love the starter-kit!

**Comment by wellyshen** [comment]
@yussinsharp Maybe you can consider to remove the [extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin), then you can arrange your styles as I did in the dev environment.

**Comment by yussinsharp** [comment]
@wellyshen So you're saying that I must manually add the stylesheets to the renderHtmlPage?

**Comment by wellyshen** [comment]
@yussinsharp Yea, this is what I can suggest currently, because the "extract-text-webpack-plugin" is designed for one application (both admin and client will sharing a style, if we use it). But your case is special.

**Comment by wellyshen** [comment]
@yussinsharp I suggest you can ask it on [extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) repo, I did see any possible for multiple styles on the repo yet.

**Comment by yussinsharp** [comment]
Thanks @wellyshen, will do.
