### ISSUE TITLE
server is bundle into a single file in production mode

### ISSUE THREAD

**Issue by xwillmadeit** [wellyshen/react-cool-starter#41]
I am really confusing how to build server side node code for production，you are using webpack and bundle it all with a single server.js file which contains some react component code...

if it's true not to bundle server code...  if we should just use babel to compile our node code and compoinent code to es5 for production？

**Comment by wellyshen** [comment]
@xwillmadeit Runtime compiling is not a bad practice for production, please refer to https://github.com/babel/example-node-server/issues/13 for more detail. It's necessary to include the first page (react components) for server-side rendering then send to browser when the first page loaded.
