### ISSUE TITLE
As we know the difference between dependencies and devDependencies, Why dev packages are inside dependencies?

### ISSUE THREAD

**Issue by amerllica** [wellyshen/react-cool-starter#429]
Actually, my question is not about ReactJS programming, based on my question title, as we know the difference between dependencies and devDependencies, Why dev packages are inside dependencies?

```
  "dependencies": {
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/preset-env": "^7.8.4",
    "@babel/preset-react": "^7.8.3",
    "@babel/preset-typescript": "^7.8.3",
    "@babel/register": "^7.8.3",
    "@hot-loader/react-dom": "^16.11.0",
    "@loadable/babel-plugin": "^5.12.0",
    "@loadable/component": "^5.12.0",
    "@loadable/server": "^5.12.0",
```

It is part of a `package.json` of this repo, so why `@babel` plugins or `@babel/preset-env` exist inside **dependencies** part?

**Comment by wellyshen** [comment]
@amerllica Good question. Because these deps are being used in runtime (SSR). If some of them are not, maybe them should be moved into devDeps lol.

**Comment by amerllica** [comment]
@wellyshen, Thanks for your answer, but please keep this issue open, I wanna show some evidence about some of them which they should be moved to depDependencies.

**Comment by wellyshen** [comment]
@amerllica Thank you for your help bro. I am crazy busying now.

**Comment by wellyshen** [comment]
Close due to inactive.
