### ISSUE TITLE
Trouble deploying to Amazon Elastic Beanstalk

### ISSUE THREAD

**Issue by djtowns** [wellyshen/react-cool-starter#43]
Firstly I would like to say thanks, I tried many boiler plates to find a good SSR react template and this is by far the best and I now have a fully working website.

I have hit issues trying to deploy to AWS, I have added a local variable for NODE_ENV = production and changed the EB start command to 'node ./index.js' then built the project and deployed to EB.

It fails with unable to find webpack-isomorphic-tools which is required in index.js but is in dev-dependencies in the package.json?  I tried moving to dependencies  but then just get 'waiting for the first webpack build to finish' continuously and a 502 error from the page?

Any idea what I am doing wrong, do I need to move any other packages up to dependencies for this to run in AWS, the 'yarn start:production' works fine on my local machine, but there I obviously have all of the packages anyway?

Again, thanks for a great boiler plate

**Comment by wellyshen** [comment]
@djtowns Try to upload all the available packages which are imported from server and client side. And don't forget to upload the "webpack-assets.json" file, which is created by the "webpack-isomorphic-tools" to your host.

**Comment by djtowns** [comment]
You are a genius, prompted me to check the uploaded package on S3, my mistake was I had not created a .ebignore file, so it was using the .gitignore file and not uploading anything in build! All working now, genius 😊

**Comment by wellyshen** [comment]
@djtowns Congrates buddy:)
