### ISSUE TITLE
Update to use "universal-webpack" instead of "webpack-universal-tools"

### ISSUE THREAD

**Issue by narin** [wellyshen/react-cool-starter#45]
Looks like the author has deprecated `webpack-universal` tools and replaced it with `universal-webpack`.  With this project, "`yarn add` fails with `Couldn't find package "webpack-universal-tools" on the "npm" registry.` any time you try to add a new package.

**Comment by wellyshen** [comment]
@narin I run `yarn add webpack-isomorphic-tools` it goes well, are you sure you install the right package? Seems it's still working and the author is using it, try [here].(https://github.com/halt-hammerzeit/webpack-isomorphic-tools)

<img width="620" alt="2017-03-28 9 03 33" src="https://cloud.githubusercontent.com/assets/21308003/24406166/1776b3a4-13fa-11e7-9388-aecb2daa5266.png">
