### ISSUE TITLE
index.html ?

### ISSUE THREAD

**Issue by msimonc** [wellyshen/react-cool-starter#46]
I already have an api server and so would adapt your **awesome** project to it as a front end,
I'll just: yarn build:client

Q: Could you please create an index.html file?  

Thanks mate from Sydney

**Comment by wellyshen** [comment]
@msimonc The main feature of this starter kit is "universal rendering". All the html configuration was designed for the purpose, if you just want a client side solution, I will recommend you give [create-react-app](https://github.com/facebookincubator/create-react-app) a try ;)

**Comment by msimonc** [comment]
Thanks but create-react-app doesn't provide the react-router4 / webpack2 / code splitting combination that yours does, which is rare ATM.  Universal Rendering is great but many front end apps already have a back end so don't need it.  Cheers,

**Comment by wellyshen** [comment]
@msimonc OK, I will consider your suggestion, but I need time to do adjust and release a client side only repo.

**Comment by msimonc** [comment]
Good.  I'll be working on it too.  

Have a look in Github yourself, but AFAIK your project is a leader in those techs ATM.
