### ISSUE TITLE
Rendering routes error: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by igor-lemon** [wellyshen/react-cool-starter#47]
Sometime I have an error.

==> 😭  Rendering routes error: TypeError: Converting circular structure to JSON
GET / 404 1294.641 ms - 12

I don't know any relations and how to reproduce that error. Sometime I can start app and app works well and after I can restart server and have the error. Very strange. Because I didn't change any code. Run clear:all command doesn't help. But after reboot a server the app can works corrects.

**Comment by wellyshen** [comment]
@igor-lemon Did you try the latest commit repo?

**Comment by wellyshen** [comment]
@igor-lemon The error was I designed to inform the developer that there's a wrong url from server side. For example if you type an url : "http://localhost:3000/UserInfo/100", we don't the data of "100", there're we throw an error and direct user to the "Not Found Page". You can handle it in your `UserInfo` component for better experience, here's the code to show how it be handled on server-side :

<img width="731" alt="2017-04-03 10 54 59" src="https://cloud.githubusercontent.com/assets/21308003/24615394/b1f728a8-18c0-11e7-9b2b-215d979d2137.png">

**Comment by igor-lemon** [comment]
Huh. I tried to find that error by text in code but didn't find anything.
Thx.

**Comment by wellyshen** [comment]
@igor-lemon, The `TypeError: Converting circular structure to JSON` was generated by the error catch of promise.
