### ISSUE TITLE
Add bootstrap css 

### ISSUE THREAD

**Issue by lgarro** [wellyshen/react-cool-starter#48]
Hi,

First of all thanks for a great starter. I was having some problems trying to add bootstrap to the starter. I tried several ways .

1. Require the bootstrap.css at Html.js
2. Import the style , in general styles import section at App/index.js
3. Tried adding react-bootstrap(Compos work , but still import still fails ) 

The above methods always throw me an error with the fonts loader: woff -woff2-eot-svg etc. It saids it can not find the "file-loader". Given this I tried playing with the loaders order but still didnt work.

Any idea to get this working, thanks

**Comment by lgarro** [comment]
actually looking in old issues, found the answer. Just needed to disable css modules, is this  correct ?

**Comment by wellyshen** [comment]
Hi @lgarro I'd recommend you import the Bootstrap in the `./src/App/index.js` file. Yes, you're right just disable the CSS modules then you can use Bootstrap as normal css class :)
