### ISSUE TITLE
SSR render components without data

### ISSUE THREAD

**Issue by Alex-Ferreli** [wellyshen/react-cool-starter#50]
Hi! Thanks for the awesome starter.

When the server render the HTML server side, i didn't have the state:
```
const routerContext = {};
let htmlContent = renderToString(
	<Provider store={store}>
		<StaticRouter location={req.url} context={routerContext}>
			<App />
		</StaticRouter>
	</Provider>,
);
```

and i return the HTML with the initial state of all the containers. When the client try to render in the same div to reuse the generated HTML, React warn me that the generated HTML is different (i render with `window.__INITIAL_STATE__`).

Should i do render after loaded the data from the component load? If I do it, i do multiple render, because the first is needed for redirect:
```
// Check if the render result contains a redirect, if so we need to set
// the specific status and redirect header and end the response
if (routerContext.url) {
	ctx.status = 301;
	ctx.redirect(routerContext.url);
	ctx.body = '';
	return;
}
```

so i need to do it before the data is loaded.

Thanks in advance

**Comment by wellyshen** [comment]
@Alex-Ferreli Does it occur in the production environment?

**Comment by Alex-Ferreli** [comment]
@wellyshen in development. The only thing that i do, was removing webpack-isomorphic-tool and some other stuff. But if you try it, you will see it. If you render to check redirects, you didn't have load the data in the store yet, but you pass the htmlcontent as parameter  to render the app. You must re-render the app with new data loaded. It's an issue to render 2 time?

**Comment by wellyshen** [comment]
@Alex-Ferreli For SSR you should not remove the "webpack-isomorphic-tools" or the style and javascript assets won't be available.

**Comment by Alex-Ferreli** [comment]
@wellyshen ok, i will insert it again. But if i remove all the styles and link bundle.js it should work anyway. `webpack-isomorphic-tools` didn't revolve this issue, because i need to `renderToStatic` 1 time to check for `Redirect`s and another time to render with data loaded from component.

**Comment by wellyshen** [comment]
@Alex-Ferreli Can you give me an example?

**Comment by wellyshen** [comment]
@Alex-Ferreli I have fixed some problem about SSR, maybe you can try the latest to see if your problem still exist.

**Comment by Alex-Ferreli** [comment]
@wellyshen Sorry for no example. Thank you now seems working!
