### ISSUE TITLE
Browser History not working when going back on same route

### ISSUE THREAD

**Issue by kmrigendra** [wellyshen/react-cool-starter#508]
Hi Team,

I'm facing issues in the re-rendering the same component on searchParam change.
I'm using componentDidUpdate in the view but getting below issue:

Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

Could you please help me out?

**Comment by wellyshen** [comment]
@kmrigendra Did you set state in `componentDidUpdate`?

**Comment by wellyshen** [comment]
Close due to the root cause of this issue pretty obvious.
