### ISSUE TITLE
Issue with programmatically changing routes

### ISSUE THREAD

**Issue by danyim** [wellyshen/react-cool-starter#51]
First off, thanks for creating a clean and well-documented starter app. We are in the process of migrating our existing code to use the tools provided here.

We are running into an issue with React Router v4 when trying to navigate to another route programmatically via `push`. At first we tried `history.push(...)`, but that gave us errors saying `push` was undefined.

After looking through the issues, we found a thread that's relevant: #36. I think the issue was made before the full React Router v4 implementation was made to the boilerplate, but we went ahead with attempting the solution anyway. We added this to a connected component:

```
import { push } from 'react-router-redux'
...
const mapDispatchToProps = (dispatch) => {
  return {
    push: v => dispatch(push(v)),
    ...
  }
};
```

And tried changing routes via
```
this.props.push('/newroute')
```

Although the browser's URL bar changes location, but the page does not update. Can anyone tell me what's missing here?

---

### Steps to reproduce:
1. Replace `./src/containers/Home/index.js` with the following:
```
/* eslint-disable react/sort-comp */
/* @flow */

import React, { PureComponent } from 'react';
import { connect } from 'react-redux';
import type { Connector } from 'react-redux';
import Helmet from 'react-helmet';
import { push } from 'react-router-redux';

import * as action from './action';
import type { Home as HomeType, Dispatch, Reducer } from '../../types';
import UserList from '../../components/UserList';
import styles from './styles.scss';

type Props = {
  home: HomeType,
  fetchUsersIfNeeded: () => void,
  push: () => void,
};

// Export this for unit testing more easily
export class Home extends PureComponent {
  props: Props;

  static defaultProps: {
    home: {
      readyStatus: 'USERS_INVALID',
      list: null,
    },
    fetchUsersIfNeeded: () => {},
  };

  componentDidMount() {
    this.props.fetchUsersIfNeeded();
  }

  renderUserList = () => {
    const { home } = this.props;

    if (!home.readyStatus || home.readyStatus === action.USERS_INVALID ||
      home.readyStatus === action.USERS_REQUESTING) {
      return <p>Loading...</p>;
    }

    if (home.readyStatus === action.USERS_FAILURE) {
      return <p>Oops, Failed to load list!</p>;
    }

    return <UserList list={home.list} />;
  }

  render() {
    return (
      <div className={styles.Home}>
        <Helmet title="Home" />
        {this.renderUserList()}
        <button onClick={() => this.props.push('/UserInfo/6')}>Click this button</button>
      </div>
    );
  }
}

const connector: Connector<{}, Props> = connect(
  ({ home }: Reducer) => ({ home }),
  (dispatch: Dispatch) => ({
    fetchUsersIfNeeded: () => dispatch(action.fetchUsersIfNeeded()),
    push: a => dispatch(push(a)),
  }),
);

export default connector(Home);
```
2. Run the project and click the "Click this button"
3. URL will change but the component won't update

**Comment by wellyshen** [comment]
@danyim, See if [it](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md) can help you

**Comment by danyim** [comment]
Thank you. I ran across that article and [also this one](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md), but it still didn't help.

If you add the following in the example I provided above:
```
import { withRouter } from 'react-router-dom';
...
export default withRouter(connector(Home));
```

It still has the same effect where the browser's URL changes but the component does not render properly.

**Comment by wellyshen** [comment]
@danyim I have tried it and it also can't work for me, maybe it's a bug. I saw you asked on the repo of React-Router, I'm also waiting for the response from the author.

**Comment by danyim** [comment]
Figured it out. The `BrowserRouter` needs to be wrapped with `withRouter` so that the location gets passed down to its children.

In `./src/client.js` change:
```js
const renderApp = () => {
  const App = require('./containers/App').default;
  render(
    <AppContainer>
      <Provider store={store}>
        <ConnectedRouter history={history}>
          <BrowserRouter>
            <App />
          </BrowserRouter>
        </ConnectedRouter>

      </Provider>
    </AppContainer>,
    mountNode,
  );
};
```

to
```js
const renderApp = () => {
  const App = require('./containers/App').default;
  const nonBlockingRouter = withRouter(BrowserRouter);

  render(
    <AppContainer>
      <Provider store={store}>
        <ConnectedRouter history={history}>
          <nonBlockingRouter>
            <App />
          </nonBlockingRouter>
        </ConnectedRouter>

      </Provider>
    </AppContainer>,
    mountNode,
  );
};
```


One thing I can't figure out is why this doesn't work when the variable name is capitalized. Try naming the const to `NonBlockingRouter` for instance.

**Comment by wellyshen** [comment]
@danyim Thanks man, it really help me :)

**Comment by wellyshen** [comment]
@danyim 

I think another simple way to fix the problem is remove the `BrowserRouter`, you can see my latest commit for more detail :)

If any chance please help to verify if this change will occur other side-effects, thanks.

**Comment by danyim** [comment]
I was wondering about the specific motivation for that router structure. Was there a specific example from the react-router v4 docs that nested a `<BrowserRouter>` inside a `<ConnectedRouter>`?

**Comment by wellyshen** [comment]
@danyim 

I saw the [doc](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux#usage) to set up the react-router-redux with RR4.

I think the `BrowserRouter` can be instead by `ConnectedRouter`, but I am still waiting for the validation from author by this [issue](https://github.com/ReactTraining/react-router/issues/4961).

**Comment by wellyshen** [comment]
@danyim Both `BrowserRouter` and `ConnectedRouter` are based on the router of RR4, therefore we just need to implement the `ConnectedRouter` for react-router-redux with RR4, see [here](https://github.com/ReactTraining/react-router/issues/4961) for the detail explain.

**Comment by danyim** [comment]
Great. Thanks for fixing and maintaining this boilerplate!
