### ISSUE TITLE
SSR not working correctly

### ISSUE THREAD

**Issue by MartinCerny-awin** [wellyshen/react-cool-starter#52]
It doesn't do SSR for me. I have changed __DISABLE_SSR__ global variable to false, but when I turn off JavaScript or open source code it doesn't show expected content.

**Comment by wellyshen** [comment]
@MartinCerny-awin

SSR doesn't means it can run with `.js` disabled , I guess you misunderstanding about it.

If SSR doesn't work, you won't see the data is presented on the "source code" window. Take this starter as the example, you can see the "user lists" data is presented on the "source code" window. 

You can set the "DISABLE_SSR" to `true` to see what's different between SSR enabled and SSR disabled.

**Comment by MartinCerny-awin** [comment]
I think that mine understanding of SSR is correct. Every article that I found describes it in this way: 
> Once the request is done processing, your browser gets back the fully rendered HTML and displays it on the screen. 
[Source](https://medium.freecodecamp.com/what-exactly-is-client-side-rendering-and-hows-it-different-from-server-side-rendering-bd5c786b340d)

The last project that I did using react doesn't need JavaScript on the client to render the content. You can also view HTML elements when you go to the source code. You can try it [here](https://www.findoc.co.uk)

I do not think that this repository has correct implementation of SSR.

**Comment by wellyshen** [comment]
@MartinCerny-awin Yea, I got your point. I will check it, thanks.

**Comment by wellyshen** [comment]
Hi @MartinCerny-awin It's just a little bug. I already fixed it, please help to verify it.

**Comment by MartinCerny-awin** [comment]
It works perfectly now

**Comment by wellyshen** [comment]
@MartinCerny-awin Thanks man ;)
