### ISSUE TITLE
2 warnings

### ISSUE THREAD

**Issue by oskarleonard** [wellyshen/react-cool-starter#53]
Im getting 2 warnings when running the app. 

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <div class="styles__App-2nmMK" d
 (server) <div class="_2nmMK" data-reactro

**Comment by wellyshen** [comment]
Hi @wayweary 

The first warning has been fixed by the last commit.
For the second warning, which means the rendering result are different between client and server. It usually occur in development environment. You can re-start the server to solve it.
