### ISSUE TITLE
Cannot find module '@loadable/babel-plugin' in production

### ISSUE THREAD

**Issue by mehrdad-masoumi** [wellyshen/react-cool-starter#535]
after this step
yarn build                  # Building bundle
rm -rf node_modules         # After building remove node modules
yarn install --production   # Then install dependencies only

yarn start error in windows and linux
![Capture](https://user-images.githubusercontent.com/8133819/78835349-489e9900-7a05-11ea-8e08-dff85e1f3840.JPG)

**Comment by mehrdad-masoumi** [comment]
@wellyshen

**Comment by wellyshen** [comment]
@mehrdad517 Did you install the `@loadable/babel-plugin` as dependency rather than devDependencies?

**Comment by mehrdad-masoumi** [comment]
yes.
 i'm using flow branch

**Comment by wellyshen** [comment]
@mehrdad517 The package is in devDependencies. You need to move it (and all the runtime related packages) from devDepednecies to dependencies. BTW, try to use master branch if you can. Flow branch isn’t maintained anymore.
