### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by m0rdreck** [wellyshen/react-cool-starter#54]
Hi,

Thank for your work, i have one problem's if it's one i'm not sure.

When i create new components, i create js and scss file hot reload relaunch the browser and he don't find the scss file.

I need to relaunch build cmd.

Thank you for help.

**Comment by m0rdreck** [comment]
Other error with scss

Error: Failed because of a stylelint error.

    at linterSuccess (node_modules\stylelint-webpack-plugin\lib\run-compilation.js:32:14)

After hot reload stop working.

**Comment by wellyshen** [comment]
@m0rdreck 

I use the [stylelint](https://github.com/stylelint/stylelint) in the webpack config for terminating bundling once there's a wrong style format. You can disable it through this [doc](https://github.com/wellyshen/react-cool-starter#javascript-and-style-lint) or see the [repo](https://github.com/stylelint/stylelint) for more detail.

For the `.scss` error can you show me the error message?

**Comment by m0rdreck** [comment]
Hi yes i see stylelint.

But if i write error, console say at linterSuccess (node_modules\stylelint-webpack-plugin\lib\run-compilation.js:32:14)

After i can correct this error all is crash and don't move.

I need to relaunch cmd yarn start for see changement.

I'm on windows 10.

**Comment by wellyshen** [comment]
@m0rdreck I think it's because of the `failOnError` breaks the build process, you can turn off it for making hot reloading works, see this [doc](https://github.com/JaKXz/stylelint-webpack-plugin#options) for more detail.

**Comment by m0rdreck** [comment]
ok thank for help i begin with webpack not simple 👍 

Just turn styleint = false in config.js solve problem's
