### ISSUE TITLE
Accessing the store [Question]

### ISSUE THREAD

**Issue by lgarro** [wellyshen/react-cool-starter#55]
I was trying to access the store that is passed down to html.js from the server.js. First I tried the same approach wih the Connector and passing down the reducer in the connect. But the value for my reducer is always undefined. Is the dispatch part required ? from what I understand I can send connect like this: 

```
const mapStateToProps = ({ tracker }: Reducer) => ({ tracker });

const connector: Connector<{}, Props> = connect(mapStateToProps);

export default connector(FlowHome);
```

Reducer

```
/* @flow */

import _ from 'lodash';

import {
  TRACKER_NEXT_STEP,
} from './action';
import type { Tracker, Action } from '../../types';

type State = Tracker;

const initialState = {
  currentStep: '0',
  completedSteps: [],
};

export default (state: State = initialState, action: Action): State => {
  switch (action.type) {
    case TRACKER_NEXT_STEP:
      return _.assign({}, state, { currentStep: action.currentStep });
    default:
      return state;
  }
};
```

Type 
```
export type Tracker = {
  currentStep: string,
  completedSteps: Array<string>,
}

export type Reducer = {
  tracker: Tracker,
  router: any,
};

export type Action = { type: 'TRACKER_NEXT_STEP', currentStep: string };
```

Any suggestion on what is the correct way to get the state this way. This reducer specifically is really simple and does not have any calls to the server. And the state holds a string.

Thanks

**Comment by wellyshen** [comment]
@lgarro Make sure you have registered your reducer in [this](https://github.com/wellyshen/react-cool-starter/blob/master/src/redux/reducers.js) file.

**Comment by lgarro** [comment]
@wellyshen  I have like this 

```
/* @flow */

import { combineReducers } from 'redux';
import { routerReducer as router } from 'react-router-redux';
import tracker from '../containers/FlowHome/reducer';

export default combineReducers({
  tracker,
  router,
});
```

Given the example im using I do not need to pass the loadData to routes correct? Because I dont use any dispatch ?

ty

**Comment by wellyshen** [comment]
@lgarro Yes, If you don't need to fetch data from server-side, you don't need to set up the action calling in `routes.js`. From your settings, you should able to access your initialState, I suggest you to re-check your code again, make sure you didn't miss anything.

**Comment by lgarro** [comment]
thanks for the feedback , until now. One more questions, does every container needs to be connected. Or am I able to create a container with a more presentational behavior. Could put it in components folder but I want to have compos folder just for the basic building blocks and then have my app container in one place.

**Comment by wellyshen** [comment]
@lgarro, Once I have the same question. There's no a clearly answer, I'd like to recommend you to read the [post](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0).

**Comment by lgarro** [comment]
@wellyshen  the problem was the import of the container in routes.js . I was importing the index directly.
Thanks
