### ISSUE TITLE
how to disable image bundle 

### ISSUE THREAD

**Issue by mehrdad-masoumi** [wellyshen/react-cool-starter#557]
static image on production envorment not show

**Comment by mehrdad-masoumi** [comment]
@wellyshen

**Comment by wellyshen** [comment]
@mehrdad517 I can't reproduce this issue. Can you describe the issue more detailed or give me a reproduced branch for investigating this issue?

**Comment by wellyshen** [comment]
Close due to inactive, if this issue actually exist. Please report it to me again.

**Comment by mehrdad-masoumi** [comment]
i use require to load image. but image not loading,
on master branch

**Comment by wellyshen** [comment]
@mehrdad517 Webpack `url-loader` turns on the `esModules` by default. If you want to access your images by the `require()`, you need to use it as below:

```js
<img src={require('your-image-path').default} />
```
