### ISSUE TITLE
load data api not send request info

### ISSUE THREAD

**Issue by mehrdad-masoumi** [wellyshen/react-cool-starter#588]
[2020-05-04 22:51:10] production.INFO: array (
  'domain' => 'deltakit',
  'url' => 'http://api.deltakit.ir/api/shop/products/swiper',
  'method' => 'GET',
  'origin' => NULL,
  'Referer' => NULL,
  'host' => 'api.deltakit.ir',
)
[2020-05-04 22:51:10] production.INFO: array (
  'domain' => 'deltakit',
  'url' => 'http://api.deltakit.ir/api/brand',
  'method' => 'GET',
  'origin' => NULL,
  'Referer' => NULL,
  'host' => 'api.deltakit.ir',
)
[2020-05-04 22:51:10] production.INFO: array (
  'domain' => 'deltakit',
  'url' => 'http://api.deltakit.ir/api/setting',
  'method' => 'GET',
  'origin' => NULL,
  'Referer' => NULL,
  'host' => 'api.deltakit.ir',
)
[2020-05-04 22:51:10] production.INFO: array (
  'domain' => 'deltakit',
  'url' => 'http://api.deltakit.ir/api/blog',
  'method' => 'GET',
  'origin' => NULL,
  'Referer' => NULL,
  'host' => 'api.deltakit.ir',
)
[2020-05-04 22:51:12] production.INFO: array (
  'domain' => 'matinpakhsh',
  'url' => 'http://api.deltakit.ir/api/blog?limit=4&page=1',
  'method' => 'GET',
  'origin' => 'http://matinpakhsh.ir',
  'Referer' => 'http://matinpakhsh.ir/',
  'host' => 'api.deltakit.ir',
)
[2020-05-04 22:51:12] production.INFO: array (
  'domain' => 'matinpakhsh',
  'url' => 'http://api.deltakit.ir/api/slider',
  'method' => 'GET',
  'origin' => 'http://matinpakhsh.ir',
  'Referer' => 'http://matinpakhsh.ir/',
  'host' => 'api.deltakit.ir',
)

log of main rout, slider and blog with referer and contain other request options

      {
        path: '/',
        exact: true,
        component: asyncHome, // Add your route here
        loadData: ({params}: { params: { filter: any, category: any, tag: any } }) => [
          settingAction.fetchSettingIfNeeded(),
          productSwiperAction.fetchProductSwiperIfNeeded(),
          brandAction.fetchBrandIfNeeded(),
          blogAction.fetchBlogIfNeeded({ page: 1, limit: 4 }, params.category, params.tag)
        ],
      },

**Comment by mehrdad-masoumi** [comment]
if using window.location.host or etc routes error

**Comment by mehrdad-masoumi** [comment]
how to send host, origin or referer to server in load data api

**Comment by mehrdad-masoumi** [comment]
[2020-05-04 22:46:25] local.INFO: array (
  'domain' => 'deltakit',
  'url' => 'GET',
  'origin' => 'http://localhost:3001',
  'Referer' => 'http://localhost:3001/',
  'host' => 'localhost:8000',
)  
[2020-05-04 22:46:25] local.INFO: array (
  'domain' => 'deltakit',
  'url' => 'GET',
  'origin' => 'http://localhost:3001',
  'Referer' => 'http://localhost:3001/',
  'host' => 'localhost:8000',
)  
[2020-05-04 22:46:50] local.INFO: array (
  'domain' => 'deltakit',
  'url' => 'GET',
  'origin' => 'http://localhost:3001',
  'Referer' => 'http://localhost:3001/',
  'host' => 'localhost:8000',
)  
[2020-05-04 22:46:50] local.INFO: array (
  'domain' => 'deltakit',
  'url' => 'GET',
  'origin' => 'http://localhost:3001',
  'Referer' => 'http://localhost:3001/',
  'host' => 'localhost:8000',
)  
[2020-05-04 22:48:19] local.INFO: array (
  'domain' => 'deltakit',
  'url' => 'http://localhost:8000/api/slider',
  'method' => 'GET',
  'origin' => 'http://localhost:3001',
  'Referer' => 'http://localhost:3001/',
  'host' => 'localhost:8000',
)  
[2020-05-04 22:48:19] local.INFO: array (
  'domain' => 'deltakit',
  'url' => 'http://localhost:8000/api/blog?limit=4&page=1',
  'method' => 'GET',
  'origin' => 'http://localhost:3001',
  'Referer' => 'http://localhost:3001/',
  'host' => 'localhost:8000',
)  
in my localhost

**Comment by mehrdad-masoumi** [comment]
@wellyshen

**Comment by wellyshen** [comment]
@mehrdad517 I have exposed the HTTP request and response for you (see [v3.7.0](https://github.com/wellyshen/react-cool-starter#data-fetching-from-server-side)). You can get the related data from the `req` object then send it with `axios`.

**Comment by mehrdad-masoumi** [comment]
@wellyshen tank u

**Comment by mehrdad-masoumi** [comment]
The problem was not solved.I got the host information using req.
But when I called the action again at home I have to pass the req to it, But where from?
How can I access req by default in Actions?
An AppState defines a router that does not contain headers.

My program must send the header to receive information from the server based on the header sent.

@wellyshen

**Comment by mehrdad-masoumi** [comment]
how to set req object in server.tsx that send with loaddata url
@wellyshen

**Comment by wellyshen** [comment]
@mehrdad517 We can't access the req in client-side directly, but we can pass the data of req to client-side via Redux store then access it as below:

```js
// routes.ts
export default [
  {
    component: App,
    routes: [
      {
        path: "/",
        exact: true,
        component: asyncHome,
        loadData: ({ req }) => [
          // Pass the req data to client-side via Redux store
          reqDataAction.set({ hostname: req.hostname });
        ],
      },
    ],
  },
];

// someAction.ts
export const fetchData = () => (_, getState) => {
  // Now you can get the hostname in client-side
  const { host } = getState().reqData;
};
```

**Comment by mehrdad-masoumi** [comment]
solved!
please apply this configuration in the new version,
