### ISSUE TITLE
IE 11 promise

### ISSUE THREAD

**Issue by oskarleonard** [wellyshen/react-cool-starter#59]
App does not work properly in IE 11. I suggest adding babel-polyfill. Something like below should fix the problem:
1. npm install --save babel-polyfill
2. Add 'babel-polyfill' in vendor array.

**Comment by wellyshen** [comment]
@wayweary Can you help me to verify this issue by adding the `babel-polyfill` in the entry of webpack config or `./index.js` to see if it works on IE11?

The entry of webpack config :
```javascript
const getEntry = () => {
  // ...

  let entry = [
    'babel-polyfill',
    // others...
  ];

  // ...
};
```

**Comment by oskarleonard** [comment]
I think it is needed in both places, prod and dev. For the getting started guide to work (`yarn start:production`) in IE11 you need to add it to the vendor array or add it some other way in the `if (!isDev) {` statement. 

By adding what you wrote it will work with `yarn start` but not  `yarn start:production`

So it is necessary for both prod and dev.

**Comment by wellyshen** [comment]
@wayweary Thank you for your suggestion, I added "babel-polyfill" into the `index.js` for fixing this issue, can you help to verify this issue through the latest commit?

**Comment by oskarleonard** [comment]
Production (yarn start:production) OK, because you added it in the vendor array.

Development (yarn start) Not OK. I think adding it in the index.js file is to late. You need to add it first in the entry array. like
 ```  
let entry = [
    'babel-polyfill', // Fixes for IE11
    'react-hot-loader/patch',
    'webpack-hot-middleware/client?reload=true',
    './src/client.js',
  ];
```

Great starter kit by the way, i hope you will keep it updated :). We use parts from it in our project, one worrying part is the alpha and beta dependencies.

**Comment by wellyshen** [comment]
Hi @wayweary I have pushed a new modified commit, could you mind to verify if it's OK on dev, thanks :)

**Comment by oskarleonard** [comment]
@wellyshen 
Great that you found a way to add the polyfill directly in the main variable, very clean. Dont forget to remove the polyfill in the vendor array and it will be perfect 👍  :).

**Comment by wellyshen** [comment]
@wayweary Thanks a lot man, I have adjusted it as you suggested ;)
