### ISSUE TITLE
Where we should use tsx extension file extension?

### ISSUE THREAD

**Issue by amerllica** [wellyshen/react-cool-starter#594]
Just like all of us know this starter uses TypeScript. so most of the files should be written by **ts** file extension, but some files have **tsx** extension. it happened because they contain **JSX**. so it is more readable to use *x* end of the extension.

But for route file, I see the file have **tsx** extension and actually it doesn't contain JSX codes. so why it should be `routes.tsx`? I think files with pure TypeScript/JavaScript codes should have `ts`/`js` file extension.

**Comment by wellyshen** [comment]
@amerllica Thank you bro, I have fixed it in the latest version.
