### ISSUE TITLE
state.router.location always null

### ISSUE THREAD

**Issue by supukarmin** [wellyshen/react-cool-starter#60]
state.router.location is always null. I just did a fresh installation and checked it twice. Any ideas?

**Comment by wellyshen** [comment]
@Loewenhardt Here's my router state. The `state.router.location` isn't null. Make sure you were using the latest commit and tracked it properly.

<img width="1280" alt="2017-05-05 7 02 19" src="https://cloud.githubusercontent.com/assets/21308003/25743164/9d9e0bba-31c5-11e7-8436-bed667fb8e14.png">

**Comment by supukarmin** [comment]
It works now. I don't know what the problem was, maybe some cache issue. Thank you.
