### ISSUE TITLE
Is it possible to have more readable package.json file?

### ISSUE THREAD

**Issue by amerllica** [wellyshen/react-cool-starter#601]
The title comes from this question: **Why all of the configs are in the package.json file?**

Why we have not separated these files:

 - `.eslintrc` and `.eslintignore` for ESLint configuration
 - `.babelrc` for having babel configuration
 - `.stylelintrc` for having style lint configuration
 - `.prettierrc` for having configuration of prettier
 - `.browserslistrc` for having browserify configuration
 - and etc.

If you are agreed, let me do these configurations. I will make them.

**Comment by wellyshen** [comment]
@amerllica Okay let's do it. Thank you.

**Comment by amerllica** [comment]
Dear @wellyshen, can you review my PR, because I have another PR to implement a better development area to have a faster development build.

**Comment by wellyshen** [comment]
@amerllica I did. And I leave some comments to you bro.

**Comment by amerllica** [comment]
@wellyshen, I cannot see any comment, it's so weird for me. why I see a conflict. the day I sent the PR there was no conflict. so I fix it and will send it again.

**Comment by wellyshen** [comment]
@amerllica Sorry I forgot to submit the comments. Can you see them now?

**Comment by amerllica** [comment]
Dear @wellyshen, Thanks for your comments. for the last time, please review the comments and after that, I will change my codes for the current PR.

**Comment by wellyshen** [comment]
@amerllica Thank you for your effort bro, I will review it again after you update the PR.

**Comment by amerllica** [comment]
Thanks @wellyshen, I answer to some comments. I mean review the comments. not the codes.

**Comment by wellyshen** [comment]
@amerllica I have replied your comments, please review them. If any concerning, feel free to discuss with me, thank you.

**Comment by amerllica** [comment]
Dear @wellyshen bro, I push new commit now. actually, I changed codes based on your code review.

Why does the build fall into error?
