### ISSUE TITLE
Css import

### ISSUE THREAD

**Issue by m0rdreck** [wellyshen/react-cool-starter#61]
How to import CSS from node_modules ? example for draft js

**Comment by wellyshen** [comment]
@m0rdreck Assume you're in `App.js` and you want to import bootstrap from node_modules and using it without css modules :

```javascript
import '../../../node_modules/bootstrap/dist/css/bootstrap.css';

// ...
```

**Comment by m0rdreck** [comment]
i try but not working ... don't see any changement in styles i have add in style Html.js and in my containers.

i show the css content in code but not apply on view

**Comment by wellyshen** [comment]
@m0rdreck Actually, there's no different between put `.css` file in `.src/theme` or `node_modules/`, make sure your path or css file is correct.
