### ISSUE TITLE
Usage of global variables 

### ISSUE THREAD

**Issue by lgarro** [wellyshen/react-cool-starter#65]
Im currently trying to set some different deployment options for my server , in order to have different test environments.

Right now what im doing is defining a variable TARGET_SERVER on my heroku instance in order to trigger the Procfile web process with that variable and thus using the correct information for my different API versions. The issue right now is with the config file usage but on the front end side.

On my ```prod.js``` config file I redefined an API_URL attribute which points to prod server and then I created a ```staging.js``` that has another api url. The configuration works fine for everything that is server side such as my mongo connection it grabs the right one but when retrieving the ```TARGET_SERVER``` environment in an action file, it does not know the variable I set on the server, so I tried setting a ```global.TARGET_SERVER``` and assigned ```process.env.TARGET_SERVER```, and also added the declaration on ```globalVariables.js```.

declaration : ```declare var __TARGET_SERVER__: any;```

index.js 
```global.__TARGET_SERVER__ = process.env.TARGET_SERVER;```

When trying to use this value ```__TARGET_SERVER__``` on ```config/index.js``` I always get undefined. 
I get undefined here when using config from a Container action.js where I get the API url. Server side works fine.

```if (process.env.NODE_ENV !== 'production') {
  module.exports = require('./default');
} else {
  // eslint-disable-next-line
  if (__TARGET_SERVER__ == 'stage' || process.env.TARGET_SERVER == 'stage') {
    console.log('Using staging.js config');
    module.exports = require('./staging');
  } else {
    console.log('Using prod.js config');
    module.exports = require('./prod');
  }
}
```

UPDATE: variable no longer undfined when defined from webpack files, but still I get the wrong value for it 

Do you know what is the possible failure on my approach to set the global variable reference in the front side.
Thanks in advance for the time dedicated in answering and maintaining this repo in good shape.

**Comment by wellyshen** [comment]
@lgarro Where did you define the global variable? In the `./index.js` file?

**Comment by lgarro** [comment]
@wellyshen yes its defined in the ./index js 

```global.__CLIENT__ = false;
global.__SERVER__ = true;
global.__DISABLE_SSR__ = false;   // Disable server side render here
global.__DEV__ = process.env.NODE_ENV !== 'production'; //update
global.__TARGET_SERVER__ = process.env.TARGET_SERVER;```

**Comment by wellyshen** [comment]
Hi @lgarro, Have you setup your new global variable in `package.json`? You can check how did I setup the `process.env.NODE_ENV` and used it from the starter.

**Comment by lgarro** [comment]
instead of defining there I was passing it directly to the node ./index js without using the better-npm-script, via a heroku Procfile. But right now I took a different approach in order to make it work so , ill close the issue thanks very much for the guidance @wellyshen
