### ISSUE TITLE
Client side loading doesn't work

### ISSUE THREAD

**Issue by scaledrop** [wellyshen/react-cool-starter#678]
All pages seem to be loading from server now. 

dev:
![image](https://user-images.githubusercontent.com/2621312/89731194-b665da80-da62-11ea-8717-83d87f243816.png)

prod:
![image](https://user-images.githubusercontent.com/2621312/89731175-99310c00-da62-11ea-8aee-60d9bf57e24a.png)

This has happened recently. @wellyshen Can you please look at it?

**Comment by wellyshen** [comment]
@scaledrop No problem, it has been fixed in the [v3.10.1](https://github.com/helmetjs/helmet/blob/master/CHANGELOG.md#added).

**Comment by scaledrop** [comment]
Thanks a lot!
