### ISSUE TITLE
Bizarre warnings when adding onClick handler to button

### ISSUE THREAD

**Issue by jeghers** [wellyshen/react-cool-starter#68]
After adding a click handler to a button, these warnings now fill the console with every click:

Warning: isMounted(...) is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.
Warning: replaceState(...) is deprecated in plain JavaScript React classes. Refactor your code to use setState instead (see https://github.com/facebook/react/issues/3236).

Here is the render code:

  onClick() {
    console.log('onClick - this...');
    console.log(this);
  }

  render() {
    console.log('this.props.about...');
    console.log(this.props.about);
    return (
      <div className={styles.About}>
        <Helmet title="About" />
        {this.renderUserList()}
        <button onClick={() => this.onClick()}>&nbsp;Increment&nbsp;</button>
        &nbsp;&nbsp;Count is {this.props.about.counter}
      </div>
    );
  }

(I was forced to use the arrow function for onClick in order to get a this pointer in the handler function)

**Comment by jeghers** [comment]
Note: this happens in IE but not Chrome

**Comment by wellyshen** [comment]
@jeghers 

I guess `onClick` isn't the main reason for causing this warning. Have you used any out of updated 3rd party library or used the `isMounted()` method? See [here](https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html) for more information.

If I were you I will write the function as below :

```javascript
handleOnClick = () => {
  console.log('onClick - this...');
  console.log(this);
}

render() {
  return <button onClick={this.handleOnClick} />;
}
```
