### ISSUE TITLE
Error: pngquant failed to build, make sure that libpng-dev is installed

### ISSUE THREAD

**Issue by s-pyadyshev** [wellyshen/react-cool-starter#689]
$ yarn
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > connected-react-router@6.8.0" has unmet peer dependency "immutable@^3.8.1 || ^4.0.0-rc.1".
warning " > connected-react-router@6.8.0" has unmet peer dependency "redux@^3.6.0 || ^4.0.0".
warning " > connected-react-router@6.8.0" has unmet peer dependency "seamless-immutable@^7.1.3".
warning " > react-redux@7.2.1" has unmet peer dependency "redux@^2.0.0 || ^3.0.0 || ^4.0.0-0".
warning " > eslint-plugin-testing-library@3.6.0" has incorrect peer dependency "eslint@^5 || ^6".
[5/5] Building fresh packages...
[10/12] ⠂ cwebp-bin
[2/12] ⠂ node-sass
[-/12] ⠂ waiting...
[-/12] ⠄ waiting...
warning Error running install script for optional dependency: "C:\\projects\\react-cool-starter\\node_modules\\pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: C:\\projects\\react-cool-starter\\node_modules\\pngquant-bin
Output:
‼ Command failed: C:\\projects\\react-cool-starter\\node_modules\\pngquant-bin\\vendor\\pngquant.exe --version

  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at C:\\projects\\react-cool-starter\\node_modules\\bin-build\\node_modules\\execa\\index.js:231:11
Done in 73.50s.

**Comment by wellyshen** [comment]
@s-pyadyshev See if you can find the solution via this [open issue](https://github.com/imagemin/imagemin-pngquant/issues/46).
