### ISSUE TITLE
Moving an image directory during build

### ISSUE THREAD

**Issue by jmsherry** [wellyshen/react-cool-starter#69]
So, this might be a stupid question but it's not working atm!

If I have  a directory full of images which I want to be public, how is that meant to work? If I have the directory in `src` webpack doesn't pick it up and move it to the build directory!

How are static public images meant to be handled?

**Comment by NiluK** [comment]
Static assets can be handled by putting it in the /public/ folder but not in the assets folder as Wepback will overwrite the assets folder. eg https://puu.sh/w79s7/02f1fd3b3e.png

**Comment by jmsherry** [comment]
@NiluK Thanks :)

It seems odd though because the logo the header was require()d...??

And that would make sense because:
- Having them manually loaded into that directory means:
    *  your system has no control over them and 
    * they can't be optimised by webpack...
- Usually in boilerplates there's a `src` directory and the contents are then processed into a `dist` (or `build`) directory. The `dist` is deleted and remade every time and is excluded from source control.

Personally I'd worry about someone not realising and deleting their build directory `rm -rf`-style??!!

Not complaining, just querying and offering an opinion. :)

**Comment by NiluK** [comment]
Yeah I agree.

**Comment by jmsherry** [comment]
@wellyshen Is it supposed to be done this way? Or have we misunderstood??

Thanks. :)

**Comment by wellyshen** [comment]
Hi @jmsherry, 

As the [webpack config](https://github.com/wellyshen/react-cool-starter/blob/master/tools/webpack/webpack.client.babel.js#L108), images will be built into the assets folder of the public folder. 

For the `.svg` logo of the starter, It has embed as a part of `.js` file (a.k.a inline image for small size images), that's why you can't see it in the assets folder.

**Comment by jmsherry** [comment]
Hey @wellyshen :),
Yes, I worked out what was going on with the logo. The issue is more what to do if I have, for example, a gallery of images. I can't require them all individually! It would be better to have webpack detect them and move them to the build directory (possibly optimising them on the way!).

I did put a directory of images into `src`, hoping that it would, but it didn't. I'm really asking the question to check whether webpack was supposed to move them or not? 

Thanks :)

**Comment by wellyshen** [comment]
@jmsherry As I know, if you don't import images somewhere. `file-loader` won't copy them into the the output dist folder (refer to this [issue](https://github.com/webpack-contrib/file-loader/issues/116)). I think the images folder can be move through npm command or some plugins.

**Comment by jmsherry** [comment]
Yes, that's what I really wanted to know. :)

I'll close the ticket, but it may be worth considering in the future adding some image optimisation to the flow?

**Comment by wellyshen** [comment]
@jmsherry Yes, if there's a great library to deal with it, I'm willing to count it into the starter.
