### ISSUE TITLE
It's strange behavior of app

### ISSUE THREAD

**Issue by maximusnikulin** [wellyshen/react-cool-starter#7]
Hi, could you explane me, what the profit of using async reducers and async routes is?
When I run your app it's load data in first time, despite on the data have already been in app(isomorphic routing with "preload" data), then when I click one of links I see "...loading" again, when come back Home Page I see "...loading" again .
I thought It's too many useless requests to the API. Maybe I am wrong?
If you have time, write me an answer. 
Also, I found small bug with stylelinter, when I make mistake in my scss file It shows message, but after repairing webpack doesn't hot reload. It is terminated via failOnErrors: false, but then webpack'll be compile css even with errors.
Thanks

**Comment by maximusnikulin** [comment]
I understood reason for "...loading", but

**Comment by maximusnikulin** [comment]
I understood the reason  for repeat request to API, but is there any way to avoid it? 

Also when I change initial state of one of the reducers for example in Home reducer I added some new prop, it was showed only when I reloaded server. 
It's very hard to develop app every time reload server when you want to change reducer.
If I make mistake in js code, I often get message:
[nodemon] app crashed - waiting for file changes before starting...
And even I repair error I should reload server.
Async reducers and routes use for webpack code spliting? To reduce size of bundle file?

**Comment by wellyshen** [comment]
@maximusnikulin 

For the hot reloading purpose, the repeat API fetching behavior just in development environment, in production the fetched data won't be fetched again.

For the issue of reducer hot reloading and repairing error of JS and style part, I will check it and reply you soon :)

By the way, the async routing and async reducer are used to enhance the experience of user browsing, in the other words, if one day your app extended to a large scale service, then user landing to your website, they will see the home page more faster without waiting for the whole javascript files loaded.

**Comment by maximusnikulin** [comment]
Wow!!!  it's intresting things about async router and reducers, thanks a lot for your answer.
I'll be waiting for some news, thanks.

**Comment by wellyshen** [comment]
Hi @maximusnikulin 
If your props isn't changeable, I suggest you put it in the component view rather than the reducer (e.g. Home / reducer.js). If it's changeable, generally it will be changed by action dispatching. With this concept the hot reloading will work perfectly ;)

For the hot reload issue of styelint and eslint, just set the `failOnError: false`, or the build process will be terminated, which is the reason of hot reloading failed.

**Comment by maximusnikulin** [comment]
Thanks for your answer, I understood your idea. I have no big experience of developing React app, but I noticed that it useful sometimes make object for `initialState` of whole my app and put it when create store. I solved this, change `__DISABLE-SSR__ = true` and rewrite some code `
const store = __DISABLE_SSR__ ? configureStore() : configureStore(initialState);`
After this, my store will depends on only my client - not server. 
I  was really excited by idea of async reducers and routers, that really great, but is there way to check out if it works in boilerplate. I thought, when I open panel 'Network' in Chrome Devtools, I'll see new js file was loaded asynchronously when I go to Home or go to UserInfo.
Sorry for late answer and a lot of questions, I would use your boilerplate in my projects because it really nice structure and there are all thing I needed.

More: https://github.com/maximusnikulin/react-cool-starter/blob/master/src/client.js
Also I want to know why we have different variables `__SERVER__ , __CLIENT__, __DISABLE--SSR`
in index.js and tool/webpack/config.babel.js and they don't connect each other.
Might It need something like this in config.babel.js:
`__DISABLE_SSR__:JSON.stringify(global.__DISABLE_SSR__),` and similar for others.
Thanks.

**Comment by wellyshen** [comment]
Hi @maximusnikulin 

Nice to hear about it from you, If you use it for your own product, please feel free to share with me :)

The different variable is that:
`__SERVER__` is used to check if the file is running in server side (node)
`__CLIENT__` is used to check if the file is running in client side (webpack bundle)
`__DISABLE_SSR__` is used to disable the server side render

For the `__DISABLE_SSR__`, I am planning to remove it from webpack config... but your idea would be great, thanks a lot.

**Comment by maximusnikulin** [comment]
Thanks and last question about async reducers and routers, are you sure that is working? If yes, are we able check it out? Maybe in chrome dev tools tab "network"? Because now I don't see new chunks there, when go between routes 
Thanks

**Comment by wellyshen** [comment]
Hi @maximusnikulin 

Thank for your report this issue, I will fix it soon :)

**Comment by wellyshen** [comment]
Hi @maximusnikulin The async routing and async reducer now Rocks, please clone the latest comment repo to see it ;)
