### ISSUE TITLE
Stylelint fails reporting no error details

### ISSUE THREAD

**Issue by jeghers** [wellyshen/react-cool-starter#70]
I get this...

Error: Failed because of a stylelint error.

    at linterSuccess (C:\Users\mjeghers\Desktop\UUI\react-redux-cool-callsign-lookup\node_modules\stylelint-webpack-plugin\lib\run-compilation.js:35:14)

**Comment by jeghers** [comment]
Also, when this happens, the hot loading dies and the server must be killed and restarted

**Comment by wellyshen** [comment]
@jeghers Sorry for later, due to the setup of `stylelint-webpack-plugin`, which will cause the terminating of webpack bundling. Maybe you can turn it off through `./tools/webpack/config.js` and use `yarn lint` to check the style.
