### ISSUE TITLE
css lib is not working - semantic ui

### ISSUE THREAD

**Issue by nikvarma** [wellyshen/react-cool-starter#714]
thank you for create starter guide app, very helpful.

i am facing the issue with css, seems there is some issue in webpack.config. i installed **semantic ui**  and now when i am running the app css is not applying due build is adding extra prefix on each class name **semantic-min__ui.semantic-min__button**.

**Comment by wellyshen** [comment]
@nikvarma Can you give me a minimal repo for debugging?

**Comment by nikvarma** [comment]
Hi, this issue is resolved now, after updating the packages.

but now i'm facing issue with deploying to firebase(bez no index file is generating) and web server. plz help @wellyshen 

build cmd

"build": "cross-env NODE_ENV=production webpack --progress --hide-modules --config ./tools/webpack/config.babel.js",

![image](https://user-images.githubusercontent.com/3116497/93920477-3d060c80-fcdd-11ea-83ad-433496f9d5b5.png)
![image](https://user-images.githubusercontent.com/3116497/93920548-53ac6380-fcdd-11ea-950c-915856b5570e.png)

**Comment by wellyshen** [comment]
@nikvarma Sorry I don't familiar with the hosting of Firebase. For React server-side rendering, the HTML template is generating by the express server, therefore there's no the `index.html` file. But the general concept is [packing the all necessary stuff](https://github.com/wellyshen/react-cool-starter#how-to-deploy) then running it by a Node.js hosting.
