### ISSUE TITLE
Why so indentation / white-space sensitive?

### ISSUE THREAD

**Issue by aagentah** [wellyshen/react-cool-starter#74]
I can't seem to get any work done on this project because "wrong" indentation & white-space trailing causes me to get linting errors and fail everything.  Even if a CSS class, or a div has a trailing white-space, it seems to lock down my whole project until I fix it.

Is there a way I can turn this off as it seems a bit excessive & seriously kills workflow?
Thank you in advance

**Comment by wellyshen** [comment]
@danjonesdev Try to turn off the lint error detecting while webpack bundling through [here](https://github.com/wellyshen/react-cool-starter/blob/master/tools/webpack/config.js)

**Comment by aagentah** [comment]
So this is the config.js now:
```

// Disable CSSModules here
const CSSModules = true;

// Disable js lint error terminating here
const eslint = false;
// Disable style lint error terminating here
const stylelint = false;

// Register vendors here
const vendor = [
  'react',
  'react-dom',
  'redux',
  'react-redux',
  'redux-thunk',
  'react-hot-loader',
  'react-router-dom',
  'history',
  'react-router-redux',
  'react-helmet',
  'axios',
  'redbox-react',
  'chalk',
  'lodash',
  'babel-polyfill',   // Support promise for IE browser (for prod)
];

module.exports = {
  CSSModules,
  // eslint,
  // stylelint,
  vendor,
};
```


Yet I still get errors like:
` Expected indentation of 6 space characters but found 4  react/jsx-indent`

 ```
   2:8   error  A space is required after '{'   object-curly-spacing
   2:13  error  A space is required before '}'  object-curly-spacing
   3:8   error  A space is required after '{'   object-curly-spacing
   3:28  error  A space is required before '}'  object-curly-spacing
  11:19  error  A space is required after '{'   object-curly-spacing
  11:24  error  A space is required before '}'  object-curly-spacing

```

Any advice on how to stop all errors like this? (As it isn't breaking my code it's just white-space right?)

**Comment by wellyshen** [comment]
@danjonesdev Try to remove the [eslint-loader](https://github.com/MoOx/eslint-loader) and the related config from [webpack.client.config](https://github.com/wellyshen/react-cool-starter/blob/master/tools/webpack/webpack.client.babel.js)
