### ISSUE TITLE
Unexpected unknown property "webkit-transition"

### ISSUE THREAD

**Issue by aagentah** [wellyshen/react-cool-starter#75]
I really am sorry, this is the 3rd issue I have raised, I really am a nice guy... I promise!

So for some reason the app doesn't allow for styles like `animation` or `webkit-transition`.

Here is my code:

```
.UserList {
  max-width: 1200px;
  margin: 0 auto;
  opacity: 0;

  &:hover {
    webkit-transition: opacity 2.0s ease-in;
    -moz-transition: opacity 2.0s ease-in;
    -o-transition: opacity 2.0s ease-in;
    opacity: 1;
  }
```

Here is my error:

> ERROR in
> src/components/UserList/styles.scss
>   9:5   ×  Unexpected unknown property "webkit-transition"   property-no-unknown

I'm really struggling resolve fix this, any help would be appreciated! 
Thank you in advance!

**Comment by wellyshen** [comment]
@danjonesdev I have used [postcss-loader](https://github.com/postcss/postcss-loader) to support cross-browser style. I think you don't have to do it by yourself.

**Comment by aagentah** [comment]
That's cool, thank you :)
