### ISSUE TITLE
Minification not working?

### ISSUE THREAD

**Issue by iamacup** [wellyshen/react-cool-starter#78]
Hey

First - i love what you have done, and i am so thankful you made this pack! I am trying to keep our project up to date with yours, but the latest changes have left me with a question:

I think the latest version of the starter pack is missing JS minification, the last version i forked (https://github.com/iamacup/sliips-ui/tree/cbe0825aff4c22d16793babd4a3bd089f1a828db)  had the following stats:

https://pastebin.com/5bQ7tmdS

> vendor.c476fbf6.js   469 kB       1  [emitted]  [big]  vendor

But the latest version of react-cool-starter has this:

https://pastebin.com/iHYb0KN6

> vendor.c5a4f66d.js  1.99 MB       1  [emitted]  [big]  vendor

**Comment by iamacup** [comment]
May be related to this: https://github.com/babel/babili/issues/172

**Comment by wellyshen** [comment]
@iamacup Thank you for the instruction. I have use another plugin to replace the original one. Now it works great :)
