### ISSUE TITLE
I found something interesting: Redux Clerk

### ISSUE THREAD

**Issue by aagentah** [wellyshen/react-cool-starter#82]
So this isn't an issue as such, more of a proposed implementation. I have been reading this [article](https://inside.getambassador.com/redux-clerk-reusable-action-creators-and-reducers-for-async-crud-b0b6954f7056)

> If you’ve ever used Redux and Redux Thunk you’re well aware of the repetitive nature of CRUD actions and reducers. Each CRUD operation is made up of the same set of action creators and reducer to handle each of these actions. After we built several sets of these we realized they were almost identical, with the exception of the action names and some async request configuration. Redux Clerk solves the code duplication problem by generating standard actions and reducers needed for CRUD operations.

[Redux Clerk](https://github.com/GetAmbassador/redux-clerk) looks highly beneficial to anyone using a similar Redux process for CRUD operations, I was wondering what people's thoughts were on this, and wether it could be considered for this boilerplate?

Thanks
Dan

**Comment by wellyshen** [comment]
@danjonesdev Thank you for sharing it to me. It seems interesting, I'll spend time to realize it :)
