### ISSUE TITLE
Home/action does not throw USERS_FAILURE err

### ISSUE THREAD

**Issue by aagentah** [wellyshen/react-cool-starter#84]
In the Home/action.js file, If I change the axios URL to for example:

`export const API_URL = 'https://jsonplaceholder.typicode.com/LinkThatDoesntWork';`

I believe this should return USERS_FAILURE err on the request because that would'nt return the right data, but instead it throws this in my cmd on "yarn start":

> ==> �  Rendering routes error: TypeError: Converting circular structure to JSON

Should this not throw USERS_FAILURE  instead of failing to start the app?
Thanks
Dan

**Comment by wellyshen** [comment]
@danjonesdev Thank you for reporting this bug. It has been fixed in the latest commit.
