### ISSUE TITLE
Example for subroutes

### ISSUE THREAD

**Issue by kooinam** [wellyshen/react-cool-starter#85]
I've tried to implement subroutes using following codes but to no avail. Can anyone show some example? Thanks alot!
https://gist.github.com/kooinam/0eb33d5c201a6e2ce065229409fd4f2a

**Comment by wellyshen** [comment]
Hi @kooinam, The setup of the sub-routes of react-router V4 has a bit different from V2 , please see this [doc](https://reacttraining.com/react-router/web/example/route-config).
