### ISSUE TITLE
Warning: can't resolve definitions/basicConfigOrBoolean

### ISSUE THREAD

**Issue by ghost** [wellyshen/react-cool-starter#86]
Hey Welly,
 I keep getting this warning: `can't resolve reference #/definitions/basicConfigOrBoolean from id # `
and this keeps coming during running yarn build. I have made a couple of changes to eliminate scss and work only with css styles in the project. The other changes were to make sure it deploys to heroku properly.

It is just a warning that keeps cropping up during yarn build especially. Let me know man!

Thanks

**Comment by wellyshen** [comment]
@rahulbasu710 Upgraded dependencies to fix this issue. Here's the [root cause](https://github.com/airbnb/javascript/issues/1488#issuecomment-317526550)

**Comment by ghost** [comment]
Thanks man

**Comment by eldeveloperjuan** [comment]
@rahulbasu710 can you please tell the changes made to deploy it in heroku ? Im having troubles doing it.
Thanks a lot.
