### ISSUE TITLE
Where to fetchData for entire app

### ISSUE THREAD

**Issue by qburns** [wellyshen/react-cool-starter#9]
Hi @wellyshen , 

This boilerplate is working great for me so far, great work! I did have a question that maybe you can answer. It's not an issue with the boilerplate itself, but more so how to structure my logic with it.

I am storing my user JWToken into a cookie using react-cookie. I need to have the application check whether the user is stored in the redux store and if not, read the cookie and set it. However, I am struggling on where to load the cookie and FetchData for the entire application as a whole.

I understand fetching the data server side for the individual components, but I am a bit confused when it comes to fetching it for the whole app.

**Comment by wellyshen** [comment]
Hi @qburns 

I have studied topic call [HOC](https://crysislinux.com/limit-access-to-redux-apps-with-higher-order-components/). It's a great way to handle user authentication. Maybe you should try it :)

**Comment by qburns** [comment]
@wellyshen Isn't `.src/containers/App` a stateless functional component? I guess I would need to hook it up to Redux store in order to fetch and call my actions.

However, where/how would I call the children in App? Currently it is passed in as a prop to App itself.

**Comment by wellyshen** [comment]
Hi @qburns 

You can turn the `App` into react component for your purpose. I suggest not to call the children component through `App` directly. You can fetch the global store through it first, then use the global store on each children component. Does it helpful for you?

**Comment by qburns** [comment]
@wellyshen Thank you so much. I was staring at it for so long, I didn't try the simple solution. It is working now. Great work on this.

**Comment by wellyshen** [comment]
@qburns  How did you do finally?

**Comment by qburns** [comment]
@wellyshen 

I turned App into a React container and added a static fetchUser method like so:

`
import styles from './App.scss';

class App extends Component {
  static fetchUser(dispatch) {
    return Promise.all([
      dispatch(fetchUserIfNeeded()),
    ]);
  }

  shouldComponentUpdate(nextProps, nextState) {
    return shallowCompare(this, nextProps, nextState);
  }

  componentDidMount() {
    const { dispatch } = this.props;
    App.fetchUser(dispatch);
  }

  render() {

    return (

    <div className={styles.App}>
      <Container>
        <Helmet {...config.app} />
         <....more stuff here like navigation....>
        {this.props.children}
      </Container>
    </div>
    );
  }
}

App.propTypes = { children: PropTypes.node };

const mapStateToProps = state => ({ user: state.get('user') });

export default connect(mapStateToProps)(App);
`

The fetchUser method is calling 

`dispatch(getUserFromCookie);`

which looks like this:

`export const getUserFromCookie = (dispatch) => {
  dispatch({ type: GET_USER_FROM_COOKIE_ATTEMPT });
  const userCookie = cookie.load('userInfo');
  if (userCookie) {
    dispatch({ type: GET_LOGGED_IN_USER_SUCCESS, payload: userCookie });
  }
};`

The cookie is previously set when logging in.

One thing I am having trouble with, is using mapDispatchToProps in addition to the static method.

For example, I am used to writing my connect function like so:
`export default connect(mapStateToProps, { loginUser, otherAction })(LoginForm);`

However, if I try to write it like that on something like the homepage where it is getting data through fetchData, I get dispatch is not defined. I know this is because Redux does not put dispatch into props if you define actions, but I am struggling with how to both fetchData and dispatch other actions in one file. I'm sure I am missing something simple.

**Comment by qburns** [comment]
Also, I forgot to add that I had to make a change in routes.js like so:

```
export default function createRoutes(store) {
  return {
    path: '/',
    component: App,
    indexRoute: {
      getComponent(location, cb) {
        const importModules = Promise.all([
          System.import('./containers/Home'),
          System.import('./containers/Home/reducer'),
          **System.import('./Auth/reducer'),**
        ]);

        const renderRoute = loadModule(cb);

        importModules
          .then(([Component, reducer, **userReducer**]) => {
            injectReducer(store, 'home', reducer.default);
            **injectReducer(store, 'user', userReducer.default);**

            renderRoute(Component);
          })
          .catch(errorLoading);
      },
    },
```

I then import the userReducer into every route along with their normal reducer.

**Comment by wellyshen** [comment]
@qburns 

Great work! I think you don't have to `mapDispatchToProps`. Try just call the `dispatch(YourAction)` like I did in the static method. It works for me

**Comment by qburns** [comment]
@wellyshen Thanks for all the help. I have one last question if you are able to answer.

I am having difficulty navigating routes programatically outside of components.

Inside components I can do like this:
```
import React from 'react';

export default class Example extends React.Component {
  constructor(props) {
    super(props);
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick(e) {
    e.preventDefault();
    this.context.router.transitionTo('/');
  }

  render(){
    return (<div onClick={this.handleClick}>Click me!</div>);
  }
}

Example.contextTypes = {
  router: React.PropTypes.func.isRequired
};

```
This works as expected. However, when I try to do it in an action like below, only the URL changes but the application does not change pages

```
import { push } from 'react-router-redux';

export const redirectUser = () => (dispatch) => {
  dispatch(push('/signup'));
}
```

**Comment by wellyshen** [comment]
@qburns Have you setup the [middleware](https://github.com/reactjs/react-router-redux#what-if-i-want-to-issue-navigation-events-via-redux-actions)?

**Comment by qburns** [comment]
@wellyshen Yes I have. My redux/store.js has this in it:
```

import { browserHistory } from 'react-router';
import { routerMiddleware } from 'react-router-redux';

export default (initialState) => {
  const middlewares = [
    thunk,
    routerMiddleware(browserHistory)
  ];


  const enhancers = [
    applyMiddleware(...middlewares),
    __DEV__ && typeof window === 'object' && typeof window.devToolsExtension !== 'undefined' ?
      window.devToolsExtension() : f => f,
  ];

```

**Comment by wellyshen** [comment]
Hi @qburns 

How about doing this in your component ?

```
  handleClick(e) {
    e.preventDefault();
    
    { dispatch } = this.props;
    dispatch(push('/signup'));
  }
```

**Comment by qburns** [comment]
@wellyshen Unfortunately I cannot do that here. My case is that I am building a higher order component that checks whether the user is logged in. If they are not, I need to automatically re-direct them to the login screen.

**Comment by wellyshen** [comment]
@qburns Alright, maybe you can check this [sample](https://github.com/joshgeller/react-redux-jwt-auth-example)

**Comment by qburns** [comment]
@wellyshen I fixed it! Sorry for wasting your time. In case you decide to do it yourself or anyone else who comes across it:

In my store.js, I was calling browserHistory like so:

```
import { browserHistory } from 'react-router';
import { routerMiddleware } from 'react-router-redux';

export default (initialState) => {
  const middlewares = [
    thunk,
    routerMiddleware(browserHistory)
  ];
```

However, I needed to be calling it from /es6 directory like this:

import { browserHistory } from 'react-router/es6';

This has solved my issues with navigating programatically. I can now use push like expected:
```

import { push } from 'react-router-redux';
export const redirectUser = () => (dispatch) => {
  dispatch(push('/example'));
}
```

**Comment by wellyshen** [comment]
@qburns Alright, it's really a small detail, thanks for your sharing :)
