### ISSUE TITLE
Database connection

### ISSUE THREAD

**Issue by chengchihhan** [wellyshen/react-cool-starter#90]
In this boilerplate, I wanna run backend(express) as
api-server to connect my database(MySQL),
is there any example or a recommendation?

thanks

**Comment by wellyshen** [comment]
@chengchihhan 

Sorry, I'm not familiar with react + express API server. But I think you can create your own routes on express and fetch the MySQL data by API calling function (axios). Here's a simple [example](https://www.ibm.com/blogs/bluemix/2017/06/react-web-express-api-development-production/), maybe you can see it.

If you got fully understanding, please kindly to share it to me ;)

**Comment by martin2786** [comment]
Hi @wellyshen @chengchihhan This boilerplate already uses express so you can add a file with your API routes and register those on server.js, also you will need to add the controllers for the API and all the libraries to connect with MySQL, keep in mind that this will run in the same port as the react app. I recommend you set up another server dedicated for your API and make the change on the startup script to start both servers, one running in port 3000 and the other one in 3001 (it can be whatever you want) the logic behing this is that you may want to host the client and the API on different servers in production. 
To call the API from the react app you will need to point to the API url in the action.js on the container component where you want to fetch the data, in the boilerplate there is an example of getting github users by calling the github API so it will be similar but pointing to your API. The link welly posted about creating and express API should be enough to get you started. Hope this helps.

**Comment by chengchihhan** [comment]
Hi @wellyshen @martin2786 

I really appreciate your useful recommendations. Following above advice, I've set up my api server successfully in these days. In addition, I'm writing a simple example with this boilerplate, will share it
after I am done.

Thanks.
