### ISSUE TITLE
[webpack-isomorphic-tools] [error] asset not found: ./src/components/UserList/styles.scss

### ISSUE THREAD

**Issue by zolcman** [wellyshen/react-cool-starter#91]
I try remove component UserList from Home component. And I have error

```
[webpack-isomorphic-tools] [error] asset not found: ./src/components/UserList/styles.scss
==> 😭  Rendering routes error: TypeError: Cannot read property '_style' of undefined
```

**Comment by martin2786** [comment]
Did you remove the whole UserList folder or just removed the usage of Userlist on the home component?

**Comment by zolcman** [comment]
just comment this field import UserList from '../../components/UserList';

**Comment by martin2786** [comment]
You also need to remove this line from /utils/html.js 
              require('../components/UserList/styles.scss')._style
Since the component is no longer being imported, the style is not getting imported either and the html fails.

**Comment by zolcman** [comment]
thanks, man. just found this!

**Comment by martin2786** [comment]
no problem, glad to help 👍
