### ISSUE TITLE
Cannot load images with more than 10Kb

### ISSUE THREAD

**Issue by Satish-Gupta** [wellyshen/react-cool-starter#942]
## Images are not loading if the image size is more than 10Kb

The image stops working if the file size is more than 10Kb. 

![image](https://user-images.githubusercontent.com/6943258/99707702-eb071a80-2ac4-11eb-93f1-0742a3ad9f20.png)

If i change  **name: "[name].[contenthash:8].[ext]"** to **name: "[name].[hash:8].[ext]"** for images section in hooks.js then actual hash is used but then i get the following error
  
![image](https://user-images.githubusercontent.com/6943258/99710098-3e2e9c80-2ac8-11eb-8f7c-bf52b31f56b2.png)

**Comment by wellyshen** [comment]
@Satish-Gupta Sorry for the late, have you synced the **name** between `hooks.js` and [config.babel.js](https://github.com/wellyshen/react-cool-starter/blob/master/tools/webpack/config.babel.js#L98)?

**Comment by Satish-Gupta** [comment]
Hi, 
I have synced the hooks.js and config.babel.js and still having the same result.

- hooks.js

```
// Images
  require("asset-require-hook")({
    // Must use the same option with webpack's configuration
    extensions: ["gif", "jpg", "jpeg", "png", "webp", "svg"],
    publicPath: "/assets/",
    limit: 10 * 1024,
    name: "[name].[hash:8].[ext]",
  });
```

- config.babel.js

```
{
        test: /\.(gif|png|jpe?g|webp|svg)$/,
        use: [
          {
            // Any image below or equal to 10K will be converted to inline base64 instead
            loader: "url-loader",
            options: { limit: 10 * 1024, name: "[name].[hash:8].[ext]" },
          },
          {
            loader: "image-webpack-loader",
            // For each optimizer you wish to configure
            // Plz check https://github.com/tcoopman/image-webpack-loader#usage
            options: { disable: true },
          },
        ],
      },
```
If i remove the hash section in both of the above it works.

**Comment by wellyshen** [comment]
@Satish-Gupta Please solve it by your way now. I am going to implement the server-side bundling once the starter has been upgraded to webpack v5.

**Comment by Satish-Gupta** [comment]
@wellyshen, Sure. I will do so until the upgrade. Thank you.
